Data in Tables and Intro to SQL
Ada-Developers-Academy/core-unit-2 pull request #1
Opened 2021-03-01 20:16 UTC by tildeee

2021-03-29 21:34 UTC, anselrognlie reviewed
Comments for Data in Tables. Moving on to Intro to SQL

2021-03-29 21:34 UTC, anselrognlie commented on data-in-tables/activity-data-in-tables.md
> +
Steps 1 and 2 are basically the same, and it sounds strange that they are essentially unaware of each other. I think it's worth explicitly calling out this would be a good time to think about what columns are the same, what different decisions did they make... that sort of stuff.  This can be reinforced for #3 as well.

```suggestion

Compare the columns identified on the previous post with the columns for this one. Which are the same, which are different? Which did you notice in one but not the other?

```

2021-03-29 21:34 UTC, anselrognlie commented on data-in-tables/activity-data-in-tables.md
> +3. Together as a group, pull up the _listing_ page for the "For Sale" category and "Antiques" subcategory.
I feel like it could still be more clear that they should stay on the listing page rather than going through to an individual item.
```suggestion
3. Together as a group, pull up the _listing_ page for the "For Sale" category and "Antiques" subcategory. Do _not_ click through to an actual item.
```

2021-03-29 21:34 UTC, anselrognlie commented on data-in-tables/activity-data-in-tables.md
> +
Even though this is less similar than the previous two explorations, I think that could make a compare/contrast here more interesting.

```suggestion

Again, compare the columns identified in the previous examples with the columns for this one. Which are the same, which are different? Which did you notice in one but not the other?

```

2021-03-29 21:34 UTC, anselrognlie commented on data-in-tables/activity-data-in-tables.md
> +- When making a new post, a dropdown that includes all subcategories for that category to choose from
```suggestion
- When making a new post, display a dropdown that includes all subcategories for that category to choose from
```

2021-03-29 21:34 UTC, anselrognlie commented on data-in-tables/activity-data-in-tables.md
> +1. Get 10 usernames
Why would I get 10 arbitrary user names??? I can't think of a good reason to do this.

2021-03-29 21:34 UTC, anselrognlie commented on data-in-tables/activity-data-in-tables.md
> +For the following prompts, let your creativity think about _any_ app that could exist.
```suggestion
For the following prompts, let your creativity run free and think about _any_ app that could exist.
```

2021-03-29 21:34 UTC, anselrognlie commented on data-in-tables/activity-data-in-tables.md
> +1. In Part 2, did the columns for a post in "services" differ from the columns for a post in "for sale"? In what ways?
I feel like this is a better discussion had while doing part 2 rather than reviewing it here. I recommend moving the comparison steps up to step 2 (the suggestions I made), and then we don't really need this review question.
```suggestion
```

2021-03-30 21:43 UTC, anselrognlie reviewed
intro-to-sql

reviewed:
intro-to-relational-databases.md
intro-to-sql.instructor.md
sql-setup.md

remaining:
activity-intro-to-sql.instructor.md
activity-intro-to-sql.md
adding-new-records.md
deleting-records.md
problem-set-intro-to-sql.md
retrieving-records.md
updating-records.md

2021-03-30 21:43 UTC, anselrognlie commented on intro-to-sql/sql-setup.md
> +| Error Description                             | What It Could Mean                                                                                       |
adjust the left column width
```suggestion
| <div style="width:210px;">Error Description</div>                             | What It Could Mean                                                                                       |
```

2021-03-30 21:43 UTC, anselrognlie commented on intro-to-sql/sql-setup.md
> +
Whenever I've introduced a student to psql, they often forget the semicolon. That's listed in one of the entries, but the main way I see it is that psql just sits there waiting for further input. But so long as they haven't typed any part of another command, they can just type `;` to complete the prior command. Maybe incclude that in some form?

```suggestion
| `Nothing happens when I try to run a command`    | Most likely there is a semicolon missing, and the prompt is waiting for you to keep typing. Try just entering `;` on its own.           |

```

2021-03-30 21:43 UTC, anselrognlie commented on intro-to-sql/sql-setup.md
> +* Opened the Postgres terminal as user `postgres` with `$ psql -U postgres`
change tense to match the rest of the list

```suggestion
* Install PostgreSQL
* Open the Postgres terminal as user `postgres` with `$ psql -U postgres`
```

2021-03-30 21:43 UTC, anselrognlie commented on intro-to-sql/sql-setup.md
> +* Opened the Postgres terminal as user `postgres` with `$ psql -U postgres`
needs to match the list
```suggestion
* Install PostgreSQL
* Open the Postgres terminal as user `postgres` with `$ psql -U postgres`
```

2021-03-31 21:44 UTC, tildeee commented on data-in-tables/activity-data-in-tables.md
> +1. Get 10 usernames
Employee of the month? 😆 

Let's cut it; when I was writing this, I even thought "this list is prettyyyyy long"
^^^ you can't stop me from a semi-colon in my comments!

```suggestion
```

2021-03-31 21:47 UTC, tildeee commented on data-in-tables/data-in-tables.md
> +By focusing on this kind of table, we will be set up for recognizing patterns commonly found in software.
I'll take another stab at this, but I think that this lesson rests on students thinking about rows and columns, so I'm gonna push back against "lists" as the concept to ground us

2021-03-31 21:51 UTC, tildeee commented on data-in-tables/data-in-tables.md
> +| Finish my reading backlog      | 20                      | All of the books I haven't finished but said I would | No                            |
Let's keep it light and casual! I'd like to let it go.

2021-03-31 22:06 UTC, tildeee commented on data-in-tables/data-in-tables.md
> +By focusing on this kind of table, we will be set up for recognizing patterns commonly found in software.
I think just as a reader (and a writer), I'd be pretty sick of the shopping list example by now! I don't want to wear them out on it. I want to pull them into it with things that they've done for themselves in their own life! I want this to evoke that we're moving past one-dimensional lists, too, so I think that's why I feel strongly about not leading with shopping lists.

2021-03-31 22:16 UTC, tildeee commented on data-in-tables/data-in-tables.md
> +
I actually don't think that students need to know the acronym right now...? I get that the opportunity is RIGHT THERE for us to name it, but IMO it just comes across as naming it for the sake of naming it. I personally don't think it's worth assessing that knowledge right now, and this lesson is focused on re-shaping our non-programmer brains to programmer brains... I'm gonna fight for holding back on this definition in this lesson. I'm really into CRUD's definition as a "reveal" and for the student to experience, "well of course that exists, I could've made that up!"

2021-03-31 22:18 UTC, tildeee commented on course.yaml
> +
This file shouldn't exist in this repo, right?

2021-03-31 22:26 UTC, tildeee commented on data-in-tables/activity-data-in-tables.md
> +
I'm gonna always keep slowing you down-- I know it seems painfully slow, but comparing should come after a bunch of practice of doing the thing many times.

I'd like the activity to be focused on making the tables, actually. It's a bonus if they can compare and contrast them.

I promise promise promise that doing the table skill without comparison will help students. It's a lot to juggle! If this were a problem set and there were three prompts to make tables, I'd be interested in thinking about a comparison question for the fourth.

2021-03-31 22:28 UTC, tildeee commented on data-in-tables/data-in-tables.md
> +- Adding and deleting columns is painful; when we add a column, we'll need to go through each row and fill it in with some value. Deleting a column also means going through and modifying every record
I'm into this! About to accept it, BUT...

I'm re-reading through this section... is it necessary? Should we cut it?

2021-03-31 22:29 UTC, tildeee commented on data-in-tables/data-in-tables.md
> +- Adding and deleting columns is painful; when we add a column, we'll need to go through each row and fill it in with some value. Deleting a column also means going through and modifying every record
```suggestion
```

I'm re-reading through this section... is it necessary? Should we cut it?

I think when I was writing it, I wanted to plant this seed as a heads up because I was witnessing capstone or something hahahahahaha

I'm... actually in favor of cutting it? @anselrognlie

2021-04-01 05:34 UTC, anselrognlie reviewed
intro-to-sql reviews complete.

moving onto intermediate-sql

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +* title: Drop Books Table
```suggestion
* title: Intro to SQL
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +* title: Inserting New Publishers
```suggestion
* title: Intro to SQL
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +WHERE name = 'Dark Pony Gaming';
move the command output to after the command
```suggestion
SELECT * FROM publishers 
WHERE name = 'Dark Pony Gaming';
/* Should output:
 id |       name        |                  address                   
----+-------------------+--------------------------------------------
  6 | Dark Pony Gaming | 315 5th Ave S Suite 200, Seattle, WA 98104
(1 row)
*/
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +SELECT EXISTS(  SELECT * FROM information_schema.tables WHERE table_schema='public' AND table_name='reviews');
move command output to after command
```suggestion
SELECT EXISTS(  SELECT * FROM information_schema.tables WHERE table_schema='public' AND table_name='reviews');
/* Should output: 
 exists 
--------
 t
(1 row)
*/
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +VALUES('The greatest book ever!', 3, 'This comic was so inspring!', 4, 5);
move command output to after command
```suggestion
INSERT INTO reviews (title, product_id, body, creator_id, stars)
VALUES('The greatest book ever!', 3, 'This comic was so inspiring!', 4, 5);
/* Should output:
INSERT 0 1
*/
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +SELECT EXISTS(  SELECT * FROM information_schema.tables WHERE table_schema='public' AND table_name='books');
move command output to after command
```suggestion
/* 
To verify the table is gone run the following.
*/

SELECT EXISTS(  SELECT * FROM information_schema.tables WHERE table_schema='public' AND table_name='books');
/*
Should output (notice the "f"): 
 exists 
--------
 f
(1 row)
*/
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +* title: Inserting New Products
```suggestion
* title: Intro to SQL
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +When you finish, try your solution by creating the table and running your SQL statement in PSQL and then verify that the row appears with:
```suggestion
When you finish, try your solution by creating the table and running your SQL statement in `psql` and then verify that the row appears with:
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +When you finish, try your solution by creating the table and running your SQL statement in PSQL and then verify that the row appears with the following SQL query:
```suggestion
When you finish, try your solution by creating the table and running your SQL statement in `psql` and then verify that the row appears with the following SQL query:
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +WHERE name = 'Jimmy Corrigan';
output after command
```suggestion
SELECT * FROM products 
WHERE name = 'Jimmy Corrigan';
/* Should result with:
 id |      name      | publisher_id |        description         
----+----------------+--------------+----------------------------
  2 | Jimmy Corrigan |            3 | The smartest kid on earth.
(1 row)

*/
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +  'Semiautobiographical story of a young man raised in a strict evangelical tradition.');
```suggestion
INSERT INTO products (name, publisher_id, description)
VALUES ('Jimmy Corrigan', 3, 'The smartest kid on earth.');
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +* title: Updating Users
```suggestion
* title: Intro to SQL
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +When you finish, try your solution by running the following in psql and then verify that the row appears with the following SQL query:
```suggestion
When you finish, try your solution by running the following in `psql` and then verify that the row appears with the following SQL query:
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +
table users and specified user already exists from having run the setup sql file
```suggestion
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +
duplicate of the following instruction
```suggestion
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +WHERE first_name = 'Cade'
output to after
```suggestion
SELECT * FROM users
WHERE first_name = 'Cade'
/* Should result with:
 id | first_name | last_name |         email         
----+------------+-----------+-----------------------
  8 | Cade       | O'Moore   | cade.omoore@gmail.com
(1 row)
*/
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +INSERT ...
```suggestion
UPDATE ...
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +* title: SELECT products with publisher_id 3
```suggestion
* title: Intro to SQL
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +Write a SELECT statement to retrieve only the names of products who's publisher_id is 3
```suggestion
Write a SELECT statement to retrieve only the names of products who's `publisher_id` is 3
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +* title: Select products with publishers ids between 0 and 100
```suggestion
* title: Intro to SQL
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +Write a SELECT statement to retrieve the names and descriptions of products who's publisher_id is a 1 or 2 digit number.
```suggestion
Write a SELECT statement to retrieve the names and descriptions of products who's `publisher_id` is a 1 or 2 digit number.
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/sql-fixtures/create-products-table.sql
> +
There's a question asking for products with 1 or 2 digit publisher ids, but no 2 digit publisher ids. Adding this _should_ be ok, since the test result is read directly from the data.
```suggestion

INSERT INTO products (
  name,
  description,
  publisher_id
)
VALUES ('product 8', 'some description 8', 99);

```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +* title: Drop Books Table
```suggestion
* title: Intro to SQL
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +The user "Auster Alexandra" has retired.  Write an SQL statement to remove them from the users table.
```suggestion
The user "Auster Alexandra" has retired.  Write an SQL statement to remove them from the `users` table.
```

2021-04-01 05:34 UTC, anselrognlie commented on intro-to-sql/problem-set-intro-to-sql.md
> +WHERE first_name = 'Auster' AND last_name = 'Alexandra';
output after command
```suggestion
/* 
To verify the table is gone run the following.
*/

SELECT * 
FROM users 
WHERE first_name = 'Auster' AND last_name = 'Alexandra';
/*
Should output:
 id | first_name | last_name | email 
----+------------+-----------+-------
(0 rows)
*/
```

2021-04-01 05:37 UTC, anselrognlie commented on config.yaml
> +        Path: /intro-to-sql/deleting-records.md
The problem set looked ok. There's the question of where to link the sql script, but that's being tracked on that file.

2021-04-01 05:39 UTC, anselrognlie commented on course.yaml
> +
I'm not sure? I haven't set up any course sections. I imagine to get the unit that _is_ showing in core to show, this must already have been dealt with one way or another? 🤷

2021-04-01 06:26 UTC, anselrognlie reviewed
migrates the examples in intro-to-sql CRUD lessons to use the answer style introduced in deleting records.

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/retrieving-records.md
> +This statement selects the `author_name` column in the `authors` table.
```suggestion
<details style="max-width: 700px; margin: auto;">
  <summary>Answer</summary>

1. The name of the table is `authors`
1. The selected column is `author_name`

</details>
```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/retrieving-records.md
> +This selects all columns in the `drivers` table.
```suggestion
<details style="max-width: 700px; margin: auto;">
  <summary>Answer</summary>

1. The name of the table is `drivers`
1. All columns in the table are selected

</details>
```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/retrieving-records.md
> +This selects the `id`, `category`, and `title` columns in the `media` table.
```suggestion
<details style="max-width: 700px; margin: auto;">
  <summary>Answer</summary>

1. The name of the table is `media`
2. We select 3 columns: `id`, `category`, and `title`

</details>
```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
```suggestion
```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
```suggestion
```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
```suggestion
```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
```suggestion
```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
show description collapsed
```suggestion

<details style="max-width: 700px; margin: auto;">
  <summary>Answer</summary>

1. The name of the table is `authors`
1. For the column `author_name`, the updated value is `'(No Author)'`
1. All records in the table will be updated

</details>

```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
show description collapsed
```suggestion

<details style="max-width: 700px; margin: auto;">
  <summary>Answer</summary>
This query makes Driver #2 unavailable.

1. The name of the table is `drivers`
1. For the column `is_available`, the updated value is `false`
1. The record with `id` `2` will be updated

</details>

```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
show description collapsed
```suggestion

<details style="max-width: 700px; margin: auto;">
  <summary>Answer</summary>
This query gives Media #1 a new publication year and empty description.

1. The name of the table is `media`
1. We update 2 columns:
   1. For the column `publication_year`, the updated value is `'1990'`
   1. For the column `description_text`, the updated value is `NULL`
1. The record with `media_id` `1` will be updated

</details>

```

2021-04-01 06:26 UTC, anselrognlie commented on intro-to-sql/updating-records.md
> +
show description collapsed
```suggestion

<details style="max-width: 700px; margin: auto;">
  <summary>Answer</summary>
This query renames category `'album'` to `'Album'`.

1. The name of the table is `media`
1. For the column `category`, the updated value is `'Album'`
1. Any record with `category` `'album'` will be updated

</details>

```

2021-04-02 21:47 UTC, anselrognlie requested changes
Finished remaining section (intermediate-sql).  Be aware that the PR is getting tweaky.

Please be gentle!!! 🙏

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/problem-set-intermediate-sql.md
> +What purpose does the table in the middle serve?
incorrect hint
```suggestion
What does this mean?

![Many](../assets/intermediate-sql_database-relationships_erd-connection-many-no-text.png)
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/problem-set-intermediate-sql.md
> +![Many](../assets/intermediate-sql_database-relationships_erd-connection-many-no-text.png)
incorrect hint

```suggestion
![One](../assets/intermediate-sql_database-relationships_erd-connection-one-no-text.png)
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/problem-set-intermediate-sql.md
> +You have the following database.  Write a SELECT statement which uses a JOIN clause to combines the vendors and products tables.
```suggestion
We have the following database.  Write a `SELECT` statement which uses a `JOIN` clause that combines the `vendors` and `products` tables.
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/problem-set-intermediate-sql.md
> +If we look the `products` table has a foreign key, `vendor_id`.  Could you use that in the join clause.
```suggestion
Notice that the `products` table has a foreign key, `vendor_id`.  Can we use that in the join clause?
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/problem-set-intermediate-sql.md
> +You have the following database.  Write a SELECT statement which uses a JOIN clause to find the name of vendors who have products which cost less than 20.0.
```suggestion
We have the following database.  Write a `SELECT` statement which uses a `JOIN` clause to find the name of vendors who have products with a cost less than 20.
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/sql/problem-set.sql
> +CREATE TABLE ordersProducts (
```suggestion
CREATE TABLE orders_products (
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/sql/problem-set.sql
> +INSERT INTO ordersProducts (
```suggestion
INSERT INTO orders_products (
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/sql/problem-set.sql
> +INSERT INTO ordersProducts (
```suggestion
INSERT INTO orders_products (
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/sql/problem-set.sql
> +INSERT INTO ordersProducts (
```suggestion
INSERT INTO orders_products (
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/sql/problem-set.sql
> +INSERT INTO ordersProducts (
```suggestion
INSERT INTO orders_products (
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/sql/problem-set.sql
> +INSERT INTO ordersProducts (
```suggestion
INSERT INTO orders_products (
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/problem-set-intermediate-sql.md
> +You have the following database.  Write a SELECT statement which uses a JOIN clause to list the order ids for all the orders which include the product named `'Widget Tsunami'`.
```suggestion
We have the following database.  Write a `SELECT` statement which uses a `JOIN` clause to list the order ids for all the orders which include the product named `'Widget Tsunami'`.
```

2021-04-02 21:47 UTC, anselrognlie commented on intermediate-sql/problem-set-intermediate-sql.md
> +The database listed here has a join table `ordersProducts`.  Take a look at the section in [database joins](./database-joins.md) which gives an example of a many-to-many relationship.
```suggestion
The database listed here has a join table `orders_products`.  Take a look at the section in [database joins](./database-joins.md) which gives an example of a many-to-many relationship.
```

2021-04-06 05:39 UTC, tildeee commented on intermediate-sql/establishing-relationships.md
> +## Goals
I'm giving a long answer!!

I have this whole document of "Standards" that I like formalizing with the header "Learning Goals." These are meant to be bullet point lists only.

Goals, on the other hand, is for prose to say "Hey this isn't really part of the curriculum LEARNING GOALS" but there's a kind of nuanced reason for what we want.

I distinguish Learning Goals vs. Goals this way:

- If we ever changed stacks again for the curriculum, or needed a curriculum rewrite, I would want everything listed as "Learning Goals" to be something we try to preserve
- If we want to teach something outside of that, it'll be in just a "Goals" section

The scenario I'm picturing in my head is:

- When we were converting textbook-curriculum to core curriculum, I had all these thoughts like, "Is it vital that we keep teaching 'Rails View Helpers' or the equivalent of it in Flask" for instance. I also had frustration because I wasn't sure which topics were vital to keep, versus which ones were "nice to have." I wish I knew what was the "bare minimum" for us to teach, because, as you know, I would call textbook-curriculum _very bloated_ and in need of cutting.

- Forward-looking scenario: The first time I introduced Goals vs. Learning Goals in this curriculum was the "Intro to Decorators" lesson. Is it actually _necessary_ for students to learn about Python decorators to be successful in their career? Definitely not. But was it worth it to have for C15? ... Maybe!!!!!! But, at least now going forward, if someone thinks, "If we cut "Intro to Decorators," do we need to cover it somewhere else in the curriculum?" and we have a pretty "obvious" way to say "well the goal for this lesson was to get familiar with syntax for class and static methods... so as long as we accomplish that goal, we're good"

---

Another way I think about LGs is:

I want to be able to make a list of every LG in the curriculum and say "this is the contract of things we're going to try to deliver in the curriculum. No less."

I don't really want to add to that contract "Intro to Python Decorators" loool you know what I'm saying?


---

For this specific case, it's probably Learning Goals that's most appropriate. TBH, chris just kinda made these up and they aren't in my big ole list of learning goals, but uhhhhh I mean they're not bad/I don't think it's important to work through that 100% in this PR

2021-04-06 15:56 UTC, tildeee commented on intro-to-sql/activity-intro-to-sql.md
> +
I've been scrolling past this comment and I still feel closer to "resolving" this suggestion for now, and seeing if it comes up for C16. I'm pretty much like 55% on the side of "it lengthens this lesson just a little bit more than I think I wanna try for C15"

I'm gonna edit this suggestion to make a comment and check for C16

2021-04-06 16:26 UTC, merged