Testing our apis
Ada-Developers-Academy/core-unit-2 pull request #11
Opened 2021-04-02 00:21 UTC by tildeee

2021-04-22 19:56 UTC, anselrognlie reviewed
comments for environements-and-env-vars.md

this felt a little murky about what an environment was (is it our terminal, is it different machines, is it a database). Flask also has the FLASK_ENV variable that we don't discuss. I leaned into dance metaphor, but split it up a bit more according to my understanding. hopefully this jives with your objectives!

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +1. Define environment variables and manage them
revise the goals (plural, since more than one)
we don't go much into what "managing" means so I'd remove that from the second goal

```suggestion
Our goals are:

1. Define development and testing environments
1. Define environment variables
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +
if we still want to call out "manage" consider adding a dedicated third goal about managing
```suggestion
1. Start thinking about how to manage environment variables

```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +No, really. "Environment" is a common concept among many different situations. When in doubt, clarify with questions!
saying it's a common concept sounds like it should have the same meaning everywhere
rephrase to emphasize the definition is overloaded
```suggestion
No, really. "Environment" can mean many different things in many different situations. When in doubt, clarify with questions!
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +In the context of local project development and testing, there are two common patterns:
this is showing a single pattern with two parts
```suggestion
In the context of local project development and testing, we will commonly use two environments according to the following pattern:
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +| Name                    | Purpose                                                                                        | Differences                          |
Differences sounds a little vague given the actual values in the table
```suggestion
| Name                    | Purpose                                                                                        | <div style="min-width:200px">Configuration Details</div>                          |
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +| Development environment | Dedicated to rapid development. Things will change often as the developer works on the project | Has a dedicated development database |
explain what's in the development database, and call out debugging/logging
```suggestion
| Development environment | Dedicated to rapid development. Things will change often as we work on the project | Has a dedicated development database where we can add sample data we will use during development. May enable a debugging mode with detailed logging and error reports. |
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +| Testing environment     | Dedicated to setting up the data for running test suites.                                      | Has a dedicated testing database     |
what's special about the testing database?
```suggestion
| Testing environment     | Dedicated to running test suites.                                      | Has a dedicated testing database containing specific data used to exercise our test suite.     |
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +1. A _testing environment_ dedicated for holding test data
'to' sounds a little better to me and has agreement with the phrasing in the table
```suggestion
1. A _development environment_ dedicated to rapid development
1. A _testing environment_ dedicated to holding test data
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +As developers, we'll have access to both environments. Whenever we run our Flask API, we can designate it to use a specific environment.
we don't just _have_ access, we access them both a lot.
our discussions so far have made it sound like dev and test are completely distinct (and they can be), but since we'll be doing dev and test from our local machine, provide some explanation of why that is.
```suggestion
As developers, we access both environments.

As we develop our Flask API, we will work in our development environment. As we make changes to our code, we will test it frequently using our test environment. 

These two environments could exist on different machines. In practice, it is usually more convenient to have a way to run under either environment from our own developer machine. This allows us to test our code as we are working on it, minimizing the chance of breaking previous functionality (called a _regression_).

Whenever we run our Flask API, we can designate which environment to use.
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +The environment that our Flask API uses will determine which database it accesses while it runs.
the environment can affect even more, so keep this at the level of general customization, but provide the database as an example of this
```suggestion
We will customize how we set certain configuration settings in our Flask API—such as the database it will access—based on the environment.
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +Keeping these environments separate can help her have better expectations for what's available.
having expectations about what's available sounds like we're bracing ourselves for disappointment. try focussing on the clarity and focus we gain by using different environments for different purposes.
```suggestion
Keeping these environments separate helps Aleesha and the other dancers focus on doing specific things in each environment.
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +We can imagine Aleesha's practice room at home is like a _development environment_.
like I wrote above, we are basically using both dev and test together, so tie these concepts back to the metaphor.
```suggestion
We can imagine Aleesha's practice room at home is like her combined _development_ and _test_ environment.

As her _development_ environment, she can develop new dance routines in her own space. She can easily reconfigure the lighting and arrangement of things in that space to suit her work.

As her _test_ environment, she can practice and practice and make sure she has everything down before meeting with the rest of her dance team.
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +
Our metaphor has the studio and main stage parts as well. I'd like to explain where they fit into dev practice as well.
```suggestion

### !callout-info

## More Environments Are Possible

For now, we will focus on development and test environments. But there are other environments that are also useful.

<br />

We can have _staging_ environments, which are more like the practice studio used by Aleesha's whole team. It's a place where all the work they've done individually comes together and can be seen working as a whole. Since this is a shared space involving multiple people, it's harder to make changes here.

<br />

We will also have a _production_ environment. This is the main performance stage, where the rest of the world sees our hard work. Once the performance starts, we _really_ don't want to make changes!

### !end-callout

```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +As we introduce testing into our Flask API development, we will want to setup a dedicated testing environment. This will make our testing experience more consistent and reliable.
explain why we want this and how it makes the experience better
```suggestion
As we introduce testing into our Flask API development, we want it to be easy for our tests to run using our test environment settings.

Having dedicated test settings is important so that our tests can run under the actual conditions we want to test. Making this change automatic will help us avoid running tests using the wrong data.

This will make our testing experience more consistent and reliable.
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +Environment variables are strings that hold data outside of our application code. These variables are set at the environment level, and affect how an app is run.
the jump from environments to variables feels disjoint, so included a small transition sentence.
as a reader _ don't know that I can identify with something being set  "at the environment level". I modified it to say that our environments will provide ways to set this (there's an added callout a bit later showing a small example)
give some overview of the kinds of affects they have on our code. (the details come in later bullets)

```suggestion
We will use environment variables to store information about values that change between environments.

Environment variables are strings that hold data outside of our application code. The environments we use provide ways to set these kinds of values.

Within our code, we can examine these variables, and either use them directly as data, or use them to make decisions about how our code should behave.
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +- Where the location of other resources are (such as other services part of a larger software system)
don't need where (especially compared to the other bullets)
callback to connection string vocab
I kept reading part as a noun which was throwing my ability to parse the sentence
```suggestion
- The location of a database (a connection string)
- Locations of other resources (such as other services that are part of a larger software system)
```

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +
Add a callout showing a simple example of seeing and modifying environment variables
no suggestion because code
following comment includes the markdown

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +
### !callout-info

## There Are Many Environment Variables Set Already

From any terminal prompt, we can run the command `env`. This displays the environment variables currently set in our terminal. We can set our own environment variables from the terminal as well. Let's run the following:

```bash
$ export MY_NEW_VAR="my value"
```

<br />

If we then run `env` again, we will see our environment variable `MY_NEW_VAR` appear among the output.

### !end-callout

2021-04-22 19:56 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +Different tools, packages, and practices will give us ways to manage and hide our environment variables.
wound reorganizing this a bit
maintain the emphasis on avoiding committing
built a bit of a story about how we got from "values outside our code" to something we might accidentally commit.
included a callout emphasizing that we will be looking at just a small part of what goes into configuring environments.

```suggestion
Because environment variables are held outside of our code, they do not get checked into source control. This makes them very useful for storing _sensitive and secret data_.

- We might need a username and password to connect to a database.
- An API key is usually unique to our account. If someone else gets it, they can misuse a service acting under our identity.

As our applications grow, we may need to store a larger number of variables, to the point that using the `export` command becomes a problem. It would be nice if we could group our environment variables into a special file: a file that holds only our environment variables, and no code.

But once we have placed them in a file, we might accidentally commit that file. Because of the danger of misuse, we want to **avoid committing environment variables to source control**, where nefarious individuals could steal our credentials!

It seems like we're right back where we started!

In the next lesson, will explore how to manage our environment variables so that they remain organized, out of our code, and secure!

### !callout-info

## Many Ways to Customize Environments

Flask doesn't require a particular approach to setting environment configurations. We will keep our discussion of configuration focused on switching between databases and storing application secrets. Customizing configuration is a much larger topic, with many clever approaches to explore. Follow your curiosity!

### !end-callout
```

2021-04-23 07:09 UTC, anselrognlie reviewed
comments for dot-env-and-the-test-db

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +Based on the current state of this Flask app, let's look at a replacement for the `app/__init__.py` file, then go through the differences.
minor revision in first passage
I'd just say this is revised and call out what to watch for
minor changes to discussion reminder
```suggestion
Now that we've set up environment variables and the test database, let's change some configurations in our app to make use of them.

Let's look at a revised version of the `app/__init__.py` file that includes the changes needed to handle test mode. We'll examine the differences following the code.
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +    if test_config is None:
I assume we'll want to make a change like this following the slack discussion?
```suggestion
    if not test_config:
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +        db.create_all()
this will get done in the test runner code
```suggestion
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +| <div style="min-width:250px;"> Piece of Code </div> | Notes
improve the word wrapping
```suggestion
| <div style="min-width:310px;"> Piece of Code </div> | Notes                                                                                                                                                                                                                                                              |
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +| `import os`                                         | This built-in package will allow us to read the environment variables set in `.env`
this is a module, not a package
I'd just mention that it reads environment variables in general (even those not set through .env)
```suggestion
| `import os`                                         | This built-in module provides a way to read environment variables                                                                                                                                                                                |
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +| `load_dotenv()`                                     | The `python-dotenv` package specifies to call this method and load the variables before using them
here we can mention that this bridges between the .env file and the os module
add explanations for why we are adding the param to create_app
```suggestion
| `load_dotenv()`                                     | The `python-dotenv` package specifies to call this method, which loads the values from our `.env` file so that the `os` module is able to see them.                                                                                                                                                                  |
| `def create_app( ... ):` | Add a new keyword parameter to `create_app` that we can use to customize its behavior |
| `test_config=None` | We have called the new parameter `test_config` which should receive a dictionary of configuration settings. It has a default value of `None`, making the parameter optional. |
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +| `if test_config is None:`                           | Create a conditional based on the keyword argument `test_config`. Whenever we call `create_app()`, from now on, we can optionally pass in a tes
update for code agreement
most of this is moved up to the suggested new descriptions of the change to create_app
```suggestion
| `if not test_config:`                           | Check the keyword argument `test_config`. When we call `create_app()`, if `test_config` is falsy (`None` or empty), that means we are not trying to run the app in a test environment. |
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +Understanding how to read this code is more valuable than learning how to write it. Realistically, on many projects, test environments are set up. However, it's valuable to read this code in order to
untangle the line about setting up test environments: test environments get set up , and???
```suggestion
Understanding how to read this code is more valuable than learning how to write it. On many projects, we set up test environments by referring back to code from a previous project. But we should strive to be able to read this code in order to:
```

2021-04-23 07:09 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +Let's run our app in development mode with `(venv) $ flask run`, and make some requests in Postman. We can manually test all of our functionality to ensure we haven't lost anything.
some minor changes to the first 2 passages
slipped in a reference to regressions (introduced in a suggestion in the previous lesson)
```suggestion
We'll test our test environment after we set up tests in the next lessons!

For now, let's verify that we didn't break our development environment. These changes should not have affected our development environment at all!

Let's run our app in development mode with `(venv) $ flask run`, and make some requests in Postman. We can manually test all of our functionality to ensure we haven't introduced any _regressions_, broken scenarios which used to work.
```

2021-04-25 00:04 UTC, anselrognlie commented on testing-our-apis/fixtures.md
> +# Fixtures
Updated fixtures.md with content

2021-04-25 06:43 UTC, anselrognlie reviewed
comments for test-setup

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +We can continue to use tests and pytest to test our Flask APIs! Reading, writing, and using pytest for a Flask API isn't very different from using pytest outside a Flask API.
minor rewording to flow a bit better from the Fixture lesson. We've discussed a lot of this functionality in the previous lesson, so it should be less surprising that we'll be using tests in general, and pytest specifically.
```suggestion
We can build on our pytest knowledge to test our Flask APIs! Reading, writing, and using pytest for a Flask API isn't very different from using pytest outside a Flask API.
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +One main difference is the test setup. In this lesson, we'll configure our Flask projects to use pytest and a test database.
specify that this _is_ the main difference. one main difference leaves the door open for the reader to worry about what other differences are going to pop up.
```suggestion
The main difference is in how we set up our tests. In this lesson, we'll configure our Flask projects to use pytest and a test database.
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +
minor formatting
```suggestion

<br />

```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +- A `book` table defined in both databases
We haven't made (and won't explicitly make) the books table in the test database. We will be bypassing alembic's migration tracking and use the create_all/drop_all directly to set up and tear down the database with every run.
```suggestion
- A `book` table defined in the development database
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +An `.env` file that contains:
I read `.env` as dotenv, so we can use a instead of an.
```suggestion
A `.env` file that contains:
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +Endpoints defined for these RESTful routes. They handle missing books:
same change as in previous lesson
```suggestion
Endpoints defined for these RESTful routes. They can gracefully handle missing books:
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +Let's consider what these files will do:
consider sounds more like we have some familiarity and are thinking more deeply now, but we are getting our first look here.
```suggestion
Let's take a look at what these files will do:
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `__init__.py`                            | Establishes our `tests` package, so it can be properly connected with the rest of the app folders and files. We will probably leave it empty. |
cut probably
```suggestion
| `__init__.py`                            | Establishes our `tests` package, so it can be properly connected with the rest of the app folders and files. We will leave it empty, as we typically do. |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `conftest.py`                            | A conventional Flask file that will hold test configurations and common test helper functions                                                 |
conftest.py isn't flask specific. It's a standard file in pytest suites.
```suggestion
| `conftest.py`                            | A standard pytest file that holds test configurations and common test helper functions. Essentially, it is automatically `import`ed before any other test files.                                                  |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +        yield app
add line to create the database tables (moved from the app init)
```suggestion
        db.create_all()
        yield app
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `@pytest.fixture`                                   | We'll create and use a pytest fixture named `app`, which will be used in our `client` fixtured (defined below)
fixtured → fixture
the fixture is defined below the code we are discussing, but defined about the discussion itself. defined later sounds a little more "relative" to me.
```suggestion
| `@pytest.fixture`                                   | We'll create and use a pytest fixture named `app`, which will be used in our `client` fixture (defined later)                                                                                              |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `{"TESTING": True}`                                 | Here, we're passing in a dictionary to represent a "test config" object. If we check the current implementation of `create_app()` in `app/__ini
don't need the "if we check"
```suggestion
| `{"TESTING": True}`                                 | Here, we're passing in a dictionary to represent a "test config" object. The current implementation of `create_app()` in `app/__init__.py` uses this argument only to check if it's truthy (which this is!). |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `with app.app_context():`                           | This syntax designates that the following code should have an _application context_, or in this case, have access to objects such as `db`.
Give a bit of a hand-wavey overview of what this does, but still tie it back to the database access that we're doing here.
```suggestion
| `with app.app_context():`                           | This syntax designates that the following code should have an _application context_. This lets various functionality in Flask determine what the current running app is. This is particularly important when accessing the database associated with the app.                                                                   |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `yield app`                                         | This is pytest fixture syntax which executes the actual test at this moment. `yield app` finishes executing once the test has actually be run.
`yield` has now been discussed in the fixtures lesson, so we can be a little more precise in the description
```suggestion
| `yield app`                                         | This fixture suspends here, returning the app for use in tests or other fixtures. The lines after this `yield` statement will run after the test using the app has been completed.                                                              |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `with app....: db.drop_all()`                       | After the test runs, this code specifies that we should clear our test database from any data that was saved inside our test.
```suggestion
| `with app....: db.drop_all()`                       | After the test runs, this code specifies that we should clear our test database of any data that was saved inside our test.                                                                               |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +| `@pytest.fixture`                                   | We're setting up a second test fixture...
we've seen quite a few fixture declarations now (with the addition of the fixture lesson) so I think we can be more matter-of-fact here
```suggestion
| `@pytest.fixture`                                   | Set up a second test fixture                                                                                                                                                                   |
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +Understanding how to read this code is more valuable than learning how to write it. Realistically, on many projects, test environments are set up. However, it's valuable to read this code in order to
same edits as previous lesson with this callout
```suggestion
Understanding how to read this code is more valuable than learning how to write it. On many projects, we set up test environments by referring back to code from a previous project. But we should strive to be able to read this code in order to:
```

2021-04-25 06:43 UTC, anselrognlie commented on testing-our-apis/test-setup.md
> +While we're looking at `tests/conftest.py`, let's see a few ways we'll use `client`:
we've been looking at conftest for a bit, so considering is appropriate, which means we can look at (intentional) the commands rather than just see (automatic) them
```suggestion
While we're considering `tests/conftest.py`, let's look at a few ways we'll use `client`:
```

2021-04-25 17:40 UTC, anselrognlie reviewed
comments for activity-solar-system-api-tests

2021-04-25 17:40 UTC, anselrognlie commented on testing-our-apis/activity-solar-system-api-tests.md
> +1. Create the `planet` table with the columns `id`, `name`, and `description`, and the one additional column
this will be done by the upgrade command
```suggestion
```

2021-04-25 17:40 UTC, anselrognlie commented on testing-our-apis/activity-solar-system-api-tests.md
> +1. Create an `.env` file.
"a" to match ".env" being read as "dotenv"
```suggestion
1. Create a `.env` file.
```

2021-04-25 17:40 UTC, anselrognlie commented on testing-our-apis/activity-solar-system-api-tests.md
> +1. Populate it with two environment variables: `SQLALCHEMY_DATABASE_URI` and `SQLALCHEMY_TEST_DATABASE_URI`. Set their values to the appropriate value.
repetitive use of value, but we can be more specific anyway
```suggestion
1. Populate it with two environment variables: `SQLALCHEMY_DATABASE_URI` and `SQLALCHEMY_TEST_DATABASE_URI`. Set their values to the appropriate connection strings.
```

2021-04-25 17:40 UTC, anselrognlie commented on testing-our-apis/activity-solar-system-api-tests.md
> +   1. Reads the correct database location from `.env`
correct verb form
the os.environ is more accurately described as retrieving environment variables, and since we referred to the connection strings as environment variables in the previous step, using environment variable here is both more accurate and more consistent.
```suggestion
   1. Read the correct database location from the appropriate environment variables
```

2021-04-25 17:47 UTC, anselrognlie reviewed
comments for problem set

2021-04-25 17:47 UTC, anselrognlie commented on testing-our-apis/problem-set-testing-our-apis.md
> +1. Create an `.env` file.
same change as activity
```suggestion
1. Create a `.env` file.
```

2021-04-25 17:47 UTC, anselrognlie commented on testing-our-apis/problem-set-testing-our-apis.md
> +1. Populate it with two environment variables: `SQLALCHEMY_DATABASE_URI` and `SQLALCHEMY_TEST_DATABASE_URI`. Set their values to the appropriate value.
same change as activity
```suggestion
1. Populate it with two environment variables: `SQLALCHEMY_DATABASE_URI` and `SQLALCHEMY_TEST_DATABASE_URI`. Set their values to the appropriate connection strings.
```

2021-04-25 17:47 UTC, anselrognlie commented on testing-our-apis/problem-set-testing-our-apis.md
> +   1. Reads the correct database location from `.env`
same change as activity
```suggestion
   1. Read the correct database location from the appropriate environment variables
```

2021-04-25 17:48 UTC, anselrognlie commented on config.yaml
> +    Description: "Environments and Env Vars, dotenv and the Test DB, Test Setup, Using Tests, Problem Set: Testing Our APIs, Activity: Solar System API: Tests"
```suggestion
    Description: "Environments and Env Vars, dotenv and the Test DB, Fixtures, Test Setup, Using Tests, Problem Set: Testing Our APIs, Activity: Solar System API: Tests"
```

2021-04-25 21:33 UTC, anselrognlie reviewed
comments for using-tests

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| `assert response_body == []`                        | We can check all of the parts of response body that we need to verify. We can check it's contents, size, values, etc!              |
```suggestion
| `assert response_body == []`                        | We can check all of the parts of the response body that we need to verify. We can check its contents, size, values, etc!              |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Add this test to `tests/test_routes.py`, and now let's run them!
so far only one test
```suggestion
Add this test to `tests/test_routes.py`, and let's run it!
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +To run the tests, we use:
emphasize that we run this the same way as other tests
```suggestion
To run our Flask tests, we can use the same methods as for any other test. From the command line we can run:
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +
give vs code as an option
```suggestion
Or we can run them through the VS Code test panel.

```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Notice that we do _not_ need to run the Flask server to run the tests!
this is ok, but I feel like since we're talking about something that just happened, we should use past tense
```suggestion
Notice that we did _not_ need to run the Flask server to run the tests!
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Let's go to our `app/routes.py` file and temporarily break our `/books` endpoint. One way we can break this route is to return a response with a status code `418` immediately.
I feel like immediately on its own is sort of floating there, like does it mean we should make the change right now, or should that be the first line of the function (we want the latter meaning, but it feels more like the former)
```suggestion
Let's go to our `app/routes.py` file and temporarily break our `/books` endpoint. One way we can break this route is to return a response with a status code `418` before doing anything else in the function.
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +def books():
update according to function renaming
```suggestion
def handle_books():
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +    return Response("This is one broken response!", status=418)
Let's go all in on I'm a teapot. It might get the reader to search for what's going on with this code, which is amusing. The subsequent text in the lesson isn't affected by this change.
```suggestion
    return Response("I'm a teapot!", status=418)
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +
```suggestion

<br />

```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Our test made a `GET` request to `/books/1`. A `GET` to `/books/1` can only mean that our test made a request to our `book()` route.
update for function renaming
```suggestion
Our test made a `GET` request to `/books/1`. A `GET` to `/books/1` matches the `/books/<book_id>` route with the `GET` method. This is mapped to our `handle_book()` function.
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +- Let's visit our `book()` route:
update for function renaming
```suggestion
- Let's revisit our `handle_book()` function:
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +def book(book_id):
update for function renaming
```suggestion
def handle_book(book_id):
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Our `book()` route returns a `404` response if `book` is `None`.
update for function renaming
```suggestion
Our `handle_book()` function returns a `404` response if `book` is `None`.
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +  1.  What is the most line of code that most recently affected `book`?
```suggestion
  1.  What is the line of code that most recently affected `book`?
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Why would `Book.query.get(book_id)` return `None`? What are the reasons it behaved that way?
consider posing this in a more investigative tone
```suggestion
Why would `Book.query.get(book_id)` return `None`? What could cause it to behave that way?
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +- Let's dive into `Book.query.get(book_id)`.
we don't really get to see inside of this method, so phrase this a little differently
```suggestion
- What do we know about how `Book.query.get(book_id)` works?
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Our debugging questions can continue in this line of thought:
```suggestion
Our debugging questions can continue along this line of thought:
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +1. Is what we see inside our test database consistent with the test error?
this is going require some discussion and because the database contents are dropped after each test, checking the db state is tough... So generalize this. The next change will address how to draw the final conclusion.
```suggestion
1. Are there any books in the test database?
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +At this point, we should see that our test database has no book records inside of it.
just looking in the db won't provide any useful info at this point, so walk through the thought experiment that will allow us to understand why the test is failing.
```suggestion
This final question is harder to confirm than might be expected! In the Test Setup lesson, we very briefly looked at the `app` fixture. But the full significance of the `db.create_all()` and `db.drop_all()` lines within the fixture may not have been apparent.

At the start of _each_ test, `db.create_all()` will rebuild the entire test database, creating all the tables needed for our models. Crucially, these tables begin _empty_!

Then at the end of _each_ test, `db.drop_all()` deletes _all_ the tables from the database. This prevents any test data created during one test from contaminating later tests. But this also means that if a test is not actively running, the test database will appear to be _completely_ empty! We won't even see empty tables. There will be _no_ tables!

Using our ability to debug tests with breakpoints though VS Code, it _is_ possible to pause during the middle of a test, which would give us a chance to connect to the test database and check on its state. This can be very helpful for more complicated tests!

But for the time being, we need only apply the knowledge that `db.create_all()` recreates the test database tables in an empty state at the start of each test.

This means that when we try to get the `Book` with a primary key of `1`, no `Book` is found. `Book.query.get(book_id)` returns `None`, resulting in the `404 Not Found` response status code and the failure of our test!
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +To address our test failure, let's see one way to populate the test database.
looking at is more active than seeing
```suggestion
To address our test failure, let's look at one way to populate the test database!
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +We'll define parts of our "Arrange" sections inside of pytest fixtures.
mention other methods we could approach this, but then give a reason why fixtures is a better fit here
```suggestion
We could write code directly in our test to create data as part of our "Arrange" section. We could write helper functions if this data needs to be shared with other tests.

Or by using fixtures instead, we get data reusability and we explicitly list the data dependencies our test has!
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +Let's consider how we'll use fixtures to add test data:
rephrase to acknowledge that we have discussed the generalities of fixtures already.
```suggestion
Let's review some of the characteristics of fixtures, and consider how we can use them to add test data:
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| Question              | Answer                                                                                                                                         |
wrapping format
```suggestion
| <div style="min-width:100px;">Question</div>              | Answer                                                                                                                                         |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| What are fixtures?    | Each pytest fixture we define will describe something we want to happen before the test, such as saving test data.                             |
future sounds like we haven't seen how this works at all yet, but we have. so present sounds more general.
```suggestion
| What are fixtures?    | Each pytest fixture we define describes something we want to happen before a test. We could define a fixture that creates test data.                             |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| Where do fixtures go? | The fixtures can be defined in any file (such as `tests/test_routes.py`), but we will define most of our routes inside of `tests/conftest.py`. |
routes → fixtures
give some minimal justification for why we're putting our fixtures there 
```suggestion
| Where do fixtures go? | Fixtures can be defined in any file (such as `tests/test_routes.py`), but we will define most of our fixtures inside of `tests/conftest.py`. This automatically allows them to be used in multiple test files if needed. |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| Who uses them?        | Each test will state which fixtures they want to use, and each test can use multiple fixtures!                                                 |
now each of the previous rows is following a two-sentence pattern, so continue that here. I think this also helps emphasize the multiple fixture part.
```suggestion
| Who uses them?        | Each test states which fixtures they want to use. Each test can use multiple fixtures!                                                 |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| `def two_saved_books(...):`                         | We can name our fixtures whatever we want. `two_saved_books` is good enough, although we could think of more! |
what makes it good enough?
```suggestion
| `def two_saved_books( ... ):`                         | We can name our fixtures whatever we want. `two_saved_books` is a reasonable name that will help remind us what this fixture does. |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| `def two_saved_books(app):`                         | This fixture needs to request to use the `app` fixture, defined above, so we have access to our Flask app     |
follow previous explanations that list the params alone
the app fixture is in a previous lesson, not above in this lesson
we don't actually use the app param, but it's still important and we can say why (interestingly, because of the fixture param ordering, we can leave off app and it will still work, but it's still probably better to list the explicit dependency)
```suggestion
| `app`                         | This fixture needs to request the use of the `app` fixture, defined previously, so we know the test database has been initialized.     |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +| `db.session.commit()`                               | This line commits and saves our book to the database                                                          |
```suggestion
| `db.session.commit()`                               | This line commits and saves our books to the database                                                          |
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +To actually use this fixture in a test, we need to request this fixture by name.
repeated "this fixture" sounds odd, and since we've had a whole lesson on fixtures, I don't think we need the repetition here.
```suggestion
To actually use this fixture in a test, we need to request it by name.
```

2021-04-25 21:33 UTC, anselrognlie commented on testing-our-apis/using-tests.md
> +We should conclude that we need to update our test itself, finally! Let's fill in the expected test dictionary back in `tests/test_routes.py`. It should be consistent with whatever data we put in our
provide an explanation for how to interpret the test results
"should" sounds a little judgmental in the case that I the reader wasn't able to arrive at that conclusion on my own.
```suggestion
The output shows that the data coming back from our API looks reasonable, but that the value we are comparing to in our test has empty strings for each dictionary value.

We can conclude that we need to update our test itself, finally! Let's fill in the expected test dictionary values back in `tests/test_routes.py`. It should be consistent with whatever data we put in our fixture.
```

2021-04-25 21:35 UTC, anselrognlie requested changes
Finished review with comments.

Also, you'll want to review my uploaded fixture lesson.

2021-04-27 22:40 UTC, tildeee commented on testing-our-apis/dot-env-and-the-test-db.md
> +For our Hello Books API, we want to designate a path to a development database and a testing database with the variables named `SQLALCHEMY_DATABASE_URI` and `SQLALCHEMY_TEST_DATABASE_URI`.
Gonna bring this into an issues for a future refactor! I like the suggestion, it just happens to be a lot to refactor in one go. Thanks!

2021-04-27 23:07 UTC, tildeee commented on testing-our-apis/environments-and-env-vars.md
> +
YAYYYY staging!!! I wasn't brave enough to pull in staging but this is great!! Thanks!

2021-04-28 14:03 UTC, anselrognlie commented on testing-our-apis/dot-env-and-the-test-db.md
> +For our Hello Books API, we want to designate a path to a development database and a testing database with the variables named `SQLALCHEMY_DATABASE_URI` and `SQLALCHEMY_TEST_DATABASE_URI`.
Yeah, I definitely wouldn't change this right now.

2021-04-28 14:06 UTC, anselrognlie commented on testing-our-apis/environments-and-env-vars.md
> +
It _could_ get confused with the test environment, but I think the practice studio you provided in the metaphor will do a great job of helping the reader keep these things separate in their mind, even though we won't really be using staging environments.

2021-04-28 19:46 UTC, tildeee commented on testing-our-apis/fixtures.md
> +We can run this test file with `pytest test_fixtures.py`. If we are not in our Hello Books API environment, we may need to create a virtual environment and install `pytest` so that the `pytest` comma
Alternatively,

```suggestion
We can run this test file with `python3 -m pytest test_fixtures.py`.
```

2021-04-28 19:51 UTC, tildeee commented on testing-our-apis/fixtures.md
> +- This option properly declares the fixture, but doesn't list it in the test parameter list.
Suggest for this to be a numbered list for slightly greater ease of "following"/mapping to the above options

```suggestion
1. This option doesn't follow `pytest` naming conventions, so it will not be recognized as a test.
1. This option omits the `@pytest.fixture` decorator.
1. This option calls the fixture function directly. `pytest` disallows this and will raise an error.
1. This option is correct. It uses the decorator, follows `pytest` naming conventions, and declares the fixture as a dependency in its parameter list.
1. This option properly declares the fixture, but doesn't list it in the test parameter list.
```

2021-04-28 19:54 UTC, tildeee commented on testing-our-apis/fixtures.md
> +Let's look at a small test file. Let's run `touch test_fixtures.py` to create a new file, then paste in the following code.
For the sake of making a decision for them, I may recommend being really concrete here:

```suggestion
Let's create a small test file to practice using fixtures and tests. We can create this small test file in any folder of notes. Inside our notes folder, run `touch test_fixtures.py` to create a new file, then paste in the following code.
```

2021-04-28 19:58 UTC, tildeee commented on config.yaml
> +    Title: Testing Our Apis
```suggestion
    Title: Testing Our APIs
```

2021-04-28 20:56 UTC, tildeee commented on testing-our-apis/fixtures.md
> +Let's look at a small test file. Let's run `touch test_fixtures.py` to create a new file, then paste in the following code.
```suggestion
Let's create at a small test file that we'll use to experiment for this lesson. We'll only use this test for this lesson, so we'll delete this file at the end of the lesson. Inside of our Hello Books API project, let's run `touch test_fixtures.py` to create a new file, then paste in the following code.
```

2021-04-28 20:57 UTC, tildeee commented on testing-our-apis/fixtures.md
> +We can run this test file with `pytest test_fixtures.py`. If we are not in our Hello Books API environment, we may need to create a virtual environment and install `pytest` so that the `pytest` comma
```suggestion
Because we're in the Hello Books API project, let's activate our virtual environment. Then, let's run this test file with `pytest test_fixtures.py`.
```

2021-04-28 20:57 UTC, anselrognlie commented on testing-our-apis/fixtures.md
> +We can run this test file with `pytest test_fixtures.py`. If we are not in our Hello Books API environment, we may need to create a virtual environment and install `pytest` so that the `pytest` comma
We will specifically direct the reader to create this file in Hello Books API.

2021-04-28 21:05 UTC, anselrognlie commented on testing-our-apis/fixtures.md
> +Let's look at a small test file. Let's run `touch test_fixtures.py` to create a new file, then paste in the following code.
Thanks! Made a few edits to your comment. (tried to add my own comment to preserve your original input, but then GH wouldn't let me include my comment in the batch?)

2021-04-28 21:11 UTC, anselrognlie reviewed
just trying to get GH to stop thinking i'm in a review...

2021-04-28 21:11 UTC, anselrognlie commented on testing-our-apis/fixtures.md
> +We can run this test file with `pytest test_fixtures.py`. If we are not in our Hello Books API environment, we may need to create a virtual environment and install `pytest` so that the `pytest` comma
Thanks. Made some edits here too.

2021-04-28 21:18 UTC, anselrognlie commented on testing-our-apis/fixtures.md
> +
```suggestion

### !callout-info

## Let's Cleanup Our Test File!

We can delete the `test_fixtures.py` file from our project now! Or we can set it aside in another folder if we'd like to refer back to it later. But let's be sure to remove it from this project since it was only being used as an example for this lesson!

### !end-callout

```

2021-04-28 21:40 UTC, merged