Update lesson to reflect latest version of Hello-Books-API
Ada-Developers-Academy/core-unit-2 pull request #144
Opened 2024-04-10 22:16 UTC by yangashley

Asana Task: https://app.asana.com/0/1205655776549324/1207004723163589/f

Updates directory structure to include separate routes directory, fixes typos, updates sample requirements.txt with update package versions

2024-04-11 15:15 UTC, kelsey-steven-ada requested changes
This looks great so far, there are a couple code & instruction updates that we should add plus a fairly trivial suggestion.

2024-04-11 15:15 UTC, kelsey-steven-ada commented on api-1-setup-read/flask-setup.md
> +Werkzeug==3.0.1
That looks good, better to show the new versions over older/possibly deprecated versions.

2024-04-11 15:15 UTC, kelsey-steven-ada commented on api-1-setup-read/flask-setup.md
> +The `app/routes` directory will be responsible for holding our routes. We should organize our routes so that all the routes corresponding to a particular model will be written in a single file. For e
Not strictly necessary, but I was thinking the class name should be formatted as well.

```suggestion
The `app/routes` directory will be responsible for holding our routes. We should organize our routes so that all the routes corresponding to a particular model will be written in a single file. For example, all the endpoints related to the `Book` model would be written in a file called `book_routes.py`.
```

2024-04-11 15:15 UTC, kelsey-steven-ada commented on api-1-setup-read/flask-setup.md
> +To get started, we will include the following code in `__init__.py`. This is the starting, boilerplate code to start a Flask application. Follow your curiosity if you would like to learn more about [
It isn't letting me leave a comment on the line because it isn't changed, but we should update the `create_app` function below to remove the `test_config` parameter since we do not add that until pt. 6 with testing.

2024-04-11 15:15 UTC, kelsey-steven-ada commented on api-1-setup-read/flask-setup.md
> +Configurations for the app can include things like, "Where's the location of our database?," "How do we load different data models, the objects that represent our data?," or "How can we set up templa
It might be helpful to do a quick run through of the parent ticket for Part 1 to make sure everything was hit, on line 266 below we need to change the instructions for running Flask in debug mode to `flask run --debug`

2024-04-11 15:15 UTC, kelsey-steven-ada commented on api-1-setup-read/flask-setup.md
> +We can use the number labelled as `PID` (Process Identifier) to terminate the other running server with the command `kill -9 31756`, where we would replace `31756` with the `PID` value we got from ru
Love adding the full term here for clarity ❤️

2024-04-11 15:40 UTC, anselrognlie requested changes
I included some suggestions for a few other areas to look at (couldn't make literal suggestions for most since they weren't in modified areas). We should also make sure code snippets match the updated hello-books, and I think Kelsey had some recommendations to take into account.

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +Whenever we work on a Python project, we need to consider how we manage our dependencies which are the third party packages used by our project.
But by the  time students see this section, they will be using python 3.12, which will prevent them from pip installing system-wide at all, and we'll have started students using venvs as "projects" in precourse (and they'll have seen it on all the unit 1 projects), so I think this segue text could do with a re-flow. The main things for it to touch on should be:
1. Flask projects are Python projects, just like the other projects we've done.
2. We use venvs to manage our Python projects.
3. We will use a venv to manage our Flask project.
4. Here's a reminder on how to set up a venv for a project when the requirements are supplied to us.

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
>  Here is a sample `requirements.txt` for a Flask project:
In the previous two paragraphs, can we remove the "will"s? It's unnecessary and complicates the tense.

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
>     ### Common Debugging: Need to `$ pip install --upgrade pip`
I'd suggest condensing the callout titles. The titls on the one for upgrading `setuptools` now wraps (maybe due to changes in the Learn stylesheet?), leaving the info icon orphaned and looking strange. But if we rewrite that one, we should rewrite the others for consistency.
```suggestion
   ### Common Debugging: Upgrade `pip`
```

(I can't comment on the others since they aren't close enough to a modified region)

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
>  │   ├── models
Another errant "will" in the sentence above this treeview. provide → provides

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +The `app/routes` directory will be responsible for holding our routes. We should organize our routes so that all the routes corresponding to a particular model will be written in a single file. For e
Just pointing out that I'm not _always_ against more future/speculative tenses. While this _could_ be expressed in simple present (The `app/routes` directory is responsible), it also works with "will be" since we're discussing a hypothetical structure.

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +Configurations for the app can include things like, "Where's the location of our database?," "How do we load different data models, the objects that represent our data?," or "How can we set up templa
In the prior code, we chould leave off the `test_config=None`

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +Configurations for the app can include things like, "Where's the location of our database?," "How do we load different data models, the objects that represent our data?," or "How can we set up templa
I'm not a fan of the blueprints line
"How can we set up template views, called Blueprints?"

That sounds like it was written before we had a good idea of what all the pieces in Flask were for. It also (at least for a Flask app) doesn't feel very "configuration-y" to me. Really, the only one of the three that sounds like configuration is locating the database, but I guess we're just going for a high-level view of the chunks of code that generally end up in `create_app`.

Anyway, if we want to keep a third thing here, maybe use something like "How do we run different logic in response to different requests?"

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
>  ### !callout-danger
This callout feels very out of place to me. In combination with the general weakness of the description of configuraiton we give above, I feel like this just muddies the waters and creates a potential worry where none is required. Can we cut this?

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
For running the server in debug mode, didn't Kelsey recommend a new command for that rather than setting FLASK_ENV?

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
>  Python  31756  user    3u  IPv4 0x92416cca3d5db1fb      0t0  TCP localhost:commplex-main (LISTEN)
We may want to update the error message that's shown. Newer Flask versions also detect whether they are on macos and warn about that Apple service that grabs port 5000. We may want to include information here about disabling that service if we haven't included it elsewhere.

2024-04-11 15:40 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
In the server logs section below, I've had many students get confused about what's going on in the screen shot (they try to type in some of what's actually a part of the log output, and don't see anything happen.

Could we add a Figure caption that this is Flask log out in response to two web requests, and expand the text explanation so the steps to produce something similar are more clear?

2024-04-11 16:13 UTC, yangashley commented on api-1-setup-read/flask-setup.md
> +Configurations for the app can include things like, "Where's the location of our database?," "How do we load different data models, the objects that represent our data?," or "How can we set up templa
Oh yeah, good point, thanks for the reminder. I'll have a look at the parent ticket in addition to yours and Ansel's review comments.

2024-04-11 20:50 UTC, yangashley commented on api-1-setup-read/flask-setup.md
> +Since `flask` is a package with many of its own dependencies, we will need to use a `venv` to manage our Flask project so we do not make a mess of our system-wide Python installation.
@anselrognlie is this what you had in mind wrt your comment:

"Flask projects are Python projects, just like the other projects we've done.
We use venvs to manage our Python projects.
We will use a venv to manage our Flask project.
Here's a reminder on how to set up a venv for a project when the requirements are supplied to us."

?

2024-04-11 21:32 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +Since `flask` is a package with many of its own dependencies, we will need to use a `venv` to manage our Flask project so we do not make a mess of our system-wide Python installation.
I meant for that flow of topics to replace the entire existing chunk of content from Manage Dependencies to Virtual Environment.

The "Since `flask` is a package" and "In reality, no Python project" paragraphs serve no useful purpose, because we're going to get in the habit of using venvs for everything right away, so dwelling on the fact that it has its own dependencies doesn't inform why we will make a venv.

I'd stay away from phrasing best practices as "we will want to". Stick with we will, or we should. Leave the wanting aspect out of it. It hink this whol section could be boiled down to a single paragraph. Something like:

>As we start writing APIs, we should remember that Flask projects are themselves Python projects. Like any other Python project, we need to manage the packages our project depends on—its dependencies. Like other Python projects, we handle this by creating a `venv` in which to install the packages described in the `requirements.txt` file. Let's briefly review the steps we take to perform this setup.

2024-04-11 21:52 UTC, yangashley commented on api-1-setup-read/flask-setup.md
> +As we start writing APIs, we should remember that Flask projects are themselves Python projects. Like any other Python project, we need to manage the packages our project depends on—its dependencies.
@anselrognlie I removed the "Manage Dependencies" section and then incorporated your feedback about discussing Flask projects. 

Does this flow look ok?

2024-04-11 22:25 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +As we start writing APIs, we should remember that Flask projects are themselves Python projects. Like any other Python project, we need to manage the packages our project depends on—its dependencies.
Looks good. I also like the renaming of the section. Nothing special here. Flask projects are just Python projects!

One thing is that now that I read it in context, the "briefly review" here sounds repetative with the "brief review" in the first paragraph of the next section. How about changing this one to "revisit"?

```suggestion
As we start writing APIs, we should remember that Flask projects are themselves Python projects. Like any other Python project, we need to manage the packages our project depends on—its dependencies. Like other Python projects, we handle this by creating a `venv` in which to install the packages described in the `requirements.txt` file. Let's revisit the steps we take to perform this setup.
```

2024-04-12 16:55 UTC, anselrognlie requested changes
A few minor suggestions for the added content (thanks for the AirPlay stuff), but wanted to double check on a callout that I suggested cutting.

2024-04-12 16:55 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
Remove the following blank line and add two spaces after the image to force Learn to treat the caption as inline with the impage, but wrapped to the next line.
```suggestion
![Screenshot of Terminal, which includes Flask server startup messages, and output for request/response of a 404 error](../assets/building-an-api/flask-setup_server-logs-404.png)  
```

2024-04-12 16:55 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
>  ### !callout-danger
Were you going to cut the callout?

2024-04-12 16:55 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +If we know that we have not started the Flask server then we should check that the AirPlay Receiver is disabled like the Terminal output suggests. If it is enabled, we should disable it so that our c
Include a bit more detail about what to do.
```suggestion
If we know that we have not already started another Flask server then we should check that the AirPlay Receiver is disabled like the Terminal output suggests. If it is enabled, we should disable it by unchecking its 'On' checkbox, so that our computer can use port 5000 for running the Flask server. 
```

2024-04-12 16:55 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +
Remove the following blank line and add two spaces after the image to improve the caption formatting.
```suggestion
![Screenshot of System Preferences showing the AirPlay Receiver is disabled](../assets/building-an-api/system-preferences-airplay-receiver.png)  
```

2024-04-12 16:55 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
>  Python  31756  user    3u  IPv4 0x92416cca3d5db1fb      0t0  TCP localhost:commplex-main (LISTEN)
Thanks for adding this!

2024-04-12 16:55 UTC, anselrognlie commented on api-1-setup-read/flask-setup.md
> +_Fig. Screenshot of System Preferences showing the AirPlay Receiver is disabled._
Give a bit more direction in the caption
```suggestion
_Fig. Screenshot of System Preferences with the `On` checkbox for AirPlay Receiver unchecked, indicating the AirPlay Receiver is disabled._
```

2024-04-12 17:11 UTC, yangashley commented on api-1-setup-read/flask-setup.md
>  ### !callout-danger
ohhh i misread this and cut lines 234-235. Thanks for following up.

2024-04-15 16:45 UTC, anselrognlie approved these changes
LGTM!

2024-04-15 17:26 UTC, kelsey-steven-ada approved these changes
LGTM!

2024-04-15 17:27 UTC, merged