Building an API pt. 3 - lesson 2: "Models Setup" updates
Ada-Developers-Academy/core-unit-2 pull request #147
Opened 2024-04-12 19:02 UTC by kelsey-steven-ada

[Pt. 3 Asana ticket](https://app.asana.com/0/0/1206697443678568/f)
[Pt. 3 Lesson 2 ticket ](https://app.asana.com/0/1205655776549324/1207004723163600/f)

2024-04-12 19:05 UTC, kelsey-steven-ada commented on assets/api-3-database-models-read/spiderman_app_book.png
I felt the imports info was really dry so I added this image for some joy, but I'm good removing or replacing it if folks prefer.

2024-04-16 20:24 UTC, anselrognlie requested changes
There were a lot of changes in this lesson, so there was a lot to chew on. Happy to get together and chat through any of my suggestions or possible alternatives.

2024-04-16 20:24 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +5. `flask db upgrade`
Should we also include `\q` to mark getting out of `psql`. Otherwise, the implication could be that the `flask` commands are run from `psql`.

2024-04-16 20:24 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +5. `flask db upgrade`
This could also lead to a hint like "think about which commands are run directly in the database, and which are run from the shell."

We might then include an explanation that list the commands in order, and provides a brief summary of each

2024-04-16 20:24 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +* Check that we are setting `app.config['SQLALCHEMY_DATABASE_URI']` in `__init__.py`
Does the labelled syntax work for checkbox style questions?

2024-04-16 20:24 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +* Run the app and try to make a request to a route
I'm on the fence with this one. While sometimes a bad connection can result in a crash before the app starts listening (e.g., didn't set the connection string so it ends up None, or maybe a bad protocol is listed leading to plugin load failure), other configurations aren't detected until a request comes in (bad user/pwd/server/port/dbname). So issuing a request and reading the log error can tell you what the issue is. This overlaps with visually inspecting the connection string, but even the case where the app fails to load can be informative, since it can still help us differentiate between a few cases.

So I guess this feels more like a gotcha to me.

2024-04-16 20:24 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +* Run the app and try to make a request to a route - If the database connection can't be found, often the app will not compile so we cannot use this option.
I'd go with fails to startup rather than compile. But as mentioned above, I would argue this is a still a useful strategy and should be included as a correct answer, since the error message, whether at startup or when the request is sent, can help us determine the issue.

2024-04-17 15:20 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +Before we go any further, let's comment or remove our hardcoded `books` data and our two routes from the `app`.
I looked through some other lessons to check for consistency, and it looks like with the rest of the lessons that have a collapsible section after the branch table have them abut, so that should be left as is. The same for any that abut a Piece of Code table. The way everything fits together in those cases make it look like an intentional UI eleemnt.

But for cases of a summary detail following a paragraph, adding the line break helps the paragraph feel less cramped.

2024-04-17 16:38 UTC, kelsey-steven-ada commented on api-3-database-models-read/models-setup.md
> +
Agreed, I can revise that paragraph into a table and it should be easier to take in.

2024-04-17 16:38 UTC, kelsey-steven-ada commented on api-3-database-models-read/models-setup.md
> +
What do you think about this updated wording & callout?

```suggestion
If no change is detected, we should reflect on whether any recent model changes would require the database to be updated. For instance, if we add a helper method to a model class, only our code is affected, it doesn't change the data stored in the database. In that case, generating a migration isn't necessary, and if we try to do so, no changes will be detected. 

However, if we added a new attribute to our model, that _does_ need to update the database. We need to generate a migration to tell the database to create a new column for the new attribute. If generating a migration in that case detects no changes, we'll need to do more research to determine the issue.
	
### !callout-info

## Database Migration Issues 

Migrations can be a bit finicky to keep in sync, especially when multiple people are working on a project. We need to be careful about coordinating who is creating migrations and ensuring they are shared with the team to keep everyone's development database in sync. 

<br/>

We won't have the opportunity to invest much time in troubleshooting migrations during this series, but a common resolution can be to clear out the database and generate a fresh set of migrations. More details on how to do this are described in the "Resolving Schema Conflicts" reading a bit later on.

### !end-callout
```

2024-04-17 16:38 UTC, kelsey-steven-ada commented on api-3-database-models-read/models-setup.md
> +* Run the app and try to make a request to a route
Ahh, that's fair and something to avoid. I may just remove this option.

2024-04-17 16:38 UTC, kelsey-steven-ada commented on assets/api-3-database-models-read/spiderman_app_book.png
I made another version that has `Alembic` instead of `app.py`, I'm happy to sub that one in ^_^

2024-04-17 16:43 UTC, anselrognlie commented on assets/api-3-database-models-read/spiderman_app_book.png
I still wish I could remember where the other copy was. Did we maybe remove it at some point? We don't want to be called out for having stale memes! 😆

2024-04-17 16:47 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
Yep. That's it.

2024-04-17 16:49 UTC, kelsey-steven-ada commented on api-3-database-models-read/models-setup.md
> +* Check that we are setting `app.config['SQLALCHEMY_DATABASE_URI']` in `__init__.py`
I will play around with it and find out, I'm not sure

2024-04-17 16:51 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
Looks good. For the heading, how about

```
## The `psql` Prompt Provides Input Feedback
```

2024-04-17 17:00 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
>  ### Making the `Book` Model Visible to the `app` in `__init__.py`
I'm good with going all the way to Alembic. In the past, we've sort of downplayed its involvement, but at the end of the day, all those `flask db` commands are Alembic commands, and those are the commands that need the models to be visible prior to explicitly using them anywhere else.

2024-04-17 17:03 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
>  We can generate database migrations with the following command. This command should be run every time there's a change to a file in the `models` folder.
Works for me!

2024-04-17 17:11 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +
Love this, especially mentioning the effect of having multiple contributors. That was something that had crossed my mind that we should be more explicit about at least in roundtables, but seemed like it might be too much to give the consideration it needs what with everything else we're doing. Like it feels like there's enough content to justify a lesson on coordinating migrations on projects with multiple contributors.

But having any kind of mention is better than nothing! 🙏

2024-04-17 17:22 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +That might sound like a lot of work, but SQLAlchemy provides a class named `DeclarativeBase` that provides all of the operations our database backed models will need. We will make our own `Base` mode
I agree with swapping "that" to "which", since it's a non-restrictive clause. In that case, a comma is also recommended. In the second sentence, "that will be" has closer verb agreement with "we will make".
```suggestion
That might sound like a lot of work, but SQLAlchemy provides a class named `DeclarativeBase`, which provides all of the operations our database backed models will need. We will make our own `Base` model class that will be a subclass of `DeclarativeBase`. 
```

2024-04-17 17:28 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +We can read through the contents of that file:
That works, but I'm still bothered by "we can".

```suggestion
Let's look over the contents for `db.py` before copying it to our local file:
```

2024-04-17 18:18 UTC, kelsey-steven-ada commented on assets/api-3-database-models-read/spiderman_app_book.png
No crusty memes here! We might have removed it, I did a quick check and don't see it in Unit 1 or other Unit 2 lessons at least,  but I haven't looked at Industry prep/ Unit 3.

2024-04-17 20:55 UTC, anselrognlie requested changes
Thanks for the connection string table! I have some suggestions there and for the CFU. There was also a paragraph update I suggested but I don't see, and then assorted minor updates.

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +d| Check that we are setting `app.config['SQLALCHEMY_DATABASE_URI']` in `__init__.py`
With the labeled options, the solution should be able to be listed as just
```suggestion
a|
b|
d|
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +d| Check that we are setting app.config['SQLALCHEMY_DATABASE_URI'] in `__init__.py` - We need to give this dictionary key the value of our database connection string for Flask to know where the datab
In the explanation, the labels aren't treated specially, so a plain bullet will have cleaner formatting.

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +3. `\q``- Quit the `psql` command line interface
```suggestion
3. `\q` - Quit the `psql` command line interface
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +That might sound like a lot of work, but SQLAlchemy provides a class named `DeclarativeBase` which provides all of the operations our database backed models will need. We will make our own `Base` mod
I'd still include this comma for the non-restrictive clause
```suggestion
That might sound like a lot of work, but SQLAlchemy provides a class named `DeclarativeBase`, which provides all of the operations our database backed models will need. We will make our own `Base` model class that will be a subclass of `DeclarativeBase`. 
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +With our `Base` model in hand, we can create a new file in the `app` folder `db.py` which will manage creating our database and migration objects:
non-restrictive clause comma
```suggestion
With our `Base` model in hand, we can create a new file in the `app` folder `db.py`, which will manage creating our database and migration objects:
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +2. Next, we create an instance of SQLAlchemy that we will call `db` and pass it our `Base` class as the constructor argument. We will use the `db` object when we need to interact with the database to
non-restrictive clause
```suggestion
2. Next, we create an instance of SQLAlchemy, which we will call `db`, and pass it our `Base` class as the constructor argument. We will use the `db` object when we need to interact with the database to perform operations like creating or updating records.
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +| `postgresql+psycopg2` | This tells Flask to connect to our database using the `psycopg2` package we installed from our `requirements.txt`. |
Thanks for including the table! How about chunking them up like this (and the following)
```suggestion
| `postgresql+psycopg2` | Contains information about the protocols to use for connecting to the database. This tells Flask to connect to our `postgresql` database using the `psycopg2` package we installed from our `requirements.txt`. |
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +| `://postgres:postgres` | We connect to the database using the `postgres` protocol and the user `postgres` |
```suggestion
| `://` | Required URL syntax to separate the protocol part from the user or host part. |
| `postgres:postgres` | Contains information about the user credentials to use to connect to a resource, here, the database. We connect to the database using the `postgres` user (the part before the `:`), using the password `postgres` (the part after the `:`). We never actually set a database password, but when connecting to a local PostgreSQL service, the supplied password value is ignored anyway and could be omitted. It is included here for completeness. |
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +| `@localhost:5432` | We are connecting to the local machine (`localhost`) running at port `5432` |
```suggestion
| `@` | Required URL syntax to separate the user part from the host part. |
| `localhost:5432` | Contains information about the host (the machine "hosting" the database) location. We are connecting to the local machine (`localhost`) running at port `5432` |
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +| `REPLACE_THIS_LAST_PART_WITH_DB_NAME` | This text should be replaced with the name of the database we're connecting to. For the hello-books-api project, we will replace it with our development data
```suggestion
| `/` | Required URL syntax to separate the host part from the path part. |
| `REPLACE_THIS_LAST_PART_WITH_DB_NAME` | Normally contains path information about the resource being accessed. This text should be replaced with the name of the database we're connecting to. For the hello-books-api project, we will replace it with our development database's name, `hello_books_development`. |
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +```
undecorated, there's some weird coloration going on
```suggestion
```text
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +Recall that SQL permits us to define columns that allow NULL values. In the past, SQLAlchemy would default to allowing NULL values for all columns unless otherwise marked. In the current version, col
shifts the aside to avoid splitting the restrictive clause
```suggestion
Recall that SQL permits us to define columns that allow NULL values. In the past, SQLAlchemy would default to allowing NULL values for all columns unless otherwise marked. In the current version, columns using `Mapped` types that are not explicitly marked `Optional`, as above, are considered non-nullable; they are required attributes when creating a new instance of a model.
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +Although the command `flask db init` sounds like it should initialize our database, in reality, it doesn't look at the database at all! This command creates our project's migrations folder, which Ale
```suggestion
Although the command `flask db init` sounds like it should initialize our database, in reality, it doesn't look at the database at all! This command creates our project's `migrations` folder, which Alembic will use to store its generated migration files.
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +If no change is detected, we should reflect on whether any recent model changes would require the database to be updated. For instance, if we add a helper method to a model class, only our code is af
separates the two clauses. could use ; instead
```suggestion
If no change is detected, we should reflect on whether any recent model changes would require the database to be updated. For instance, if we add a helper method to a model class, only our code is affected. It doesn't change the data stored in the database. In that case, generating a migration isn't necessary, and if we try to do so, no changes will be detected. 
```

2024-04-17 20:55 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
I had made a suggestion to replace the "At the introductory..." passage above with
```md
In situations where we need to have more control over the migration process, we may need to review a generated migration file and modify the code in either the `upgrade` or `downgrade` functions. Pregenerated comments in those functions even encourage us to make adjustments! We probably won't need to make such modifications at this point, but it's good practice to at least review the migrations before applying them in order to confirm that the generated result matches our expectations.

Skimming through the generated migrations is good practice for reading code and making assumptions about what it will do based on the context.
```

2024-04-17 21:44 UTC, kelsey-steven-ada commented on api-3-database-models-read/models-setup.md
> +| `postgresql+psycopg2` | This tells Flask to connect to our database using the `psycopg2` package we installed from our `requirements.txt`. |
Definitely more complete information, thanks for including the suggestions!

2024-04-17 21:44 UTC, kelsey-steven-ada commented on api-3-database-models-read/models-setup.md
> +We probably won't need to make such modifications at this point, but it's a good habit to at least review the migrations before applying them in order to confirm that the generated result matches our
I was struggling with the one sentence alone that didn't feel fully thematically linked and made some small adjustments, let me know what you think.

2024-04-17 21:50 UTC, anselrognlie commented on api-3-database-models-read/models-setup.md
> +We probably won't need to make such modifications at this point, but it's a good habit to at least review the migrations before applying them in order to confirm that the generated result matches our
Works for me!

2024-04-17 21:51 UTC, anselrognlie approved these changes
LGTM. Ship it!

2024-04-17 21:52 UTC, merged