Building an API pt. 3 - lesson 3: "Create" updates
Ada-Developers-Academy/core-unit-2 pull request #149
Opened 2024-04-16 20:37 UTC by kelsey-steven-ada

[Pt. 3 Asana ticket](https://app.asana.com/0/0/1206697443678568/f)
[Pt. 3 Lesson 3 ticket](https://app.asana.com/0/1205655776549324/1207004723163601/f)

2024-04-16 20:40 UTC, kelsey-steven-ada commented on assets/building-an-api/create-and-read_create-postman.png
My PR for the prior lesson created a folder under assets for images in Pt. 3. Once that PR is merged in, I plan to update the location of this image to better organize our assets folder.

2024-04-16 20:41 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +| `201 Created`   | `{ "id": 1,`</br>&nbsp;&nbsp;`  "title": "Fictional Book Title",`</br>&nbsp;&nbsp;`  "description": "A fantasy novel set in an imaginary world" }` |
Please let me know if anyone knows a better way to format a chunk of code in a table like this 🙏🏻

2024-04-16 22:03 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> + This tells the route to treat a URI the same whether or not it ends in `/`. Accepting either variation can make using our API a little easier for clients.
Remove this whole section about blueprints & "/", it's duplicated from an earlier lesson and doesn't feel important to reinforce for students.

2024-04-16 23:17 UTC, anselrognlie commented on api-3-database-models-read/create.md
> + This tells the route to treat a URI the same whether or not it ends in `/`. Accepting either variation can make using our API a little easier for clients.
Ha ha. Why on earth did we feel the need to duplicate this? Maybe it started here and then got pulled forward?

In any case, I'd be onboard with removing it here.

2024-04-17 00:46 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +| `201 Created`   | `{ "id": 1,`</br>&nbsp;&nbsp;`  "title": "Fictional Book Title",`</br>&nbsp;&nbsp;`  "description": "A fantasy novel set in an imaginary world" }` |
Ooo, I haven't tried a raw HTML table, so I'll give that a go. Thanks for the suggestion!

2024-04-17 22:41 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +| `201 Created`   | `{ "id": 1,`</br>&nbsp;&nbsp;`  "title": "Fictional Book Title",`</br>&nbsp;&nbsp;`  "description": "A fantasy novel set in an imaginary world" }` |
In an HTML table, if I wrap the dictionary in <code> tags, it collapses the whitespace and I still need to add characters for new lines and spacing. If I use <pre> around <code> it keeps the dictionary structure, but it adds spacing around the code such that it looks a bit weird 😭

I will say that the HTML table is a bit easier to parse than the line holding the dictionary as markdown, and I do think the rendered result is easier to read with the <pre> tag than the magenta code highlighting. I don't love the idea of us maintaining a bunch of custom formatting for a single table to try to fix the spacing  with <pre>, but I'm down if the team overall is.

Some of my experimenting:

![Screenshot 2024-04-17 at 3 18 42 PM](https://github.com/Ada-Developers-Academy/core-unit-2/assets/97124999/eba41413-8c6b-4cc2-a603-afb8afdd909e)
![Screenshot 2024-04-17 at 3 34 52 PM](https://github.com/Ada-Developers-Academy/core-unit-2/assets/97124999/25acb186-b22d-42e2-8e8a-5bf2b71b252a)

2024-04-17 22:58 UTC, anselrognlie commented on api-3-database-models-read/create.md
> +| `201 Created`   | `{ "id": 1,`</br>&nbsp;&nbsp;`  "title": "Fictional Book Title",`</br>&nbsp;&nbsp;`  "description": "A fantasy novel set in an imaginary world" }` |
Yeah, I think this is really promising. The only other alternative that I can see would be to stop using a table entirely. In the same way that we use inline styles to modify column widths, could that clobber whatever margin/padding is affecting the pre?

2024-04-17 23:27 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +| `201 Created`   | `{ "id": 1,`</br>&nbsp;&nbsp;`  "title": "Fictional Book Title",`</br>&nbsp;&nbsp;`  "description": "A fantasy novel set in an imaginary world" }` |
Success! 
![Screenshot 2024-04-17 at 4 27 19 PM](https://github.com/Ada-Developers-Academy/core-unit-2/assets/97124999/581170d5-4893-40ae-a40d-a5924745784b)

2024-04-18 01:59 UTC, anselrognlie commented on api-3-database-models-read/create.md
> +| `201 Created`   | `{ "id": 1,`</br>&nbsp;&nbsp;`  "title": "Fictional Book Title",`</br>&nbsp;&nbsp;`  "description": "A fantasy novel set in an imaginary world" }` |
Woo!

2024-04-24 20:47 UTC, anselrognlie requested changes
The usual text suggestions and so forth. The biggest thing that came out of this was our discussion about make_response, which will be removed from this lesson.

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
>  ### !callout-info
With the moving of `make_response`, can we cut this callout?

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
For the line above, "throughout this should" → "throughout this series should"? Though, I actually find that whole passage a little off kilter.

Maybe
> Unlike our GET routes, we can't directly test a POST route using the browser. This is because when we type an address into the browser's address bar, it always makes a GET request to that address. This was exactly what we needed to check that our get book routes were working, but won't help us try out our create book route. Instead, we'll use Postman to send a POST request that includes the necessary data in the request body.
>
> To do so, in Postman, we:

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
> +- Configure an HTTP response body to `raw` and `JSON`, and add in the sample request body:
rewords to map more closely to the language in the UI. Also request, not response
```suggestion
- Select the request `Body` tab, using the `raw` option with `JSON` selected in the list that appears, then add in a sample request body such as:
```

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
> +_Fig. Screenshot of using Postman to send a POST request to create a Book. ([Full size image](../assets/api-3-database-models-read/create-postman-output.png))_
we don't need to say this is a screenshot
```suggestion
![The Postman query interface configured as described in the text. The request was successful, so the response area shows a JSON object for the created Book object.](../assets/api-3-database-models-read/create-postman-output.png)
_Fig. A successful POST request to create a book, sent using Postman. ([Full size image](../assets/api-3-database-models-read/create-postman-output.png))_
```

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
>  Lastly, don't forget to exercise patience! It takes patience to discover how to debug with so many tools, windows, and screens.
We're not really talking about debugging here, so this sounds out of place. I'd lean towards cutting it, or rephrasing it more like this. Maybe it should be a callout in that case?
```suggestion
We have many tools to juggle while building and testing our endpoints, and it can take time to get a feel for how to use them all together in a development workflow. Be patient wwith yourself!
```

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
>  Recall that our tools for debugging include:
this feels like it needs some additional support.

```suggestion

For the theoretical developer writing the code in this lesson, everything worked on the first try. They used Postman to send a request and they got back the appropriate response. But everything working correctly on the first try is much more the exception than the rule.

If we try to exercise a route and it _doesn't_ work, first of all, we shouldn't feel bad about it. Running into issues is common and expected. But the next thing we should do is remember that our routes are code just like any other code, and we can debug them. Because we're working with a database, we may also need to check whether the expected data exists as a result of our endpoints.

We haven't looked at how the VS Code debugger can be used to step through our route code (though this is possible!), but we do already have several other tools that can help us zero in on the cause of a problem:

```

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
>  - Using the server logs
It's easy for folks to forget that the "logs" we mean are just what Flask prints in the terminal (at least during development)
- also, what should we look for in the logs
```suggestion
- Using the server logs (displayed in the terminal while Flask is running) to check status codes, error details, and `print`ed output
```

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
> +    return make_response(response, 201)
Per today's curriculum discussion, switch to tuple return
```suggestion
    return response, 201
```

2024-04-24 20:47 UTC, anselrognlie commented on api-3-database-models-read/create.md
> +* type: multiple-choice
❤️

2024-04-24 21:40 UTC, kelsey-steven-ada commented on assets/api-3-database-models-read/create-postman-output.png
Ahh, good point, I'll update the screenshot

2024-04-24 22:07 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +</table>
I think this is something we should do across the curriculum and I will make a ticket for that, I'm betting we have other code examples in tables that would benefit from switching to an HTML table. 

Around the Pt. 1 Read All Books table, I want to update lessons we touch as we go. My feelings are that continuing the flask & content updates through the remaining lessons is higher priority than going back to format that table now even though it's a small change, but if other folks feel strongly about addressing it sooner, I'm good.

2024-04-24 22:30 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +    return make_response(response, 201)
Changes have been made to the hello-books-api branches, I'll update any code samples through the lesson to remove `make_response` in the create route.

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
>  | `url_prefix="/books"`                                 | A keyword argument. This `url_prefix` indicates that _every_ endpoint using this Blueprint should be treated like it starts with `/books`. We
I get that it will reinforce the info, but it isn't the focus of the lesson so I'm happy to leave it off rather than repeat it.

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
>  | `db.session.add(new_book)`                            | `db.session` is the database's way of collecting changes that need to be made. Here, we are saying we want the database to add `new_book`.
I see what you mean... I think it's just different enough that I'm not sure how helpful students will find the comparison.

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
>  | `make_response(...)`                                  | This function instantiates a `Response` object. A `Response` object is generally what we want to return from Flask endpoint functions.
Leaving a note to self to update the table along with code examples for the changed return statement.

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
>  ### !callout-info
Yeah, it doesn't make much sense now we're returning a tuple, which folks have already seen.

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +Recall that we we have already registered `book_bp` in in `app/__init__.py` inside our `create_app`. function.
That gives much more use to this section! I was considering cutting it, but I felt like some acknowledgement was useful.

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
This does read much clearer than the original, I like that change.

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +    return make_response(response, 201)
I'll go through & update each of these options

2024-04-24 22:51 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +</table>
Ticket: https://app.asana.com/0/1201700438643002/1207164657931567/f

2024-04-24 23:04 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +Recall that we we have already registered `book_bp` in in `app/__init__.py` inside our `create_app`. function.
GitHub wasn't letting me apply the initial suggestion, retrying by highlighting just the changed content.

```suggestion
When we set up our initial book routes (which are currently commented out), we registered them on a Blueprint using the Blueprint route decorator functions. Then we had to remember to register the entire Blueprint with the `app`, so that the `app` would know about the endpoints grouped under the Blueprint.

Since we have already registered `book_bp` in `app/__init__.py` inside our `create_app` function, as we add additional routes to our Blueprint, `app` will be able to see them without needing to go back and updating the `create_app` function again. But if we create any additional Blueprints, then we'll need to be sure to register them with the `app` the same way we did with `book_bp`.
```

2024-04-24 23:05 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +Recall that we we have already registered `book_bp` in in `app/__init__.py` inside our `create_app`. function.
GitHub wasn't letting me apply the initial suggestion, retrying by highlighting just the changed content.

```suggestion
When we set up our initial book routes (which are currently commented out), we registered them on a Blueprint using the Blueprint route decorator functions. Then we had to remember to register the entire Blueprint with the `app`, so that the `app` would know about the endpoints grouped under the Blueprint.

Since we have already registered `book_bp` in `app/__init__.py` inside our `create_app` function, as we add additional routes to our Blueprint, `app` will be able to see them without needing to go back and updating the `create_app` function again. But if we create any additional Blueprints, then we'll need to be sure to register them with the `app` the same way we did with `book_bp`.
```

2024-04-24 23:25 UTC, anselrognlie commented on api-3-database-models-read/create.md
> +</table>
But shh... I might have snuck in the change to api-2-lesson-1 since we had just seen that during the review today.

2024-04-25 18:02 UTC, anselrognlie approved these changes
LGTM. I did notice one of my previous suggestions caused me to stumble this time around, and then juts a minor bit of text that could possibly be removed.

2024-04-25 18:06 UTC, kelsey-steven-ada commented on api-3-database-models-read/create.md
> +| `201` | The second value in the `tuple`, `201`, is the response code. When a second value isn't specified, `200` is always the default value. |
I'm happy to cut it since it would have just been in the previous lesson or two, if there was a bit more space between the initial info and here I wouldn't mind repeating as a reminder.

2024-04-25 18:07 UTC, merged