Building an API pt. 2 - lesson 2: "Error Handling" updates
Ada-Developers-Academy/core-unit-2 pull request #151
Opened 2024-04-17 22:14 UTC by anselrognlie

Lesson Task: https://app.asana.com/0/1205655776549324/1207004723163598/f
Part 2 Task: https://app.asana.com/0/1202084167808449/1206697443678567/f

2024-04-23 20:32 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
> +<!-- prettier-ignore-end -->
I "rotated" the table to avoid the narrow columns wrapping the values unnecessarily, following our Pieces of Code/Notes pattern. I think this works pretty well (open to different column header names), and is probably worth considering elsewhere in the curriculum if we have single row tables with more than 2 columns.

2024-04-24 17:00 UTC, kelsey-steven-ada requested changes
A couple small changes & questions for discussion. Much appreciation for some of the table formatting/updates!

2024-04-24 21:49 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
> +1. If no `book` record matches the `book_id`, the server will return a `404` response code with a message indicating that there are no `book`s with `book_id`.
Maybe? Is it the class? Is it the table name (we're talking about records)? Is it just formatting to make it stand out? Who can say. But if you interpretted it as the class name, I'm happy to capitalize it. 😁

2024-04-24 21:58 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
> +There is a single explicit `return` in this function, but we only reach it if the condition `book.id == book_id` is `True`. That is, we need to find a book with a matching ID in order for the `return
Hmm. Looking at the disassembly for a function with no return
```
def no_ret():
  pass
```

produces
```
>>> dis(no_ret)
  1           0 RESUME                   0

  2           2 RETURN_CONST             0 (None)
```

Python literally added a `RETURN_CONST (None)` opcode to the end. I wasn't sure whether that was the case, or whether it was language shenanigans that took care of dealing with the `None`. So how about:

```suggestion
There is a single explicit `return` in this function, but we only reach it if the condition `book.id == book_id` is `True`. That is, we need to find a book with a matching ID in order for the `return` to execute. If we never find a book with a matching ID, the loop will complete without returning anything, eventually reaching the end of the function.

As we know, in Python, a function that completes without an explicit `return` statement still returns `None` behind the scenes. This behavior is what Flask is seeing, which triggers the error message.
```

2024-04-24 22:01 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
>      return {"message":f"book {book_id} not found"}, 404
I agree. I didn't look closely enough at the live branch to notice that was fixed!

2024-04-24 22:03 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
> +<!-- prettier-ignore-end -->
Sadly, the default VS Code markdown formatter tries to pad out tables. Useful if producing markdown files that one actually intends others to consume in raw format. Not so useful for us. I had to switch my formatter specifically back to prettier and then use the ignore comments in order to still be able to auto format without getting monster tables.

2024-04-24 22:09 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
>  To handle this scenario, we should return a response with a response body indicating that the book with `book_id` is invalid and a `400` response code.
The code's meaning is covered previously in Intro to API Design > Designing Responses, so I'm not too concerned about the gap here between showing the number, and providing a reminder of the meaning, as the reader has at least a little prior context.

With that in mind, would you prefer to include the label with the number for general readability?

2024-04-24 22:13 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
> +<!-- prettier-ignore-end -->
I had considered switching to a table and using a code snippet, but that would look markedly different from the other code breakdowns we do. So instead I went with splitting things up into the shorter sections you see.

2024-04-24 22:23 UTC, kelsey-steven-ada commented on api-2-read-404s/400-and-404s.md
>  To handle this scenario, we should return a response with a response body indicating that the book with `book_id` is invalid and a `400` response code.
That sounds good on discussion of meaning. I would prefer to include the label the first time we bring them up just as a reminder.

2024-04-24 22:42 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
>      return {"message":f"book {book_id} not found"}, 404
Fixed offline en masse

2024-04-24 22:42 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
>      return {"message":f"book {book_id} not found"}, 404
Fixed offline en masse.

2024-04-24 22:52 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
>  To handle this scenario, we should return a response with a response body indicating that the book with `book_id` is invalid and a `400` response code.
Included the description when shown early on in the Goals, as well as the first time each appears in situ

2024-04-24 23:44 UTC, kelsey-steven-ada approved these changes
I'm okay if this merges as-is, but I left a few suggestions for discussion.

2024-04-24 23:44 UTC, kelsey-steven-ada commented on api-2-read-404s/400-and-404s.md
> +There are a variety of ways to create `Response` instances in Flask, some implicit and some explicit. The previous resource links will provide a good starting point for exploring further!
Not required, but some slight revisions that might make this section a little more concise:

```suggestion
`Response` is a Flask class that represents HTTP responses. Ultimately, anything Flask sends back to a client gets represented as an instance of `Response`. Most of the time, we won't need to work with a `Response` directly. Flask allows us to return other values from routes, such as `dict`s and `list`s, and Flask takes care of using them to build a `Response`. But in specific cases, such as our call to `abort` above, we need an actual `Response` instance! 

One way of creating a `Response` object is to instantiate a `Response` directly using its constructor. Flask also provides the helper method `make_response`, which is a little bit more flexible in the arguments it can accept than the `Response` constructor. We'll be using `make_response` instead generating our own `Response` object, but we should be aware that Flask is still creating a `Response` instance internally. We can think of `make_response` as sort of a convenience constructor for `Response`.

There are a variety of ways to create `Response` instances in Flask, some implicit and some explicit. The resource links below will provide a good starting point for exploring further! 

- [Flask's definition of `Response`](https://flask.palletsprojects.com/en/3.0.x/api/#response-objects)
- [Flask's quickstart guide on creating responses](https://flask.palletsprojects.com/en/3.0.x/quickstart/#about-responses), which notably does _not_ feature the `Response` class
```

2024-04-24 23:44 UTC, kelsey-steven-ada commented on api-2-read-404s/400-and-404s.md
>  ## Refactor with Helper function
Reading it again, this title feels a little weird. How about something like:

```suggestion
## Refactor with a Helper Function
```
or
```suggestion
## Refactor Error Handling to a Helper Function
```

2024-04-24 23:44 UTC, kelsey-steven-ada commented on api-2-read-404s/400-and-404s.md
> +We shouldn't worry if we don't see the need for a helper function right away. It's a skill that comes with experience. As we write more code, we'll get a feeling for more patterns that can be extract
Not required, but suggesting some tweaks to remove or reword sentiments that are very close between the 1st & 3rd paragraph. Github was being weird about me selecting all the paragraphs to submit one suggestion so it's split up, sorry 😅

```suggestion
We shouldn't worry if we don't see the need for a helper function right away. As we write more code, we'll get a feeling for which patterns can be extracted into separate functions. While splitting up our logic might make a project feel more complex at first, it will make it easier to maintain and extend as the project grows.
```

2024-04-24 23:44 UTC, kelsey-steven-ada commented on api-2-read-404s/400-and-404s.md
> +The more experience we gain, the better we'll become at recognizing refactors that are likely to be helpful even before we have multiple instances of similar code. This is a skill that comes with tim
```suggestion
The more experience we gain, the better we'll become at recognizing refactors that are likely to be helpful, even before we have multiple instances of similar code. To help us develop this skill, it can be beneficial to set aside specific time to review our code and actively look for repetition that might be a hint that a refactor is needed. We'll see further refactoring examples in later lessons.
```

2024-04-25 17:38 UTC, anselrognlie commented on api-2-read-404s/400-and-404s.md
> +There are a variety of ways to create `Response` instances in Flask, some implicit and some explicit. The previous resource links will provide a good starting point for exploring further!
From your edits, I did a bit more consolidation. I tried to make it sound a little less like we'll _never_ use the constructor, since we do end up using it for the empty body responses later on.
```suggestion
`Response` is a Flask class that represents HTTP responses. Ultimately, anything Flask sends back to a client gets represented as an instance of `Response`. Most of the time, we won't need to work with a `Response` directly. Flask allows us to return other values from routes, such as `dict`s and `list`s, and Flask takes care of using them to build a `Response`. But in specific cases, such as our call to `abort` above, we need an actual `Response` instance! 

While it's possible to create a `Response` object directly using its constructor, Flask also provides the helper method `make_response`, which is a little bit more flexible than the constructor in the arguments it can accept. So here, we're using `make_response`, but we should be aware that Flask is still creating a `Response` instance internally. We can think of `make_response` as sort of a convenience constructor for `Response`.

There are a variety of ways to create `Response` instances in Flask, some implicit and some explicit. The resource links below will provide a good starting point for exploring further! 

- [Flask's definition of `Response`](https://flask.palletsprojects.com/en/3.0.x/api/#response-objects)
- [Flask's quickstart guide on creating responses](https://flask.palletsprojects.com/en/3.0.x/quickstart/#about-responses), which notably does _not_ feature the `Response` class
```

2024-04-25 17:45 UTC, merged