Building an API PT. 1 - Lesson 4: "Hello World"  Updates
Ada-Developers-Academy/core-unit-2 pull request #153
Opened 2024-04-25 01:52 UTC by mikellewade

Asana Ticket: https://app.asana.com/0/1203422600663187/1207004723163590
hello-world-branch: https://github.com/AdaGold/hello-books-api/tree/01c-hello-world

2024-04-25 19:45 UTC, kelsey-steven-ada requested changes
Looking good! I saw a couple small typos & left some questions/suggestions for discussion.

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
> +### Creating a Blueprint in `hell_world_routes.py`
```suggestion
### Creating a Blueprint in `hello_world_routes.py`
```

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
>  def create_app(test_config=None):
In the updated hello-books flow we aren't adding the `test_config` until we get to testing in Pt. 6.

```suggestion
def create_app():
```

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
>  - Give a response `200 OK` with the HTTP body `"Hello, World!"`
Reading this, it seems like it's saying the body type is HTTP rather than HTML. For clarity, we could try something like:
```suggestion
- Send an HTTP response `200 OK` with a response body `"Hello, World!"`
```
or 
```suggestion
- Send a response `200 OK` with the HTML body `"Hello, World!"`
```

2024-04-25 19:45 UTC, kelsey-steven-ada commented on assets/building-an-api/flask-hello-books_hello-json-server.png
If it isn't too much of a pain, could this be retaken with Terminal in dark mode to match the other screenshots?

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
Could we add a screenshot after line 275 that shows the error for the broken endpoint in Terminal? We show the error in a browser & Postman, I think it could be helpful for students to also know what to look for in Terminal before running into an error while working.

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
>  * title: Flask Hello World
```suggestion
* title: Hello World Routes
```

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
> +* title: Flask Hello World
We've been moving towards using the name of the lesson for the Check for Understanding titles

```suggestion
* title: Hello World Routes
```

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
> +<!-- * topics: [python, pandas] (Checkpoints only, optional the topics for analyzing points) -->
I recommend removing these commented sections in both questions since we don't use points or topics and don't have plans to in the future.

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
> +b| A decorator transforms the function that follows into an endpoint.
```suggestion
b| A decorator which transforms the function that follows into an endpoint.
```

2024-04-25 19:45 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
> +c| The function will execute whenever a request that matches the decorator is received.
This isn't quite the definition of a Blueprint, but it feels like a little bit of a gotcha since this is what the Blueprint sets our app up to do. Could this option be replaced with something a little further from Blueprint's expected behavior?

2024-04-25 19:55 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
Could we add an info callout under the text and browser screenshot for the broken endpoint (around line 273) to the effect of:

> "If you test in the browser and see a generic error instead of a stack trace, ensure that the Flask app is running in debug mode with `flask run --debug` and try again."

2024-04-25 21:24 UTC, kelsey-steven-ada commented on api-1-setup-read/hello-world-routes.md
> +c| The function will execute whenever a request that matches the decorator is received.
That sounds great =]

2024-04-25 21:44 UTC, mikellewade commented on api-1-setup-read/hello-world-routes.md
Will do! I will add it after the postman since they will see the difference there first given the order.

2024-04-25 21:45 UTC, mikellewade commented on api-1-setup-read/hello-world-routes.md
> +<!-- * topics: [python, pandas] (Checkpoints only, optional the topics for analyzing points) -->
Okay awesome!

2024-04-25 23:35 UTC, mikellewade commented on assets/building-an-api/flask-hello-books_hello-json-server.png
can definitely do that!

2024-04-25 23:35 UTC, mikellewade commented on api-1-setup-read/hello-world-routes.md
🫡

2024-04-26 16:04 UTC, kelsey-steven-ada approved these changes
🙌🏻

2024-04-26 18:29 UTC, merged