Building an API pt. 6 - lesson 7: POST /books Test
Ada-Developers-Academy/core-unit-2 pull request #165
Opened 2024-06-14 13:46 UTC by kelsey-steven-ada

[Pt. 6 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678572/f)
[Pt. 6 Lesson 7 ticket](https://app.asana.com/0/1205655776549324/1207017851991904/f)

2024-06-14 15:21 UTC, anselrognlie requested changes
A few suggestions. Thanks for already including the image caption and link! 🙂

2024-06-14 15:21 UTC, anselrognlie commented on api-6-testing/post-books-test.md
Super minor, but for the table row with the test declaration (around line 40), the wrapping lands so that the final `):` ends up on its own line looking very sad. Could we add a zdero width space after the open paren so that the wrap can happen there instead?

Also code quotes pytest

```md
|`def test_create_one_book(`&ZeroWidthSpace;`client):` | Continuing our best `pytest` practices, this test should start with the name `test_`, and it should describe the nature of this test.|
```

2024-06-14 15:21 UTC, anselrognlie commented on api-6-testing/post-books-test.md
>  |`client.post("/books", json=...`|Sends an `POST` request to `/books` with the JSON request body passed in as the `json` keyword argument|
Rewords to emphasize the distinction between the actual dict and the JSON it will become
```suggestion
|`client.post("/books", json=...`|Sends a `POST` request to `/books`, with the `dict` to be used as the JSON request body passed in using the `json` keyword argument| 
```

2024-06-14 15:21 UTC, anselrognlie commented on api-6-testing/post-books-test.md
>  | `response_body = response.get_json()`| Get the JSON response body with `response.get_json()`|
Rewords to emphasize the distinction between the JSON the response contained and the value we get in python
```suggestion
| `response_body = response.get_json()`| Gets the JSON response body as a Python value. Since the create logic returns a `dict`, we should anticipate `response_body` to receive a `dict` result here.|
```

2024-06-14 15:21 UTC, anselrognlie commented on api-6-testing/post-books-test.md
>  |`assert response.status_code == 201`|Check for the expected status code|
follows tense established in "sends a post" (combining with the next suggestion gave a very strange git diff)
```suggestion
|`assert response.status_code == 201`|Checks for the expected status code|
```

2024-06-14 15:21 UTC, anselrognlie commented on api-6-testing/post-books-test.md
> +|`assert response_body == {...}}`| Check for the expected key/value pairs in the response body|
follows tense established in "sends a post"
```suggestion
|`assert response_body == {...}}`| Checks for the expected key/value pairs in the response body|
```

2024-06-14 15:21 UTC, anselrognlie commented on api-6-testing/post-books-test.md
> +_Fig. Test output reporting 3 tests in `tests/test_book_routes.py` passed. ([Full size image](../assets/api-6-testing/api-6-testing_post_test_success.png))_
Thank you!

2024-06-14 15:21 UTC, anselrognlie commented on api-6-testing/post-books-test.md
> +3. True: We only need a fixture which creates a `Book` record before the test runs if the test depends on there being data in the database.
uses "that" for a restrictive clause
```suggestion
3. True: We only need a fixture that creates a `Book` record before the test runs if the test depends on there being data in the database.
```

2024-06-17 18:37 UTC, kelsey-steven-ada commented on api-6-testing/post-books-test.md
> +d| The `client` fixture needs to used for every test using the `pytest` framework.
```suggestion
d| The `client` fixture needs to be used for every test using the `pytest` framework.
```

2024-06-17 19:30 UTC, anselrognlie commented on api-6-testing/post-books-test.md
>  - Use fixtures to create test data
I was thinking to completely remove this one about fixtures, since this lesson doesn't use fixtures to create any test data this time. If we still want multiple goals, maybe this could be

```suggestion
- Use fixtures to access the test client to send a POST request
```

But that seems wordy to me.

2024-06-17 21:40 UTC, kelsey-steven-ada commented on api-6-testing/post-books-test.md
>  - Use fixtures to create test data
Ahh, I get what you're saying, I think it's fine to only have one goal and remove the fixture related one since we aren't writing new ones or doing anything new with them.

2024-06-17 22:23 UTC, merged