Building an API pt. 8 - lesson 1: One-to-Many
Ada-Developers-Academy/core-unit-2 pull request #170
Opened 2024-08-13 19:43 UTC by kelsey-steven-ada

[Pt. 8 Asana ticket](https://app.asana.com/0/1205655776549324/1206697443678574/f)
[Pt. 8 Lesson 1 ticket](https://app.asana.com/0/1205655776549324/1207017851991911/f)

2024-08-14 17:37 UTC, anselrognlie requested changes
A few small edits, and some potential areas to provide additional background.

2024-08-14 17:37 UTC, anselrognlie commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +```py
Thanks for including these!

2024-08-14 17:37 UTC, anselrognlie commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +    author: Mapped[Optional["Author"]] = relationship(back_populates="books")
Would there be any value in dwelling on _why_ we made the author data optional? Like I'm cncerned students will assume that relationships should _always_ be optional rather than considering whether that makes sense for their data model.

Like here, it's primarily because we're too lazy to deal with existing Book data that has no author, and we could conceptualize NULL author data as representing a book with an unknown author (alternatively this could be represented with an "Unknown" author record). Probably don't want to open the can of worms that is books with multiple authors, as that would transform the relationship to a many-to-many, but I still feel like giving a sense of what's _required_ for a relationship as opposed to what's specific to this relationship could help.

2024-08-14 17:37 UTC, anselrognlie commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +##### !end-hint
How about a second hint to help establish that the stuff realted to `relationship` aren't required?
```suggestion
##### !hint

What is the difference between `author` and `author_id` in the `Book` class?
What is the difference between a `ForeignKey` and a `relationship` in SQLAlchemy?

##### !end-hint

##### !hint

SqlAlchemy `relationship` entries provide convenient access to related objects, but aren't themselves required to establish the actual model relationship.

##### !end-hint
```

2024-08-21 22:15 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +    author: Mapped[Optional["Author"]] = relationship(back_populates="books")
I think it's worth at least a brief mention, as you mentioned, it could be helpful to be clear that we don't always prefer optional relationships.

2024-08-21 22:18 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
>  Let's visualize the relationship between `book`s and `author`s. Just like we did when we built relationships in SQL, we will use an **entity relationship diagram** to visualize the relationship betwe
Thanks for catching the properties mismatch, I can get that updated. Do you know if we've been using Figma or a different tool to create ERDs for Learn?

2024-08-21 22:36 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
>  Let's visualize the relationship between `book`s and `author`s. Just like we did when we built relationships in SQL, we will use an **entity relationship diagram** to visualize the relationship betwe
Ah, looks like we were using draw.io/diagrams.net. I've made a folder in drive for us to collect curriculum assets like this that don't already live in Figma.

2024-08-21 23:19 UTC, anselrognlie commented on api-8-relationships-in-sqlalchemy/one-to-many.md
>  Let's visualize the relationship between `book`s and `author`s. Just like we did when we built relationships in SQL, we will use an **entity relationship diagram** to visualize the relationship betwe
Back in the day, we had a best practice of using tools that could export a native version of the eventual png and including them in the Learn material to make it easier to edit assets in the event of changes (such as .fig files from figma and .xcf files from GIMP) but unfortunately that fell by the wayside.

Thanks for making sure this lives in a shared drive, as a lot of times, the web-based assets ended up in someone's personal drive, now inaccessible to us.

2024-08-21 23:26 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +        query = query.where(Author.name.ilike(f"%{name_param}%"))
Adding comment to line 99 above right after stating they can check out lesson 3 for basic set up.

2024-08-21 23:26 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
>  Let's visualize the relationship between `book`s and `author`s. Just like we did when we built relationships in SQL, we will use an **entity relationship diagram** to visualize the relationship betwe
The table names in the original image (`books` and `authors`) don't match the tables that are created locally since our classes are `book` and `author`. How do you feel about me updating the names in the ERDs to match what students would see generated?

2024-08-21 23:26 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +    author: Mapped[Optional["Author"]] = relationship(back_populates="books")
Added a callout box around line 199, let me know what you think =]

2024-08-22 04:36 UTC, anselrognlie requested changes
Looks good. I just had a follow up thought around the `Optional[]` model declaration.

2024-08-22 04:36 UTC, anselrognlie commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +
```suggestion

<br>

```

2024-08-22 04:36 UTC, anselrognlie commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +If we wanted an `Author` relationship to be required for the `Book` model, we could take a different tactic, such as representing an unknown author by using an "Unknown" author record.
I think I'd feel more comfortable with an explicit connection made to the `Optional[]` chunk of the syntax. Something along these lines.
```suggestion
If we wanted an `Author` relationship to be required for the `Book` model, we could take a different tactic, such as representing an unknown author by using an "Unknown" author record. In that case, the `Optional[]` portion would be omitted from the mapping declaration. For example, while `Mapped[Optional[int]]` declares a nullable integer column, `Mapped[int]` declares an integer column that disallows `NULL` values, just as Mapped[str] declares a required string column.
```
But I know this would feel weird here, before seein the code. So what about moving the contents of this callout to just after the Book code in the details section?

2024-08-22 16:28 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +If we wanted an `Author` relationship to be required for the `Book` model, we could take a different tactic, such as representing an unknown author by using an "Unknown" author record.
Agreed, with the syntax it'll make more sense after they've seen the updated code 👍

2024-08-22 19:41 UTC, kelsey-steven-ada commented on api-8-relationships-in-sqlalchemy/one-to-many.md
>  <!-- prettier-ignore-start -->
```suggestion

## Check for Understanding

<!-- prettier-ignore-start -->
```

2024-08-27 15:52 UTC, anselrognlie approved these changes
Just the last br, then LGTM!

2024-08-27 15:52 UTC, anselrognlie commented on api-8-relationships-in-sqlalchemy/one-to-many.md
> +
no longer necessary after moving inside details
```suggestion
```

2024-08-27 17:24 UTC, merged