Flask Updates: Building an API pt. 9, lesson 2: Deploying to Render
Ada-Developers-Academy/core-unit-2 pull request #174
Opened 2024-09-13 20:49 UTC by kelsey-steven-ada

[Pt. 9 Asana ticket](https://app.asana.com/0/1205655776549324/1206934546187432/f)
[Pt. 9 Lesson 2 ticket](https://app.asana.com/0/1205655776549324/1207017851991917/f)

There is no lesson 1 ticket since that only covers general information about what deployment is; the video there looks at the lesson, but does not show outdated code.

2024-09-16 04:26 UTC, anselrognlie requested changes
A couple formatting things, a few content thoughts, and some potential future work. Let me know what you think!

2024-09-16 04:26 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
> +`SQLALCHEMY_DATABASE_URI`) as command line arguments, for example :
I'm worried that calling these command line arguments could be confusing. Could we expand this a bit to explain how environment vairables can be set for the duration of a single command by listing them as name value pairs before the actual command to run?

Would it be worth reminding students that any of the values we've been setting in the `.env` are really being loaded by the `dotenv` library to look as though they are environment variables, but that this doesn't happen when `gunicorn` is hosting our flask app, hence the need to set them ourselves.

There's material along these lines later, but here, it feels like the `SQLALCHEMY_DATABASE_URI` stuff is a little out of the blue. Since it _is_ covered later, maybe than going into all the gory details here, we could remind the reader that this is setting an environment variable and for more details to refer to the "Setup and Initialize the Render Database" topic later on? Or we could move this callout to closer to the configuration section. Or even introduce a new section about trying this out locally as a way to help troubleshoot whether the commands and values we've supplied in the Render configuration are working by running our app under `gunicorn` locally?

2024-09-16 04:26 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
Totally beyond the scope of this change, but I find it a bit cumbersome that once we introduce the render connection string (and which we need in order to setup up our db tables in the render db, we need to modify our code to go back and forth between the deployed database and the dev database.

What would think about opening a ticket to revisit this approach to make it so that it becomes only a configuration (.env) change? One of the things we stress with deployment in other contexts is that application code should not need to change when moving between development and deployment, but our own example violates this.

2024-09-16 04:26 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
> +`SQLALCHEMY_DATABASE_URI` is a [SQLAlchemy Configuration Key](https://flask-sqlalchemy.palletsprojects.com/en/3.1.x/config/) which allows us to customize certain settings in our app.
I was going to suggest using the "latest" version of the doc link (https://flask-sqlalchemy.readthedocs.io/en/latest/config/), but I guess since the version of sqlalchemy we use is fixed to a particular point in time, this could be confusing if folks go read the docs, and try to use features that exist in newer versions, but aren't in the curriculum version. So I guess the specific version of the docs is better?

2024-09-16 04:26 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
lines 352, 354 give a command to display the book and author tables, but give the command as `d book` and `d author` rather than `\d book` and `\d author`.

2024-09-16 22:34 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
> +`SQLALCHEMY_DATABASE_URI`) as command line arguments, for example :
Since we already have a troubleshooting section, I moved the expanded content down to a subheading under "General Render Debugging Strategies", let me know what you think of the changes/if it fits well there.

2024-09-16 22:34 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
I prefer that over how we have it now where we make changes in both the `.env` & `__init__.py` files, I'm good with that being added to the backlog.

2024-09-16 22:34 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
> +`SQLALCHEMY_DATABASE_URI` is a [SQLAlchemy Configuration Key](https://flask-sqlalchemy.palletsprojects.com/en/3.1.x/config/) which allows us to customize certain settings in our app.
I had a similar thought, it would be nice to have less places we need to make sure we update, but I prefer to err on the side of less potential confusion and frustration for students.

2024-09-17 06:15 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
> +`SQLALCHEMY_DATABASE_URI`) as command line arguments, for example :
Yes, I really like the treatment you gave that down in the troubleshooting and love the detailed explanation of what the command actually does. ❤️

2024-09-17 06:16 UTC, anselrognlie approved these changes
LGTM!

2024-09-17 17:47 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
Ticket for that update: https://app.asana.com/0/1201700438643002/1208335052936079

2024-09-17 17:48 UTC, merged