Update screenshots and information for BaA pt. 9 - Deployment
Ada-Developers-Academy/core-unit-2 pull request #179
Opened 2024-10-03 22:37 UTC by kelsey-steven-ada

Asana tickets:
- [Add screenshots & instructions to select runtime](https://app.asana.com/0/1205655776549324/1208335052936095/f)
- [Update instructions for deployment to only change .env file](https://app.asana.com/0/1205655776549324/1208335052936079/f)

Changes:
- Replaces all screenshots except for the verification email to reflect changes to the platform (Some fields in various parts of the flow have been renamed or moved.)
- Instead of having folks edit both the `.env` and `__init__` files, updates instructions to comment out the local db string and add the same key with connection to the remote database.

2024-10-17 22:06 UTC, anselrognlie requested changes
Thank you so much for updating all those images! I have a few suggestions, but overall this looks good. I followed along myself and only had a minor hang up or two.

2024-10-17 22:06 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
Line 526:

The "Check the local server logs" often trips folks up, but if we make it clear that we're talking about the deployed instance, maybe that would help?
>Check all of the options that are recommended debugging steps when troubleshooting our deployed application.

2024-10-17 23:32 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
> +We also want to change the "Branch" field to choose which branch we want to pull our code from to create our deployed application. Most of the time we will select `main`, but in the case of the Hello
How do you feel about rewording it to:
```suggestion
We also want to change the "Branch" field to choose which branch we want to pull our code from to create our deployed application. Most of the time we will select `main`, and this should be the option students are using to deploy their repos. The example Hello Books API repo doesn't have a `main` branch, we have named branches per-lesson. In this example deployment, we will choose a branch that includes all the code and latest changes we want to be a part of our deployed app. For the purposes of our example, we will choose `08b-nested-routes` or any later branch. 
```

Around the branches, since we talk them through checking for and installing `gunicorn` I thought it would be okay listing `08b-nested-routes` as the starting branch, do you have concerns about keeping that branch instead of using `09a-deploying-to-render` here?

2024-10-17 23:32 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
> +In the "Instance Type" section, Render will have a paid option selected by default. We want to ensure that the "Free" tier is selected before proceeding.
Right? I was sad to see the change =/

2024-10-17 23:32 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
>  ### !callout-warning
Yeah, are you thinking to add a new info callout or to include that info along with the free app limits?

2024-10-17 23:32 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
> +![Screenshot of hello-books-api database being created](../assets/deployment/render-database-info-creating-db.png)
I think this is a new change, because I don't remember it coming up previously 😢

2024-10-17 23:32 UTC, kelsey-steven-ada commented on api-9-deployment/deploying-to-render.md
> +We can find our URL on our deployed application's dashboard, listed just under the name of our web service application. Render URLs will take the form `https://your-app-name.onrender.com` Our demonst
I know we used to have `hello-books-api.onrender.com` but it isn't on the cs-fun render account. I can't remember the exact situation but I couldn't use it when deploying and taking screenshots. 

I'll add a note that they should expect to see an error if they try navigating to the page since we do not keep the app running outside of demos.

2024-10-18 03:49 UTC, anselrognlie requested changes
Updated the discussion threads, including some possible verbiage.

2024-10-18 03:49 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
> +We also want to change the "Branch" field to choose which branch we want to pull our code from to create our deployed application. Most of the time we will select `main`, but in the case of the Hello
We do have the gunicorn information, but for me, the key difference is that we would need to have commited that to this branch for it to work. So it feels like we should pick a branch which actually has the gunicorn requirement included.

How about this? Rephrased a little bit for less distance between the author's voice and the reader. And the updated branch.
```suggestion
We also want to change the "Branch" field to choose which branch we want to pull our code from to create our deployed application. Most of the time we will select `main`, and this should be the branch we pick for our individual repos. The example Hello Books API repo doesn't have a `main` branch, we have named branches per-lesson. In this example deployment, we will choose a branch that includes all the code and latest changes we want to be a part of our deployed app. For the purposes of our example, we'll use `09a-deploying-to-render`. 
```

2024-10-18 03:49 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
>  ### !callout-warning
I had been thinking a different callout, but because of the free app limits, I was leaning towards having the text in the main flow between the screenshot and the callout. Something along the lines of
>If a prompt for payment information appears after clicking the Deploy Web Service button, we can dismiss the popup and then double check that the Instance Type selection is set to Free. By default, one of the paid tiers is selected, and we'll be prompted for payment information unless we change the setting.

It's a little repetitive with the initial instructions, but my thinking is that if they didn't change the setting, they probably missed reading that paragraph, so it doesn't hurt to list it again.

2024-10-18 03:49 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
> +![Screenshot of hello-books-api database being created](../assets/deployment/render-database-info-creating-db.png)
Would it be worth calling out that it has this restriction? I'm thinking from the standpoint of making sure folks aren't caught off-guard when everything breaks, and also being aware for when it comes to capstone time. Something like

>The free database tier is time limited, and Render will remove your database, along with any data, after a set period of time unless the plan is upgraded to a paid tier. This is fine for our purposes now when we're gaining deployment experience, but we should keep this mind if we want to deploy any projects that we would like to have run for a longer time. We can always create a new database when the original is removed, but we would need to plan ahead in order to migrate any data from the original database that we would like to preseve.

2024-10-18 14:10 UTC, anselrognlie reviewed
LGTM. Just one thing about where the new paragraph about the payment popup might go. But I'm fine either way.

2024-10-18 14:10 UTC, anselrognlie commented on api-9-deployment/deploying-to-render.md
> +If a prompt for payment information appears after clicking the Deploy Web Service button, we can dismiss the popup and then double check that the `Instance Type` selection is set to `Free`. By defaul
What if this were between the screenshot and the callout? If I click the button (looking at the screen shot to confirm that I'm clicking the right one) and then something unexpected happens, I'd be hoping to see that right with the image. With the callout in between, I feel like I'm going to see that, see that _isn't_ about what I'm encountering, and then I'm going to start looking elsewhere.

2024-10-18 14:11 UTC, anselrognlie approved these changes
Sorry, meant to approve.

2024-10-18 14:21 UTC, merged