deployment: adds content
Ada-Developers-Academy/core-unit-2 pull request #28
Opened 2021-04-20 03:24 UTC by tildeee

2021-04-25 22:17 UTC, anselrognlie reviewed
comments for deployment

2021-04-25 22:17 UTC, anselrognlie commented on deployment/deployment.md
> +How do we make our web apps run online reliably?
I think this sounds a bit more exciting
```suggestion
How do we make our web apps available to the rest of the world?
```

2021-04-25 22:17 UTC, anselrognlie commented on deployment/deployment.md
> +If we _deploy_ our apps, we will set up machines and web servers dedicated to running our web app. Then, users can access our apps without relying on our own personal machines!
"when", not "if"
"relying" sounds odd to me here. This part is less important.
```suggestion
When we _deploy_ our apps, we will set up machines and web servers dedicated to running our web app. Then, users can access our apps regardless of what our own personal machines are doing!
```

2021-04-25 22:17 UTC, anselrognlie commented on deployment/deployment.md
> +In this curriculum, we will choose specific deployment tools and services that answer these questions for us, so that we may focus on web development skills.
we are expressing an ability, not a need for permission
I'd really like to say "focus on developing our web development skills" but that's too redundant-sounding to me (even though it has a slightly different connotation to me than "improving")
```suggestion
In this curriculum, we will choose specific deployment tools and services that answer these questions for us, so that we can focus on improving our web development skills.
```

2021-04-25 22:17 UTC, anselrognlie commented on deployment/deployment.md
> +The following are all examlpes of _Platforms as a Service_. The responsibility of these services is to create, manage, and maintain environments that run our deployed apps.
```suggestion
The following are all examples of _Platforms as a Service_. The responsibility of these services is to create, manage, and maintain environments that run our deployed apps.
```

2021-04-25 22:17 UTC, anselrognlie commented on deployment/deployment.md
> +Beyond the "development environment" and the "test environment," we can introduce a third "production environment." This production environment refers to the environment that runs our deployed, relea
can we echo back to the dancing analogy?
```suggestion
The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual users!
```

2021-04-26 07:47 UTC, anselrognlie reviewed
comments for deploying-to-heroku

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +[Heroku](https://www.heroku.com/home) is one Platform as a Service (PaaS). We can use Heroku services to deploy our Flask API. After we successfully deploy, our API will be available to all web clien
a little more exciting?
```suggestion
[Heroku](https://www.heroku.com/home) is one Platform as a Service (PaaS). We can use Heroku services to deploy our Flask API. After we successfully deploy, our API will be available to the whole Internet!
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +After logging into the dashboard, we should see an empty list of Heroku apps. (This screenshot features one Heroku app).
a bit more of an explanation about why the screenshot isn't showing an empty list
```suggestion
After logging into the dashboard, as a new user we should see an empty list of Heroku apps. (This screenshot is from an account which had already created one Heroku app).
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
provide an explanation of what this command does
```suggestion

This command runs two separate commands. The `&&` joins them into one convenient copy/paste-able unit.

The first command `brew tap heroku/brew` tells Homebrew to add an additional source of software packages (termed a _tap_ in Homebrew-speak). The second command `brew install heroku` uses Homebrew to install the Heroku CLI, which it will be able to find with the tap we just configured.

```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +We'll be prompted to enter any key to go to the web browser to complete login. The CLI will then log us in automatically.
```suggestion
We'll be prompted to press any key to go to a web browser to complete our login. The CLI will then log us in automatically.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +We will need to depend on a Python package named [gunicorn](https://pypi.org/project/gunicorn/).
need to depend on sounds awkward. we are taking gunicorn as a dependency, yes, but let's just say that we're going to use it (and very briefly what for)
```suggestion
We will use a Python package named [gunicorn](https://pypi.org/project/gunicorn/) to launch our Flask API on Heroku.

`gunicorn` is capable of running Flask apps so that they can handle multiple simultaneous requests, which is very important for production web applications.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Confirm that the package `gunicorn` is in the project's `requirements.txt` file.
we do instead of an order
```suggestion
We should confirm that the package `gunicorn` is in the project's `requirements.txt` file.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
Provide guidance on what top do if it's missing (it shouldn't be, and we've done this once before for a different package, but it doesn't hurt to review the steps again)
no suggestion because code
following comment contains markdown

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
If `gunicorn` does _not_ appear in our `requirement.txt`, we can add it by installing it locally with:

```bash
(venv) $ pip install gunicorn
```

After it has installed, we can update our `requirements.txt` by running:

```bash
(venv) $ pip freeze > requirements.txt
```

Heroku makes use of our `requirements.txt` file to install our app dependencies, so it is very important to ensure that all of our dependencies are properly listed.

If we needed to update our `requirements.txt`, we should be sure to add and commit this change.

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +We define web server processes Heroku needs to run inside the Procfile. We'll use our Procfile to define how to start a Flask web server.
I doubt the reader will understand what it means to define a web server process. just say why we're using it: we need it to define how to start the server
```suggestion
We'll use our Procfile to define how to start our Flask web server.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Save this file. Then, create a git commit that contains this change.
```suggestion
Save this file. Then, create a Git commit that contains this change.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +After `cd`ing to our project root, we can create a Heroku app using the Heroku CLI. In the command line using **either** of these options:
```suggestion
After `cd`ing to our project root, we can create a Heroku app using the Heroku CLI. From the command line we should pick **either** of these options:
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Replace `your-app-name` with the name of the app.
```suggestion
Replace `your-app-name` with the desired name of the app.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
include a warning about unique names
```suggestion

Note that the app name must be unique across all Heroku apps, not just our own apps. As a result, the name `hello-books-api` is already taken, as it was used in this walk-through!

We will need to come up with our own name that has a unique touch, or we can simply use the nameless option to generate a unique name automatically.

```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +This command will push our project's git history to a remote named `heroku`. It will push the default `main` branch to Heroku.
```suggestion
We should send our project codebase to our `heroku` remote.

This command will push our project's Git history to a remote named `heroku`. It will push the default `main` branch to Heroku.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Every time we want to push our git history to our Heroku app, we will need to push to the `heroku` remote.
```suggestion
Every time we want to push our Git history to our Heroku app, we will need to push to the `heroku` remote.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
add a notice about how .gitignore will affect our .env
```suggestion

### !callout-info

## Pushing to Heroku Still Ignores Files

Since we are using Git to send our code to Heroku, this means any files listed in our `.gitignore` will _not_ be sent, including our `.env` file. This means our environment variables, which include our connection strings, will not be sent to Heroku! We'll see how to tell our app where to find our database later in this lesson.

### !end-callout

```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +This command uses the Heroku CLI to add a postgres database to the app.
```suggestion
Now that we've created our Heroku app for the first time, we need to tell the app that we're interested in adding a Postgres database to our deployed Heroku app.

This command uses the Heroku CLI to add a Postgres database to the app.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Use the Heroku dashboard to view your Heroku app. In the "Overview" tab, in the "Installed add-ons" section, we should see "Heroku Postgres."
revoice for we
```suggestion
We can use the Heroku dashboard to view our Heroku app. In the "Overview" tab, in the "Installed add-ons" section, we should see "Heroku Postgres."
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Our current app probably has `SQLALCHEMY_DATABASE_URI` set as an environment variable in `.env`. The Flask code probably uses this variable with `os.environ.get("SQLALCHEMY_DATABASE_URI")`.
we don't need the "probablies" since the reader has been following the previous lessons
added some extra text to make the wrap look a little nicer (due to the long code snippet)
```suggestion
Our current app sets the `SQLALCHEMY_DATABASE_URI` environment variable using our `.env` file. Our Flask code accesses this environment variable with the code `os.environ.get("SQLALCHEMY_DATABASE_URI")`.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Then:
```suggestion
Once we locate this section, we should:
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Now, let's set `SQLALCHEMY_DATABASE_URI`.
```suggestion
Now, let's set the `SQLALCHEMY_DATABASE_URI` variable.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +```
remove all of this and use db upgrade instead
no suggestion because code
new markdown in following comment
```suggestion
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +```
Now that our Flask app is on Heroku and can connect to a database, we need to initialize the database in Heroku once.

We can run the following:

```bash
$ heroku run flask db upgrade
```

This will migrate the empty database in our remote Postgres connection to the latest schema configuration we have generated from our models.

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Our Flask project is on a Heroku machine, running, and connected to an initialized database. Now is the time to verify if our API is accessible by web!
```suggestion
Our Flask project is on a Heroku machine, running, and connected to an initialized database. Now is the time to verify whether our API is accessible by web!
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
add a notice about potential routing issues
```suggestion

### !callout-warning

## Routing Configurations May Result in a `404 Not Found`

Recall that Flask routes are very picky about `/` characters. Some browsers will try to put a `/` character at the end of an address automatically. Depending on how our routes are set up, this might result in a route mismatch.

<br />

Our Flask API isn't _intended_ to be used through a web browser. It's meant to be used programmatically. It's convenient if testing through a browser works, but if it doesn't we can move on to try testing with Postman. Alternatively, we could return to the [Create and Read](../building-an-api/create-and-read.md) lesson of Building an API for tips on how to loosen our route matching.

### !end-callout

```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Instead of `localhost:5000/books`, we could visit `https://your-app-name.herokuapp.com/books`, where `your-app-name` is the name of your Heroku app.
we could, but we won't? could has a muddier meaning than can here
your → our
```suggestion
Instead of `localhost:5000/books`, we can visit `https://your-app-name.herokuapp.com/books`, where `your-app-name` is the name of our Heroku app.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Our apps have zero books listed when we go to `/books`, even though our app is deployed correctly and connected to our Postgres database correctly.
we talking about one app
```suggestion
Our app has zero books listed when we go to `/books`, even though our app is deployed correctly and connected to our Postgres database correctly.

<br />

```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
```suggestion

<br />

```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +Recall that our deployed app is connected to a Postgres database that we created a few steps ago! We have not added any book data to our Heroku database. Even if our local database is full of books,
```suggestion
Recall that our deployed app is connected to a Postgres database that we created a few steps ago! We have not added any book data to our Heroku database. Even if our local database is full of books, our Heroku app's database connection string points at the Heroku database. 
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +We can access the server logs of our Heroku app from the Heroku dashboard by finding the "More" menu and finding "View logs."
we are recollecting what we could do, so stick with past
```suggestion
During local development on our own machines, when we ran `$ flask run`, the server's logs were output into our terminal. We could see the details about every HTTP request our server received and every HTTP response it returned. We could also see output for any errors.

We can access the server logs of our Heroku app from the Heroku dashboard by finding the "More" menu and selecting "View logs."
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +This option is useful when we want to recreate an error and see what server logs are most relevant.
clarify why we're recreating an error
```suggestion
This option is useful when we are troubleshooting an issue. If we can recreate the error, we'll be able to see the server log information related to the error just as if we were running the application locally.
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +* Initialized the database by using `$ heroku run python3`
```suggestion
* Initialized the database by using `$ heroku run flask db upgrade`
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +* Initialized the database by using `$ heroku run python3`
```suggestion
* Initialized the database by using `$ heroku run flask db upgrade`
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +We could summarize our local development workflow like this:
```suggestion
When we practice _continuous deployment_, we must adopt the practice of regularly updating the Git history of our Heroku app.

We can summarize our local development workflow like this:
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +1. Verify our deployment
```suggestion
1. Activate our virtual environment
1. Pull down any new commits from Git
1. Run tests
1. Write code
1. Make Git commits
1. Push our Git history to the `origin` remote, which is our repo on GitHub
1. **Push our Git history to the `heroku` remote**, which is our Heroku app
1. Verify our deployment
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +| Command              | Explanation                                                                                                                                                         |
improve formatting
```suggestion
| <div style="min-width:200px;">Command</div>              | Explanation                                                                                                                                                         |
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +| `heroku logs --tail` | Turns the current terminal window into tailing the Heroku logs, and get real-time updates                                                                           |
"turns the window into" sounds like a roundabout way of saying "starts" 😂 
```suggestion
| `heroku logs --tail` | Starts tailing the Heroku logs in the current terminal window, displaying real-time updates                                                                           |
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +| `heroku pg:psql`     | Runs the `psql` shell on the Heroku machine running our app. We can use this to execute `psql` commands, and check, add, update, delete the data that our app uses. |
```suggestion
| `heroku pg:psql`     | Runs the `psql` CLI on the Heroku machine running our app. We can use this to execute `psql` commands, and check, add, update, or delete the data that our app uses. |
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +| Debugging Action                          | Details
improve formatting
```suggestion
| <div style="min-width:200px;">Debugging Action</div>                          | Details                                                                                                                                                                                                                                            |
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +| Check the status of the git history       | Confirm that the remote git history is up-to-date. Check that working code has been recently pushed to the `heroku` remote.
```suggestion
| Check the status of the Git history       | Confirm that the remote Git history is up-to-date. Check that working code has been recently pushed to the `heroku` remote.                                                                                                                        |
```

2021-04-26 07:47 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +| Rubber-duck, and post questions on Slack! | Debugging deployment usually depends on context. Rubber-duck and connect with folks who are deploying similar projects to you!
```suggestion
| Rubber duck, and post questions on Slack! | Debugging deployment usually depends on context. Rubber duck and connect with folks who are deploying similar projects to you!                                                                                                                     |
```

2021-04-26 19:17 UTC, anselrognlie requested changes
comments for the problem set and activity.

2021-04-26 19:17 UTC, anselrognlie commented on deployment/problem-set-deployment.md
> +  - To the best of your ability, you should check that no syntax errors, name errors, or other runtime errors can occur
staving off possibilities seems like a tall order. I'd drop can
```suggestion
  - To the best of your ability, you should check that no syntax errors, name errors, or other runtime errors occur
```

2021-04-26 19:17 UTC, anselrognlie commented on deployment/problem-set-deployment.md
> +Prepare your Solar System API project for deployment. Similarly, your Solar System API project should be working and up-to-date on GitHub.
expand to encompass the same setup
```suggestion
Prepare your Solar System API project for deployment.

- Perform the same checks as for your Hello Books API project
- Ensure that the latest version is committed and pushed to GitHub
```

2021-04-26 19:17 UTC, anselrognlie commented on deployment/activity-deploying-to-heroku.md
> +The Hello Books API should be in a working state, such that running `$ flask run` does not produce any errors. To the best of your ability, you should check that no syntax errors, name errors, or oth
same removal of can
```suggestion
The Hello Books API should be in a working state, such that running `$ flask run` does not produce any errors. To the best of your ability, you should check that no syntax errors, name errors, or other runtime errors occur.
```

2021-04-26 19:17 UTC, anselrognlie commented on deployment/activity-deploying-to-heroku.md
> +1. While using individual Hello Books API repos, as a pair/group, follow the "Deploying to Heroku" walkthrough step-by-step together
```suggestion
1. While using individual Hello Books API repos, as a pair/group, follow the "Deploying to Heroku" walk-through step-by-step together
```

2021-04-26 19:17 UTC, anselrognlie commented on deployment/activity-deploying-to-heroku.md
> +    - Write down how you observe the issue
tense consistency
```suggestion
    - Write down how you observed the issue
```

2021-04-26 19:17 UTC, anselrognlie commented on deployment/activity-deploying-to-heroku.md
> +If there is time, repeat this process with Solar System API.
My eyes kept skipping over this. Maybe a callout so that it is more visible?
Definitely please check the verbiage, as I encouraged students who didn't have time during the activity to still attempt the deployment on their own.

```suggestion
### !callout-info

## Repeat with Solar System API

Our skills improve with repetition. If there is time during the activity, repeat the deployment process with Solar System API. If there is _not_ time, deploy Solar System API as an individual activity.

### !end-callout
```

2021-04-28 16:24 UTC, jmaddox19 commented
@tildeee, It would be very helpful for me if Ansel's suggestions got merged in so that I can pull down this PR and preview it with learn with all those changes, to be able to offer my feedback and prep for recording the video.

2021-04-29 18:34 UTC, tildeee commented on deployment/deploying-to-heroku.md
> +
Nitpicking: Could we put this into one paragraph?

```suggestion

Note that the app name must be unique across all Heroku apps, not just our own apps. As a result, the name `hello-books-api` is already taken, as it was used in this walk-through! We will need to come up with our own name that has a unique touch, or we can simply use the nameless option to generate a unique name automatically.

```

2021-04-29 18:47 UTC, jmaddox19 reviewed
Small feedback on deployment lesson

2021-04-29 18:47 UTC, jmaddox19 commented on deployment/deployment.md
> +The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual use
This looks like a person's name, but I'm confused by the reference to a person here when I don't see their name anywhere else.

2021-04-29 18:47 UTC, jmaddox19 commented on deployment/deployment.md
> +1. Deploy to the production environment
I'm thinking naming the implied context of an existing application would be useful here. Once I added that context, the word "new" felt a little awkward to me, but maybe that's just me.
```suggestion
Let's say we have an existing web application that is already deployed and already being used by people all over the world. Assuming we want to deploy early and often, our development workflow may look like this:

1. Begin a new feature
1. Do work in our local environment, using best practices for git and testing
1. Finish the new feature
1. Deploy the updated code with this new feature to the production environment
```

2021-04-29 18:49 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
Sure, if you like. I was thinking that the directive to come up with a unique name got a little buried in the middle of the paragraph, so I split it hopefully to get the reader's attention.

2021-04-29 18:52 UTC, anselrognlie commented on deployment/deployment.md
> +The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual use
Aleesha's story is introduced in the flask testing lesson to frame the discussion about environments. She's a dancer who dances at home, at a practice hall, and in performances on the main stage. 🙂

2021-04-29 18:53 UTC, anselrognlie commented on deployment/deployment.md
> +1. Deploy to the production environment
I like this change too. 👍

2021-04-29 18:58 UTC, jmaddox19 commented on deployment/deployment.md
> +The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual use
Oh, got it! This seems to break the guidance I've heard about not requiring an ordering to Learn topics, but if that guidance has been dropped, totally cool with me

2021-04-29 19:41 UTC, anselrognlie commented on deployment/deployment.md
> +The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual use
Hmm. That does make sense... On the other hand, it seems a shame to miss out on the opportunity to tie this directly into the metaphoric framework that was established earlier for reinforcement.

Lessons can't exist entirely in a vacuum since 1. there are concepts that build on each other (deploying to the production environment depends on the concept a production environment) and 2. it can sound super tone deaf to talk about a topic that a reader _has_ encountered already as though they haven't seen it before.

This is only a side comment, so I won't fight dropping this if desired, but at the same time, we have to allow for _some_ assumption of ordering.

2021-04-29 20:09 UTC, jmaddox19 commented on deployment/deployment.md
> +The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual use
Totally hear the tradeoff. I think that will always be the downside of not implying ordering for the topics. 

If the concern with implying ordering is that we want to be able to reorder them without accidentally missing stuff like this, I wonder if we could solve that by just keeping an instructor document somewhere (maybe one for each learn repo, in the root) that notes lessons that contain things that depend on previous lessons.

2021-04-29 20:26 UTC, jmaddox19 reviewed
A couple little thoughts on the deploying to heroku lesson

2021-04-29 20:26 UTC, jmaddox19 commented on deployment/deploying-to-heroku.md
> +
Very soft suggestion: I wonder if it'd be less noisy in this case to just say if something didn't work, one of the above steps in this less wasn't performed properly and suggest they try to redo those commands. Feel free to ignore this if you disagree.

2021-04-29 20:26 UTC, jmaddox19 commented on deployment/deploying-to-heroku.md
> +We can verify that our Heroku app has added a Postgres database by checking the Heroku dashboard.
```suggestion
We can verify that our Heroku app has added a Postgres database by checking the [Heroku dashboard](https://dashboard.heroku.com/).
```

2021-04-29 20:47 UTC, tildeee commented on deployment/deploying-to-heroku.md
> +
@jmaddox19 Good suggestion! When I previewed this, it didn't feel like too much extra bloat, so I decided to go with the previous suggestion, but I would probably do exactly what you said if we felt like it were too long!!

2021-04-29 20:51 UTC, tildeee commented on deployment/deploying-to-heroku.md
> +
Hmm. I'm looking at this again, and I'm happy to turn this into a "callout" if that feels better, too.

<img width="1440" alt="Screen Shot 2021-04-29 at 1 49 58 PM" src="https://user-images.githubusercontent.com/30602862/116616858-0555e780-a8f2-11eb-8919-90a401b6309f.png">
<img width="1440" alt="Screen Shot 2021-04-29 at 1 51 24 PM" src="https://user-images.githubusercontent.com/30602862/116616863-071fab00-a8f2-11eb-9a0b-773efd5cc525.png">

2021-04-29 20:55 UTC, tildeee commented on deployment/deploying-to-heroku.md
> +
For the sake of moving forward with this PR (and since all of these were soft suggestions), I went with the original suggestion, but I'm super open to bringing this back in too (since now that I re-look at it, the section here is a bit long and I understand Jared's point)!

2021-04-29 21:12 UTC, tildeee commented on deployment/deploying-to-heroku.md
> +
Oh my goodness I completely forgot this was an issue, except when I did local development and my browser's history defaulted to `localhost:5000/books/` and I had to develop on an incognito window 😱 

Nitpicking:

```suggestion

### !callout-warning
## Routing Configurations May Result in a `404 Not Found`
Recall that Flask routes are very picky about `/` characters. Some browsers will try to put a `/` character at the end of an address automatically. Depending on how our routes are set up, this might result in a route mismatch.
<br />
Our Flask API isn't _intended_ to be used through a web browser. It's meant to be used programmatically. It's convenient if testing through a browser works, but if it doesn't we can move on to try testing with Postman.
### !end-callout

```

You KNOW I want to avoid referring to another lesson in another topic if possible 😆 Would you argue that the sentence is a make-or-break kinda deal for usefulness?

...Lastly, since this doesn't only apply to localhost, but also `https://your-app-name.herokuapp.com/books/`, should this go after the screenshot, right before the "No Book Data" callout?

2021-04-29 22:31 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
The callout looks nice. But one thing is that if we did that, then the passage after "Heroku makes use of..." that talks about pushing the change to requirements.txt should also be a part of the callout. But since you went with the original, I guess this comment is pointless. 😂 

Honestly, gunicorn _should_ be in the requirements. You put it in the requirements. It would only not be there if they removed it. But since the text said to confirm it was there, it sort of begs the "but what if it isn't?" And we haven't really given much discussion to updating requirements.txt, but it would be nice if students got used to the idea, so it seemed a reasonable thing to add. 🤷

2021-04-29 22:36 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
From a previous discussion we had I thought that linking to another topic was ok, since Learn validates links within the files and will report broken links if the resource gets moved.

If it's the implied ordering, we could say to refer to rather than to return to.

They COULD just move on to postman testing. It's not the end of the worlD. I mean, we don't NEED to remind them of where we told them how to avoid this issue, but I can't think of a good reason not to.

2021-04-29 22:41 UTC, anselrognlie commented on deployment/deploying-to-heroku.md
> +
Regarding placement, I was largely driven by my aversion to stacked callouts. 😂   I'm not wedded to its present location.

2021-04-29 23:00 UTC, tildeee commented on deployment/deployment.instructor.md
> +## Why is there a "Platforms" section in the deployment lesson?
```suggestion
# Instructor: Deployment

Flask is weird about `/`. In "Building an API"/"Create and Read" we have a tip about loosening the routing pattern so that "" and "/" routes do the same thing.

Sorry y'all I took out the direct link to that lesson </3 hehehe lolol.

## Why is there a "Platforms" section in the deployment lesson?
```

2021-04-29 23:05 UTC, tildeee commented on deployment/deployment.md
> +The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual use
Personally I like this callout especially because the Aleesha metaphor is only brought up in the previous Testing topic!

I think that an instructor or someone with a voice could bring it back to Aleesha; I'm gonna go with a change to smooth this out (sorry metaphorical dance crew!) and then move forward with this PR

```suggestion
The _production_ environment refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual users!
```

2021-04-29 23:15 UTC, jmaddox19 approved these changes
I just reviewed the lessons (not the activity and exercise) since I'm recording the videos and the lessons LGTM!

2021-04-29 23:19 UTC, merged

2021-04-30 00:29 UTC, anselrognlie commented on deployment/deployment.instructor.md
> +## Why is there a "Platforms" section in the deployment lesson?
💔

2021-04-30 00:31 UTC, anselrognlie commented on deployment/deployment.md
> +The _production_ environment is like Aleesha's main stage! It refers to the environment that runs our deployed, released application. This is where all our hard work gets made available to actual use
Aleesha, bye! ✋