building-an-api
Ada-Developers-Academy/core-unit-2 pull request #7
Opened 2021-03-26 22:16 UTC by tildeee

2021-04-13 21:24 UTC, jmaddox19 reviewed
Just a couple little suggestions I have after reviewing the lesson together

2021-04-13 21:24 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +
I'd love for us to just add this without feeling the need to even explain it much because it makes development so much smoother and from my understanding there's no reason not to use it until deploying a project.
```suggestion
app.debug = True
```

2021-04-13 22:40 UTC, jmaddox19 reviewed
a few more thoughts that came up

2021-04-13 22:40 UTC, jmaddox19 commented on building-an-api/models-setup.md
> +```
Can we note that we are executing this command within psql, just to avoid students trying to run this in the terminal then asking us for help?

2021-04-15 20:54 UTC, jmaddox19 commented on building-an-api/create-and-read.md
> +    }
I would prefer that we either stick to one way of returning responses in this first lesson or we have an aside/callout sort of situation each time we introduce a new way of returning a response. (returning a dict vs. Response() vs. something else)

2021-04-16 18:10 UTC, jmaddox19 commented on building-an-api/intro-to-flask.md
> +
```suggestion

The good news is that the framework deals with these problems so that we don't need to!

```
I think some variant of this would help to clarify that we are explicitly naming things they won't need to worry about

2021-04-16 18:32 UTC, jmaddox19 commented on building-an-api/intro-to-flask.md
> +
```suggestion

The web application framework we will be learning about is Flask. Much of our learning about Flask will be us learning how Flask needs us to write code to enable us to do the above things.

```
Again, just suggesting explicit clarification about how students should process this list. I think it could definitely be worded better but this is my attempt

2021-04-16 18:32 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +
This isn't successfully enabling debug mode for me with TaskList, so I think I'm missing something here.
@kaidamasaki do you have a quick guess about what might be missing?

2021-04-16 18:35 UTC, anselrognlie reviewed
comments for intro to flask

2021-04-16 18:36 UTC, jmaddox19 reviewed
Whoops! I thought I was folding all my intro-to-flask into one review but I guess I accidentally submitted feedback 2 or 3 different times. Sorry about the noise.

2021-04-16 18:36 UTC, jmaddox19 commented on building-an-api/intro-to-flask.md
> +There will be a desire for alternative approaches to problem-solving in Flask. Researching alternative Flask patterns will:
```suggestion
There will be a desire for alternative approaches to problem-solving in Flask. Independently researching alternative Flask patterns will:
```
Assuming this is meant to be independent work, I thought it'd be helpful to explicitly state that.

2021-04-16 18:40 UTC, jmaddox19 commented on building-an-api/flask-setup.md
> +Whenever we work on a Python project, we need to be considerate of how we manage dependencies. Working with the `flask` package is enough reason to visit virtual environments.
```suggestion
Whenever we work on a Python project, we need to be considerate of how we manage dependencies. Working with the `flask` package is enough reason to revisit virtual environments.
```

2021-04-16 18:54 UTC, jmaddox19 reviewed
Here's my full review of flask-setup!

2021-04-16 18:54 UTC, jmaddox19 commented on building-an-api/flask-setup.md
> +Whenever we work on a Python project, we need to be considerate of how we manage dependencies. Working with the `flask` package is enough reason to visit virtual environments.
```suggestion
Whenever we work on a Python project, we need to be considerate of how we manage dependencies. Working with the `flask` package is enough reason to revisit virtual environments.
```

2021-04-16 18:54 UTC, jmaddox19 commented on building-an-api/flask-setup.md
> +
```suggestion

### !callout-info

## No need to manually edit the requirements.txt file
Because we can use the above command to ask `pip` to update our `requirements.txt` file, there's no need to ever open up the file and edit it directly.

### !end-callout
```

2021-04-16 18:54 UTC, jmaddox19 commented on building-an-api/flask-setup.md
> +We can use the server logs to debug our server code. Any error messages that our server needs to print will go here.
```suggestion
We can use the server logs to debug our server code. After we run `flask run` from the terminal to start the server, any error messages that our server needs to communicate will be printed in that terminal window.
```

2021-04-16 18:54 UTC, jmaddox19 commented on building-an-api/flask-setup.md
> +It isn't often that developers need to fuss with configurations; web developers should become familiar of configuration files. It's more important to know _where_ existing configurations are made, ra
This is my attempt at adding a little bit here so we don't feel the need to go pull out all the things in the lesson about configuration
```suggestion
It isn't often that developers need to fuss with configurations; web developers should become familiar of configuration files. It's more important to know _where_ existing configurations are made, rather than being able to write fresh and new configurations.
All that to say: **This code is uniquely unimportant for us to thoroughly understand.** We will likely graduate the program without needing to do much more with this code that copy and paste it.
```

2021-04-16 19:27 UTC, jmaddox19 reviewed
Full review of flask-hello-books

2021-04-16 19:27 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +| `"hello_world_bp"`                                  | The first argument is a string that will be used to name this `Blueprint` for debugging purposes. It's conventional to use the same name as the
```suggestion
| `"hello_world_bp"`                                  | The first argument is a string that will be used to identify this `Blueprint` from the Flask server logs (in the terminal). It's conventional to use the same name as the local variable holding the instance (`"hello_world_bp"`). |
```

2021-04-16 19:27 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +| `@blueprint_name.route(...)`                        | This is a decorator for the endpoint. We use the defined Blueprint, and it's method `.route()`
```suggestion
| `@blueprint_name.route(...)`                        | This decorator transforms this function into an endpoint. We use the  `.route() instance method from our Blueprint instance.`                                                 |
```

2021-04-16 19:27 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +| `methods=["GET"]`                                   | A list of HTTP methods that must match
I think we could offer a clearer explanation by explaining both arguments at once and how to combine together to define when this function will get called.
```suggestion
| `"/endpoint/path/here", methods=["GET"]`                             |  Together these arguments define what type of request  will be routed to this function. The first argument defines the path (or URL) of the request and the second argument defines a list of HTTP methods (or verbs) the request could have.                                                                                     |
```

2021-04-16 19:27 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +| `def endpoint_name():`                              | This function will execute whenever a request that matches the decorator is received. The name of this function can be made with any decision.
I didn't really understand the 2nd sentence here so I took a guess at what it was trying to say and reworded it.
```suggestion
| `def endpoint_name():`                              | This function will execute whenever a request that matches the decorator is received. The function can be named whatever feels most appropriate. |
```

2021-04-16 19:27 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +    return "Hello, World!"
By making this the same as the example above, I think it will help students to more easily observe the meaningful differences between this code and the more generic code above.

```suggestion
    my_beautiful_response_body = "Hello, World!"
    return my_beautiful_response_body
```

2021-04-16 19:27 UTC, jmaddox19 commented on building-an-api/flask-hello-books.md
> +### !end-callout
I am not against giving this recommendation in other lessons but in this one it feels to me like the lesson is very much written for the student to work along as they read through the lesson. It is a series of experiments and actually isn't really (in my mind) that many new concepts. So I'd prefer removing these notes from this lesson in particular.

```suggestion
```

2021-04-16 19:42 UTC, jmaddox19 reviewed
This is my full feedback on the models lesson

2021-04-16 19:42 UTC, jmaddox19 commented on building-an-api/models.md
> +Similarly, before we work with different tables that hold our model data in Flask, we'll need to define database tables.
If my understanding from Ansel, that this isn't necessary or helpful, is true, we can remove this
```suggestion
```

2021-04-16 19:42 UTC, jmaddox19 commented on building-an-api/models.md
> +SQLAlchemy and Flask patterns may encourage us to define each model as a class in its own file.
If there's a reason for the passivity in voice here, I'm open to it, but I'd tend to prefer a little stronger voice from the curriculum for reassurance that it does indeed know what its talking about
```suggestion
SQLAlchemy and Flask patterns encourage us to define each model as a class in its own file.
```

2021-04-16 19:42 UTC, jmaddox19 commented on building-an-api/models.md
> +Every time we define a new model, we'll need to make a small configuration update to our app.
This is among my weaker opinions, so take it or leave it, but I don't find this practical kind of information helpful to name until we're explaining what that configuration change is. As a student, I just don't know what to do with this information when I read it here.
```suggestion
```

2021-04-16 19:51 UTC, anselrognlie reviewed
comments for flask setup

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +Whenever we work on a Python project, we need to be considerate of how we manage dependencies. Working with the `flask` package is enough reason to visit virtual environments.
be clear what we mean by dependencies
provide motivation for why we are revisiting virtual environments
acknowledge the reader has encountered virtual environments in this curriculum.
```suggestion
Whenever we work on a Python project, we need to consider how we manage our dependencies, the third party packages used by our project.

`flask` is a package with many of its own dependencies, which can quickly make a mess of our system-wide Python installation!

In reality, no Python project is too small to consider using a virtual environment. But working with a package that brings as many dependencies as does `flask` is reason enough for us to revisit the topic of virtual environments now.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +
acknowledge this is a review and remind the reader they can revisit previous material in the curriculum

```suggestion

We have been using virtual environments for a bit now, starting with our prior project work. We will present a brief review here, but we can always return to the previous material to refresh our memories about why we use virtual environments.

```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +Building an API means that we're building a web server. A web server needs to be _running_ in order to be accessible to clients. When a server is running, we'll know the full request URL for HTTP req
the end sounds a little weird, like we need to know this to run it? Refocus on how running the server makes it available for requests. Next comment introduces a callout for introducing the address in a bit more detail.

```suggestion
Building an API means that we're building a web server. A web server needs to be _running_ in order to be accessible to clients. Running a web server makes it available to respond to HTTP requests at a particular _address_ and _port_.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +
add a callout to introduce address and port

```suggestion

### !callout-info

## Address and Port Are Like Street Address and Apartment

Any service listening for network requests listens at a particular _address_ and a particular _port_. The _address_ can be thought of as like a street address, while the _port_ is more like an apartment number. If we send a letter to our friend Kerry, who lives in an apartment building, we need both the street address of the building itself, as well as their apartment number in the building. If we send a letter to the wrong building, Kerry won't receive it. If we send the letter to the wrong apartment number, Kerry still won't receive it (their neighbors are jerks and won't drop it off at their door).

<br />

Likewise, if we send a network request to the wrong address, then it won't reach the proper machine. If we send it to the wrong port, it still won't reach the web server. We need to know the address and port to make sure our request reaches the web server.

### !end-callout

```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +When a server starts running, it runs start-up commands, such as rebuilding the app from its configuration files.
I wouldn't call "rebuilding the app" the same as "running the app".

```suggestion
When a server starts running, it performs its startup routine, which often includes reading configuration files, changing settings, and connecting to any required resources.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +By default, running Flask servers will be available on `localhost:5000`. This means that our clients will send HTTP requests to `localhost:5000`. "Localhost" is a special name used to refer to the co
students will often see 127.0.0.1 so include that as well
call back to the address/port introduction above and name which parts are which

```suggestion
By default, running Flask servers will be available on `localhost:5000`. `localhost` acts as the address and `5000` is the port. They are separated by a colon. Our clients will send HTTP requests to `http://localhost:5000`.

<br />

`localhost` is a special name used to refer to the local computer itself. We may also see the local computer referred to as `127.0.0.1`, which is called an _IP address_. `localhost` and `127.0.0.1` mean the same thing: the local computer itself!
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +Once we start running a server, the current Terminal tab begins to _tail_ the server logs. The servers will log status updates about the server's operations.
```suggestion
Once we start running a server, the current Terminal tab begins to _tail_ the server logs. The server will log status updates about the server's operations.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +In order for us to run command-line commands like git, we'll need to open a new Terminal window, tab, or stop the server.
command-line command is a little awkward
additional to emphasize the original terminal should remain open
the final list mixes a few action types, so slightly restructured
```suggestion
In order for us to run terminal commands like `git`, we'll need to open an additional Terminal window or tab, or stop the server.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +When we stop a server, the server runs its shut down operations. Then, it's unavailable to clients.
I'd like it to be a bit more explicit about being "unavailable"
```suggestion
When we stop a server, the server runs its shut down operations. Once complete, it will no longer be available to handle requests until we start it again.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +- Close or quit the terminal tab or window
Maybe include a callout for troubleshooting in case students _do_ still get stuck processes? Next comment includes a possible callout (no suggestion because code)

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +- Close or quit the terminal tab or window
### !callout-info

## Sometimes the Server Gets Stuck

If something goes wrong when shutting down the server, or if the Terminal where the server was running is somehow closed without stopping the server, the server may become _orphaned_. When this occurs, the server may not release the address and port where it was running. If that happens, a new server will not be able to run using that address and port, and will fail to start. This may be reported with an error message resembling `OSError: [Errno 48] Address already in use`.

<br />

To locate another server using port 5000, which Flask wants to use, we can run `lsof -i:5000`. This will produce output similar to

```
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Python  31756  user    3u  IPv4 0x92416cca3d5db1fb      0t0  TCP localhost:commplex-main (LISTEN)
```

<br />

We can use the number labelled as `PID` to terminate the other running server with the command `kill -9 31756`, where we would replace `31756` with the `PID` value we got from running `lsof`.

### !end-callout

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +When we work on Flask projects, there could be anywhere between one file, to hundreds of files and folders.
```suggestion
When we work on Flask projects, there could be anywhere from one file, to hundreds of files and folders.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +Where our code that defines endpoints will **depend on the project**.
```suggestion
The place we put our code that defines endpoints will **depend on the project**.
```

or

```suggestion
Where our code goes that defines endpoints will **depend on the project**.
```

But I prefer the version that doesn't lead with a question word (the first one), since that can be an ambiguous start to a sentence.

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +As we develop our Flask projects, we'll need to reconfigure the app to suit our needs better. Configurations to the app can include things like, "Where's the location to our database?," "How do we lo
location of our database
not sure how confident students will be with data model on its  own here, so consider including a brief description

```suggestion
As we develop our Flask projects, we'll need to reconfigure the app to suit our needs better. Configurations to the app can include things like, "Where's the location of our database?," "How do we load different data models, the objects that represent our data?," or "How can we set up template views, called Blueprints?"
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +Where our code that defines any configuration, again, **heavily depends on the project**.
same situation as above. again I prefer the first option

```suggestion
The place we put our code that defines any configuration, again, **heavily depends on the project**.
```

or 

```suggestion
Where our code goes that defines any configuration, again, **heavily depends on the project**.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +Inside each `app` folder, there will be a file named `__init__.py`. The responsibility of this file is to define the start-up logic for the Flask server.
acknowledge that so far we've told students that nothing needs to go here
the following paragraphs take a hard turn to talking about configuration (but not really being bout configuraiton?) so massage this a bit to tie configuration into the start up process.

```suggestion
Inside each `app` folder, there will be a file named `__init__.py`. This is the same file we have used to mark a folder as a package! While we often leave this file blank, a common Flask pattern is to define the start-up logic for the Flask server in this file.

The start-up logic is responsible for locating and applying any app configuration, and getting the server ready to receive requests.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +It isn't often that developers need to fuss with configurations; web developers should become familiar of configuration files. It's more important to know _where_ existing configurations are made, ra
this feels a little too open-ended to me about what is and is not important about setting up a project.
Suggestion adds some boundaries.

```suggestion
Developers don't need to fuss with configurations that often. Usually, when setting up a project, we will refer to a previous working project to make sure the new one is configured appropriately.

<br />

We should try to become familiar with the kinds of settings we might want to configure in our app. Overall it's more important to know _where_ configuration _changes_ are made, rather than being able to write fresh configurations from scratch.
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +        db.create_all()
I assume removing this is on your radar already, but if you want to fill it with something else, maybe these comments?
```suggestion
    # import models (data objects) here

    # import routes (blueprints) here
```

2021-04-16 19:51 UTC, anselrognlie commented on building-an-api/flask-setup.md
> +- Creates a `db` reference and a `migrate` reference, which will be used to work with the db
```suggestion
- Creates a `db` reference and a `migrate` reference, which will be used to work with the database
```

2021-04-16 20:13 UTC, jmaddox19 reviewed
Here's my full review of models-setup!

2021-04-16 20:13 UTC, jmaddox19 commented on building-an-api/models-setup.md
> +
I'm wondering if we could do this collapsible text sort of thing for these pieces as a quick fix...
NOTE: I had to remove the triple ticks for the bash piece to get the suggestion to work so you'll need to add those back!

```suggestion
<details>
<summary>Click here if you're curious what we needed to update in the `app/__init__.py` file to properly include our Book model in our configuration.</summary>
If we ever design any more models, we'll need to import the new model here too, mimicking the pattern of `from app.models.book import Book`.

## Database Migrations

Everything is set up! The remaining actions left are to use our Flask tools to generate migrations.

Our database development workflow will be as follows:

1. Set up the db on the Flask end once
1. Generate migration files
1. Apply the migration files

### One-Time `init` Setup

After the first time that a database and at least one table are setup, we can do this one-time setup command:

```bash
(venv) $ flask db init

</details>
```

2021-04-16 20:13 UTC, jmaddox19 commented on building-an-api/models-setup.md
> +### Apply Migrations AFter Each Model Change
```suggestion
### Apply Migrations After Each Model Change
```

2021-04-16 20:13 UTC, jmaddox19 commented on building-an-api/models-setup.md
> +This command should be run after every time we've generated new migrations and want to apply them.
My understanding of this lesson tells me this is true. If it's not, I would love to understand why so that I can make an alternative suggestion on how to add clarity to these two commands

```suggestion
This command should be run after every time we've generated new migrations and want to apply them. At this introductory level, there is no reason for us to generate migrations without immediately applying them so we should always run `flask db migrate` and `flask db upgrade` back-to-back in that order.
```

2021-04-16 20:17 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +
We generally wouldn't hard code this into the app. Its usually controlled with either the FLASK_ENV=development or FLASK_DEBUG=1 environment variables.

If this _does_ get set explicitly, there should be a disclaimer that we are doing this out of expediency and that it generally would not be set this way in a deployed product.

2021-04-16 20:23 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +### !end-callout
Initially, I thought more in line with the original text, that the student should go all the way through to have the next step in mind as they work through it on the seconds pass.

But now I think I agree with Jared.

I think a first pass would quickly turn into just skimming through to get to the end, and I think the majority of a video would go by me in this situation if I weren't following along.

Even if they misstep along the way and get confused, at worst they can delete everything and start over.

2021-04-16 20:32 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +
VSCode also supports creating a flask launch configuration which sets the FLASK_ENV appropriately.

2021-04-16 21:20 UTC, jmaddox19 reviewed
Here's my full review of create-and-read!

2021-04-16 21:20 UTC, jmaddox19 commented on building-an-api/create-and-read.md
> +| `Response(...)`                                     | We instantiate a `Response` object so we can `return` it
```suggestion
| `make_response(...)`                                     | This function instantiates a `Response` object. A `Response` object is generally what we want to return from Flask endpoint functions.                                                                                                                                                              |
```

2021-04-16 21:20 UTC, jmaddox19 commented on building-an-api/create-and-read.md
> +| `f"Book {new_book.title} successfully created"`     | The first parameter to `Response` is the HTTP response body. Until we have more specifics requirements, let's send back a string for now.
```suggestion
| `f"Book {new_book.title} successfully created"`     | The first parameter to `make_response()` is the HTTP response body. Until we have more specific requirements, we will send back a string.                                                                              |
```

2021-04-16 21:20 UTC, jmaddox19 commented on building-an-api/create-and-read.md
> +| `status=201`                                        | We can define the status code of the `Response` by setting the kwarg `status` to a digit.
```suggestion
| `201`                                        | We can define the status code of the `Response` by passing an integer as the 2nd argument to `make_response()`. When a 2nd argument isn't specified `200` is always the default value.                                                                                                                              |
```

2021-04-16 21:20 UTC, jmaddox19 commented on building-an-api/create-and-read.md
> +`jsonify` is a Flask utility function that turns its argument into JSON. We'll use `jsonify` as a way to turn a list of book dictionaries into valid JSON.
I manually verified the type returned from `jsonify`.
```suggestion
`jsonify` is a Flask utility function that turns its argument into JSON. We'll use `jsonify` as a way to turn a list of book dictionaries into a `Response` object.
```

2021-04-16 21:20 UTC, jmaddox19 commented on building-an-api/create-and-read.md
> +| `jsonify(books_response)`                           | `books_response` contains a list of book dictionaries. To turn it into JSON, we pass it into `jsonify()`               |
```suggestion
| `jsonify(books_response)`                           | `books_response` contains a list of book dictionaries. To turn it into a `Response` object, we pass it into `jsonify()`. This will be our common practice when returning a list of something because the `make_response` function does not handle lists.               |
```

2021-04-16 21:20 UTC, jmaddox19 commented on building-an-api/create-and-read.md
> +For reasons that are less important to memorize, Flask will automatically convert a dictionary into an HTTP response body.
```suggestion
## Why Didn't We Call `jsonify()` or `make_response()` on the Dictionary?

For reasons that are less important to memorize, Flask will automatically convert a dictionary into an HTTP response body. If we don't want to remember this exception, we can call `jsonify()` or `make_response()` with the dictionary as an argument to return the result.
```

2021-04-16 21:24 UTC, jmaddox19 reviewed
With this, I'm done reviewing this PR...other than the likely back-and-forth that may happen with some of the feedback!

2021-04-16 21:24 UTC, jmaddox19 commented on building-an-api/activity-solar-system-api-setup-create-read.md
> +Driver and navigator roles should switch at least daily.
I'm confused by the daily recommendation. Is this an activity that spans multiple days? The suggestion as its written sounds to me like if one person stays the driver for the whole day, that's ok, which sounds like too much to me but maybe I'm missing something.
I would feel inclined to suggest it should switch every 30 minutes, but I've tried to keep it closer to your suggestion.
```suggestion
Driver and navigator roles should switch at least once during the activity.
```

2021-04-17 23:18 UTC, anselrognlie reviewed
comments for flask hello books

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +| `"hello_world_bp"`                                  | The first argument is a string that will be used to name this `Blueprint` for debugging purposes. It's conventional to use the same name as the
Building on Jared's suggestion (also incorporating the renamed string), since the var name and string _don't_ typically match, I'd provide some guidance here.
```suggestion
| `"hello_world"`                                     | The first argument is a string that will be used to identify this `Blueprint` from the Flask server logs (in the terminal). It's conventional to use a name related to the data being served or the functionality being provided. Here we are creating a "hello world" style endpoint, so "hello_world" is fine for our needs. |
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +| `__name__`                                          | The second argument is the name of the Blueprint package. This is almost always `__name__`.
provide some context for `__name__` and what it's used for. I don't know what I should take from the argument being "the name of the Blueprint package".

```suggestion
| `__name__`                                          | The second argument is almost always the special Python variable `__name__`, which the blueprint uses to figure out certain aspects of routing.                                                                                                                                                                                |
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +Every time we instantiate a new `Blueprint`, Flask requires us to register it with `app`. This is a fancy way to say that we need to configure the app to recognize and use `hello_world_bp`.
more explicitly say what the app is doing with this

```suggestion
Every time we instantiate a new `Blueprint`, Flask requires us to register it with `app`. This is a fancy way to say that we need to tell the `app` that it should use the endpoints from `hello_world_bp` for its routing.
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +| <div style="min-width:200px;"> Piece of Code </div> | Notes                                                                                                  |
widen to get a better word wrap
```suggestion
| <div style="min-width:240px;"> Piece of Code </div> | Notes                                                                                                  |
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +| <div style="min-width:250px;"> Piece of Code </div> | Notes
widen to get a better word wrap
```suggestion
| <div style="min-width:290px;"> Piece of Code </div> | Notes                                                                                                                                                                                                                                       |
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +| `@blueprint_name.route(...)`                        | This is a decorator for the endpoint. We use the defined Blueprint, and it's method `.route()`
again, building on Jared's suggestion (slight modification), but also, the code quote is out of place

```suggestion
| `@blueprint_name.route(...)`                        | This decorator transforms the function that follows into an endpoint. We use the `.route()` instance method from our Blueprint instance.                                                                                                    |
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +| `def endpoint_name():`                              | This function will execute whenever a request that matches the decorator is received. The name of this function can be made with any decision.
Building on Jared's suggestion
```suggestion
| `def endpoint_name():`                              | This function will execute whenever a request that matches the decorator is received. The function should be named using our typical practice of giving functions good, descriptive names. The name of the function has no effect on how requests are routed. |
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +
We explicitly say to use 200 OK, but don't say how to in the example and don't mention that it's the default. Suggest adding a callout about that.

```suggestion

### !callout-info

## `200 OK` Is the Default Response Status Code

We will see how to set explicit status codes in later lessons. If we don't set the status code ourselves, Flask will use `200 OK` by default.

### !end-callout

```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +hello_world_bp = Blueprint("hello_world_bp", __name__)
matching the previous suggestion
```suggestion
hello_world_bp = Blueprint("hello_world", __name__)
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +Sending an HTTP request should come up as new details in the server logs.
Spell out what triggers the line, and what they should see.
```suggestion
Each time we send an HTTP request to our server, we should see a new line appear in the server log.
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +Confirm that you can send a request and get a response back with Postman.
revoicing for we
```suggestion
We can confirm that we can send a request and get a response back with Postman.
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +Confirm that you can send a request and get a response back in the browser. This screenshot showcases a browser using a Google Chrome browser extension for viewing JSON.
revoicing for we
if the student doesn't have the plugin, it will look different, so mention that.

```suggestion
We can also confirm that we can send a request and get a response back in the browser. This screenshot showcases a Google Chrome browser extension for viewing JSON, so it's fine if the result doesn't look the same as this.
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +Confirm that you can also see server log output.
revoicing for we
```suggestion
Finally, we can confirm that we can also see output in the server log.
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +Place this third endpoint into `routes.py`. It is intentionally broken.
more invitational tone
```suggestion
Let's place this third endpoint into `routes.py`. It is intentionally broken.
```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +
encourage checking the server log for the error (errors appear here even if the server isn't in debug mode)
also, add a callout for running the project in debug mode to get the error output shown in the screenshot
the callout is in the next comment (no suggestion because code)

```suggestion

We should also confirm that we can see the same error output in our server log.

```

2021-04-17 23:18 UTC, anselrognlie commented on building-an-api/flask-hello-books.md
> +
### !callout-info

## Flask Shows Helpful Error Messages in Debug Mode

If our browser shows only a `500 Internal Server Error` when we access this endpoint, we can restart Flask in debug mode. Running in debug mode will provide more details in the browser when an error is encountered in our server code. This information _could_ be used by malicious clients to learn about our server implementation, so we usually don't run deployed servers in debug mode.

<br />

To start Flask in debug mode, we should stop any current running Flask servers, then restart our server by running the following command.

```
FLASK_ENV=development flask run
```

### !end-callout

2021-04-18 01:25 UTC, anselrognlie reviewed
Comments on models

This is a significant change due to the original version bringing up table creation, which we don't need to do. Restructured the lesson to avoid this.

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +| Model              | A representation of a single concept relevant to the application that contains the state and behavior                                                 | Data model, resource, en
"the state and behavior" feels a little disconnected

```suggestion
| Model              | A representation of a single concept relevant to the application. The model defines the state and behavior for that concept.                          | Data model, resource, entity, domain model | "Example models in an e-shopping web app might be `User`, `Product`, `Review`, and `Order`"                                                               |
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +1. Ensure our Flask code has defined and can use the model
part of removing table stuff from the lesson. The next section provides a set of steps that we can expand to cover everything, so just cut this

```suggestion
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +## Models Relate to Databases
retitle since we won't make the same python/db split (since the db-specific section now would just be create a db)

```suggestion
## Models Are a Link Between a Database and Code
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +1. Use our database migration tools
expand the steps to reflect the non-table focused version

```suggestion
1. Configure our app to connect to the database
1. Define our model in Python code
1. Ensure that Flask and SQLAlchemy are able to see our model code
1. Use tools to convert the model into instructions for creating or updating tables
1. Apply the instructions to our database to create or update the tables
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +### Connecting the DB and Flask
```suggestion
### Connecting the Database and Flask
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +1. Configure our Flask app to use the model
We don't need this separate chunk of steps anymore since we have the full layout above
```suggestion
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +## Create the Model File and Class
a few of the headers below here will need to be shifted in one since they should all be at the same level as the other steps
```suggestion
### Create the Model File and Class
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +This curriculum's recommended file structure recommends creating a `models` folder inside of the `app` folder. Note the location of a hypothetical model, `model`, in `app/models/model.py`
incorporates Jared's change
expands the description of the file layout to include the __init__.py needed for packaging

```suggestion
#### The `app/models` Directory

SQLAlchemy and Flask patterns encourage us to define each model as a class in its own file.

This curriculum's recommended file structure creates a `models` folder inside of the `app` folder. Note the location of a hypothetical model, `Model`, in `app/models/model.py`, as well as the typical `__init__.py` file to mark the folder as a package.
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +SQLAlchemy and Flask patterns may encourage us to define each model as a class in its own file.
(I incorporated this suggestion into mine as well.)

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +└── requirements.txt
reorder to reflect how VSCode would show things, and include the __init__.py in models
```suggestion
├── app
│   ├── models
│   │   ├── __init__.py
│   │   └── model.py
│   ├── __init__.py
│   └── routes.py
├── README.md
└── requirements.txt
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +
add additional sections for the generate migrations and apply migrations at this level of detail (I know it's brought up again below, but I think it works ok)

```suggestion

### Generate Instructions for Modifying Our Database

Flask and SQLAlchemy, our package connecting our models to the database, provide many useful model-related features. One such feature is that it can examine our models defined in Python, and produce a list of instructions for how to modify the database to be able to store the state of those models. This can include both creating new tables, and altering existing tables.

### Apply the Instructions to Modifying Our Database

Once the instructions have been generated, we use Flask and SQLAlchemy to apply those instructions to our database.

Generating and applying these instructions in separate steps allows for teams to work together. One member might add a new model, and generate instructions for a new table to be created. They will commit that model and the instructions to the team repo. The other members can retrieve those instructions and apply the same change to their local working databases.

```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +SQLAlchemy, our package that connects our models to the database, has powerful functionality. Instead of writing full lines of SQL, we will write Python that uses SQLAlchemy. SQLAlchemy will do most
bring this up a level to make a separate topic for using the models
some rewording since I used some of the existing verbiage above

```suggestion
## Using Defined Models in Flask

We don't need to write the code for storing, retrieving, or updating our models. SQLAlchemy lets us define our models as normal Python classes. Instead of writing full lines of SQL ourselves, we will write Python classes following patterns defined by SQLAlchemy, and SQLAlchemy will do most of the SQL heavy lifting for us!
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +
here's my suggestion for the ORM callout

```suggestion

### !callout-info

## SQLAlchemy Is an Object-Relational Mapper (ORM)

There are many ways to connect Python to a database. Some of them require us to write specific SQL queries ourselves. SQLAlchemy instead provides a connection from our Python classes (objects) to tables in a database (relations). In other words, it maps from object to relations. It's an Object-Relational Mapper!

<br />

In general, an Object-Relational Mapper is a tool that allows us to interact with tables without needing to write SQL directly.

### !end-callout

```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +On bigger and bigger projects, we should anticipate the effects of changing our database schemas. We can organize our database schema changes into _database migrations_.
provide motivation for why these migrations happen

```suggestion
On bigger and bigger projects, we should anticipate the need to change our database schemas. Over time we will need to add new models to our projects, or we might need to modify existing models. Changes to our models require changes to our database schema. To provide the ability to track our database schema changes, we can organize our changes into _database migrations_.
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +A **datatbase migration** a representation of a change in a database's schema, usually as bit of code or a file of code. After migration files are created, these migration files can be applied to a d
```suggestion
A **database migration** is a representation of a change in a database's schema, usually as bit of code or a file of code. After migration files are created, these migration files can be applied to a database.
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +Because the scale of our projects is increasing, we will also introduce a database migration tool.
I think the provided reason is spurious. Let's just say that if we are using migrations we need to use a migration tool.

```suggestion
Migrations are usually applied using a database migration tool.
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +[Alembic](https://alembic.sqlalchemy.org/en/latest/) is the database migration tool that pairs nicely with SQLAlchemy. We will follow common database and Alembic practices to manage and maintain our
the original text would sound more grammatical as "Alembic is a database migration tool..." but I think declaring that it's the tool we will use and then cite the SQLAlchemy pairing flows a bit better. 

```suggestion
[Alembic](https://alembic.sqlalchemy.org/en/latest/) is the database migration tool that we will be using. It pairs nicely with SQLAlchemy. We will follow common database and Alembic practices to manage and maintain our migrations.
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +After the first database, table, and the configurations are set, we must initialize our migrations. We will only need to do this once.
excise table reference

```suggestion
After our database is created and we have configured our application to use it, we must initialize our migrations. We will only need to do this once.
```

2021-04-18 01:25 UTC, anselrognlie commented on building-an-api/models.md
> +
This doesn't seem helpful here. We don't give the actual command, so why would we show the creation of the migration folder. Even when we _do_ give the command, I don't know that dwelling on the details of the contents provides much benefit.

```suggestion
```

2021-04-18 05:26 UTC, anselrognlie reviewed
comments for solar system api activity

2021-04-18 05:26 UTC, anselrognlie commented on building-an-api/activity-solar-system-api-setup-create-read.md
> +   1. Setup the `Planet` model
swap the ordering since we should create the model first, and then have flask set up the table
```suggestion
   1. Setup the `Planet` model with the attributes `id`, `name`, and `description`, and one additional attribute
   1. Create a migration to add a table for the `Planet` model and then apply it. Confirm that the `planet` table has been created as expected.
```

2021-04-18 05:26 UTC, anselrognlie commented on building-an-api/activity-solar-system-api-setup-create-read.md
> +- Add all members to the forked repo as collaborators (through the repo settings)
Will students know how to do this yet, or should there be further explanation?

2021-04-18 05:26 UTC, anselrognlie commented on building-an-api/activity-solar-system-api-setup-create-read.md
> +Decide who will be the driver today. The person who most desires to practice confidence today should drive first.
Align with the suggestion above to de-emphasize dailiness.

```suggestion
Decide who will be the initial driver. The person who most desires to practice confidence should drive first.
```

2021-04-18 06:37 UTC, anselrognlie reviewed
comments for models setup

This is another lesson that needs restructuring since SQLAlchemy should be creating the table

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +## Connecting the DB and Flask
```suggestion
## Connecting the Database and Flask
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +The following is one of many formats to help locate our database. We choose this format because it will benefit some future setup instructions we have later.
I don't think we need to dwell on how many ways there are to point at the database. Let's just say what we're using. We should introduce it as a connection string, which is super common terminology for this value.

```suggestion
We need to tell Flask where to find our new database. We do this by supplying a _connection string_ that identifies where it is, and how to connect to it.

A connection string resembles the following:
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +
provide an explanation of what is going on in the connection string. Hopefully that well help it seem more approachable and not just a massive chunk of characters.

```suggestion

This tells Flask to connect to our database using the `psycopg2` package we installed from our `requirements.txt`. It connects using the `postgres` protocol using the `postgres` user on the local machine running at port `5432`.

```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +### Configure the DB in `app/__init__.py`
```suggestion
### Configure the Database in `app/__init__.py`
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +Read through this code that configures the DB to use SQLAlchemy appropriately for our app.
re-voice for we
```suggestion
We can examine this code, which configures the database to use SQLAlchemy appropriately for our app.
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +Then, align your `app/__init__.py` file so it looks identical.
re-voice for we
```suggestion
Then, we can edit our `app/__init__.py` file so it looks identical.
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +   1. We set `app.config['SQLALCHEMY_DATABASE_URI']` to the pathway to our database, `hello_books_development`
explain what the first line is doing
refer to the connection string as a connection string (it's not really a path)
```suggestion
   1. We set `app.config['SQLALCHEMY_TRACK_MODIFICATIONS']` to `False` to hide a warning about a feature in SQLAlchemy that we won't be using.
   1. We set `app.config['SQLALCHEMY_DATABASE_URI']` to the connection string for our database, `hello_books_development`
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +$ mkdir app/models
include creating the package file
```suggestion
$ mkdir app/models
$ touch app/models/__init__.py
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +└── requirements.txt
re-order for vscode and include the package file
```suggestion
├── app
│   ├── models
│   │   ├── __init__.py
│   │   └── book.py
│   ├── __init__.py
│   └── routes.py
├── README.md
└── requirements.txt
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +### Models are Classes that Inherit `db.Model`
verbs should be capitalized. rules vary for the other words, but if we go with the 4 letters is long enough rule, then that and from should also be capitalized
```suggestion
### Models Are Classes That Inherit From `db.Model`
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +1. Connect the model seamlessly with our SQL database, mapping attribute to table column
```suggestion
1. Connect the model seamlessly with our SQL database, mapping attributes to table columns
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +| `class Book(...)`                                   | We define a new class, and name it after our model (usually singular)                                                   |
include notice about how this affects the table name that SQLAlchemy will pick
```suggestion
| `class Book(...)`                                   | We define a new class, and name it after our model (usually singular). By default, SQLAlchemy will use the lowercase version of this class name as the name of the table it will create.                                                   |
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +| `id = db.Column(...)`                               | Instances of `Book` will have an attribute `id`, which maps to a database column                                        |
acknowledge that this is different from how we do things with plain old python objects
prefer "will map" since at this point we haven't created the table
```suggestion
| `id = db.Column(...)`                               | Instances of `Book` will have an attribute `id`, which will map to a database column. Notice that this attribute goes outside of any instance method and doesn't reference `self`. This is part of the pattern that models deriving from `db.Model` will follow, even though it's a little different from a typical Python class.                                      |
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +| `db.Integer`                                        | A column data-type that SQL Alchemy defines. The `id` column accepts integers.                                          |
```suggestion
| `db.Integer`                                        | A column data-type that SQL Alchemy defines. The `id` column stores integers.                                          |
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +| `primary_key=True, autoincrement=True`              | Keyword arguments that allow SQLAlchemy to understand how to fill in the values for new `Book` instances                |
tie back to some of the concepts that came up about primary keys in the SQL lessons
```suggestion
| `primary_key=True, autoincrement=True`              | Keyword arguments that allow SQLAlchemy to understand how to fill in the values for new `Book` instances. Notice how they resemble constraints that can be supplied to a column.                |
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +| `description = db.Column(db.String)`                | Creates a `description` attribute, which maps to the string column, `description`                                       |
prefer "will map" since we haven't made the table yet
```suggestion
| `title = db.Column(db.String)`                      | Creates a `title` attribute, which will map to a string column, `title`                                                   |
| `description = db.Column(db.String)`                | Creates a `description` attribute, which will map to a string column, `description`                                       |
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +Congratulations on defining your first Flask model!
re-voice to we
```suggestion
Congratulations! We've defined our first Flask model!
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +### !end-callout
alternatively we can rephrase to make it clear that we _didn't_ do this here, but could. This could be referenced later when discussing single/plural table names during the migration discussion.

```suggestion
### !callout-secondary

## Specifying the Table Name

In model definitions, if we don't like the default name that SQLAlchemy picks we can specify a different name for the table, using the `__tablename__` property. There is more to research here!

### !end-callout
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +### Configuring the `Book` Model in `__init__.py`
we're not doing anything to the book model here, we're just making it visible
```suggestion
### Making the `Book` Model Visible to the `app` in `__init__.py`
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +Now that we've defined `Book`, we need to make sure our `app` sees it. During the configuration step, we need to import `Book` and connect it to our SQLAlchemy `db`.
Other than the import, we don't need to do anything to connect it.
```suggestion
Now that we've defined `Book`, we need to make sure our `app` sees it. To do so, we need to import `Book` during the `app` startup.
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +There is new code after `db` and `migrate` are initialized, but before the `return app` statement. This code essentially connects the Flask `app` and the SQLAlchemy `db` to see each other.
reworked since the create_all stuff should be removed

```suggestion
Notice the new `import` code after `db` and `migrate` are initialized, but before the `return app` statement. This code ensures that the `Book` model will be available to the `app` when we update our database in a moment.
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +        db.create_all()
not needed (and bypasses migration tracking)
```suggestion
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +
we've previously told students that imports go at the top, so acknowledge this difference
```suggestion

### !callout-warning

## Sometimes Imports Don't Go at the Top

Generally we prefer to put `import` statements at the top of our files. However, doing so here would result in an error called a _circular import error_. There are a number of ways to avoid this error, but by far the most straight-forward way is to place this `import` inside a function so that it doesn't run until the function gets called.

<br />

Sometimes we need to bend what we consider to be a best practice to address an immediate situation.

### !end-callout

```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +Everything is set up! The remaining actions left are to use our Flask tools to generate migrations.
everything isn't set up, but after the migration it will be
```suggestion
Our model is set up! The remaining actions left are to use our Flask tools to generate the migrations that we'll be able to use to update our database.
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +1. Set up the db on the Flask end once
```suggestion
1. Set up the database on the Flask end once
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +After the first time that a database and at least one table are setup, we can do this one-time setup command:
rephrase due to table handling change
```suggestion
Once we have created our database and configured the connection string, we can do this one-time setup command:
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +(venv) $ flask db migrate
include the message option to label our migration
```suggestion
(venv) $ flask db migrate -m "adds Book model"
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +
I have suggestions to bring the text in line with have Flask create the table, so hiding shouldn't be required.

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +
explanation for the -m option by comparing it to commit messages
```suggestion

Notice that just like when we make `git` commits, here too we can record a message summarizing the changes we have made. When running this command ourselves, we should replace the `"adds Book model"` with a description relevant to our recent changes.

```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +└── requirements.txt
reorder to better match vscode and include the package files
```suggestion
├── app
│   ├── models
│   │   ├── __init__.py
│   │   └── book.py
│   ├── __init__.py
│   └── routes.py
├── migrations
│   ├── alembic.ini
│   ├── env.py
│   ├── README
│   ├── script.py.mako
│   └── versions
├── README.md
└── requirements.txt
```

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +This command should be run after every time we've generated new migrations and want to apply them.
Yep, students should always run them back to back. Though when working in a group, only one person should modify a model and generate the migration (and run upgrade locally). Those should get checking in and pulled by the other team members. Each other team member would then run the upgrade without running the migrate.

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +
Add a section about confirming that the migration applied successfully. Suggestion in following comment. No suggestion due to code.

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +
### Confirm the Migration

We should now be able to connect to our database with `psql` and confirm that the `book` table has been created. Connect to Postgres with:

```
psql -U postgres
```

Once in the Postgres interactive terminal we can run `\c hello_books_development` to connect to the database. We can list the tables in the database with `\dt` which should show us `book`, and another table called `alembic_version` which tracks our migrations. We can display the columns of the `book` table by running `\d book`, which will show `id`, `title`, and `description`.

Congratulations! We've created our first Flask model table!

2021-04-18 06:37 UTC, anselrognlie commented on building-an-api/models-setup.md
> +
Add an acknowledgement about the singularity of the table name despite our previous guidance in the SQL lessons. This is based on the section that had been up around the manual table creation section, expanded.

```suggestion

### !callout-warning

## Singular Table Names vs. Plural Table Names

Different situations call for different conventions. Notice that SQLAlchemy used the name `book` for the table. Previously, we have suggested using plural table names, like `books`.

<br />

Traditional database practice often uses plural names for tables, since conceptually a table holds many records. A `books` table would hold many book records. However, class names usually use singular names, since they are a description for a single instance of our type. So we make a `Book` class rather than a `Books` class. For simplicity, SQLAlchemy uses this class name for the table name.

<br />

We could tell SQLAlchemy that we would rather use a table name of `books`. There is only a small amount of additional code we would need to write. But then our class and table names wouldn't match, which could lead to confusion. As a result, we will recommend that we use `book`, and other singular table names with Flask. We should be ready to adapt our practices to the context in which we are operating. Even though database tables are often plural, sometimes they will be singular!

### !end-callout

```

2021-04-18 22:16 UTC, anselrognlie reviewed
comments for create and read

biggest change echoes jared's feedback on reordering the creation and registration of the blueprint.

I also have some concerns about the code samples showing the use of variables that shadow the function name they're defined in.

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +No request body.
reminder about why we don't need the request body
```suggestion
`GET` requests do not include a request body, so no additional planning around the request body is needed.
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +During this method, we will need to:
the same transitional phrase as before
```suggestion
Now that we have an idea of what our endpoint should look like, we can turn our attention to how to implement it.

Our endpoint will need to:
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +1. Retrieve the book with the matching `book_id` from the db
```suggestion
1. Retrieve the book with the matching `book_id` from the database
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +Let's create an entirely new route.
provide motivation for why a new route is required
```suggestion
Our new route needs to read data from the incoming request path. Our existing route doesn't do this, so we'll need to add an entirely new route to our existing `Blueprint`.
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +This route has a **route parameter**. The route `/books/1` should give us the details for the book with `id` 1. `/books/2` should give us details for book with `id` 2, `/books/3000` should give us de
we haven't (quite) seen the code yet, so saying it has the parameter sounds a little strange
```suggestion
Our new route needs a **route parameter**. The route `/books/1` should give us the details for the book with `id` 1. `/books/2` should give us details for book with `id` 2, `/books/3000` should give us details for book 3000, and so on.
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +Our new route will need to account for this.
and now I'm desperate to start a passage without the words "Our new route" 🤣 
```suggestion
Let's take a look at how our new route will account for this!
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +| `"/<book_id>"`                                      | This is the `Blueprint` syntax to indicate _route parameters_. `<book_id>` shows that we are looking for a variable value (could be `1`, `2`, o
dealing with the "any decision" phrasing
```suggestion
| `"/<book_id>"`                                      | This is the `Blueprint` syntax to indicate _route parameters_. The `<book_id>` placeholder shows that we are looking for a variable value (could be `1`, `2`, or `3000`). We'll use this value in the function as the variable `book_id`, so we should use a good, descriptive name. |
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +| `def book(book_id):`                                | This `book` function is called whenever the HTTP request matches the decorator. The name of this function can be made with any decision. We mus
dealing with "any decision"
details about exactly what ends up in the parameter
further edits may be required if there is concern about the name collision between the function and the variable.

```suggestion
| `def book(book_id):`                                | This `book` function is called whenever the HTTP request matches the decorator. The name of this function should follow the previously discussed guidelines. We must add a parameter to this method, `book_id`. This parameter name must match the route parameter in the decorator. It will receive the part of the request path that lines up with the placeholder in the route.               |
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +| `Book.query.get(book_id)`                           | We must pass in the primary key of a book here. The primary key of the book we're looking for is in the route parameter, `book_id`.
```suggestion
| `Book.query.get(book_id)`                           | We must pass in the primary key of a book here. The primary key of the book we're looking for was provided in the route parameter, `book_id`.                                                                                                                                                      |
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +| `{ "id": book_id, ... }`                            | We can create a dictionary literal for our HTTP response.
use the result book object to match the code
```suggestion
| `{ "id": book.id, ... }`                            | We can create a dictionary literal for our HTTP response.                                                                                                                                                                                                                                |
```

2021-04-18 22:16 UTC, anselrognlie commented on building-an-api/create-and-read.md
> +
add a callout to warn against putting too much stock in the placeholder names (python doesn't know what a book id is and blindly takes whats left of the path)

```suggestion

### !callout-warning

## Python Doesn't Know What a `book_id` Is

We called the route parameter `book_id` and expect it to be an id of a book. But just like regular variable names, Python has no idea what a `book_id` is. All it does is look for whatever part of the URL path follows `/books/` and captures that into the variable `book_id`. So a request for `/books/my_long_value` would set the value of `book_id` to be `"my_long_value"`.

<br />

We should be careful to avoid thinking that Python uses the name of the parameter to do any kind of validation. As usual, the name provides information to us developers, not to Python. 

### !end-callout

```

2021-04-18 22:24 UTC, anselrognlie requested changes
Finished my review pass.

@tildeee GH is really teetering on the edge (as seems to be our usual experience!!!). I _am_ still able to view the file view after a couple retries, but we're really close again.

2021-04-19 04:43 UTC, tildeee commented on building-an-api/flask-hello-books.md
> +A common installation error may be solved by executing `$ pip install --upgrade pip`. Afterwards, attempt `$ pip install -r requirements.txt` again. _(Note: Written March 2021.)_
This date supposed to shame us into double checking periodically! Taking out the dates from the others and leaving this top one.

2021-04-19 06:45 UTC, merged