Update and delete
Ada-Developers-Academy/core-unit-2 pull request #8
Opened 2021-03-29 21:13 UTC by tildeee

2021-04-20 05:00 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +We can also check if our book was updated in the database using `psql`!
flesh this out a bit as in the last lesson (at least for this first one)
```suggestion
We can also check if our book was updated in the database using `psql`, just as we did when creating new records!

Let's try it out on our own! We can refer back to the Intro to SQL lessons if we need a reminder about how to write a query like this.
```

2021-04-20 05:00 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +* Predicted the HTTP response, request, and logic for this endpoint
match lesson changes
```suggestion
* Planned the HTTP response, request, and logic for this endpoint
```

2021-04-20 05:00 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +* Saved the instance of `Book` in the database
reflect the actual action
```suggestion
* Updated the instance of `Book` in the database
```

2021-04-20 05:01 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +* Predicted the HTTP response, request, and logic for this endpoint
match the question revision
```suggestion
* Planned the HTTP response, request, and logic for this endpoint
```

2021-04-20 05:01 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +* Saved the instance of `Book` in the database
match the question revision
```suggestion
* Updated the instance of `Book` in the database
```

2021-04-20 05:02 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +There are many cases that weren't covered in this lesson, even though they are relevant to creating and reading `Book`s. For example, what happens if we make a `GET` request to `/books/this-book-does
match the verb
```suggestion
There are many cases that weren't covered in this lesson, even though they are relevant to creating and reading `Book`s. For example, what happens if we make a `PUT` request to `/books/this-book-doesnt-exist`? We are intentionally not covering these cases at the moment, to limit this lesson. However, hypothesize and research how to handle erroneous HTTP requests. Follow your curiosity!
```

2021-04-20 05:02 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +### Predict HTTP Requests, Responses, and Logic
```suggestion
### Planning HTTP Requests, Responses, and Logic
```

2021-04-20 05:05 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +Let's consider the endpoint to create a book:
prompt for verb and endpoint consideration
```suggestion
We should think about the typical HTTP verb and endpoint used for requests that delete a particular model record.

For this feature, we should make a `DELETE` request to the `/books` path, and we'll need to include the `id` of the record to delete as part of the endpoint.
```

2021-04-20 05:06 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +No request body.
details about why we don't need the request body
```suggestion
`DELETE` requests do not generally include a request body, so no additional planning around the request body is needed.
```

2021-04-20 05:37 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +| `id` | `title`                        | `description`                                     |
formatting
```suggestion
| <div style="min-width:40px;">`id`</div> | `title`                | `description`                               |
```

2021-04-20 05:38 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +The response we want to send back is:
discussion of the response
```suggestion
When the record is successfully updated, we should return the appropriate status code, which is `200 OK`. Some APIs return the the record that was just deleted as the response body, but for simplicity, we will return a brief status message.
```

2021-04-20 05:38 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +During this method, we will need to:
typical transition text
```suggestion
Now that we have an idea of what our endpoint should look like, we can turn our attention to how to implement it.

Our endpoint will need to:
```

2021-04-20 05:40 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +1. Send back a response
call out using the route param and looking it up in the db
characterize the `delete` call as informing the database of our intent to delete, prior to the commit call

```suggestion
1. Read the `book_id` in the request path
1. Retrieve the `Book` instance with the matching `book_id` from the database
1. Tell the database to delete this instance of `Book`
1. Save this change in the database
1. Send back a response
```

2021-04-20 05:41 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +Let's look at this example code for our delete feature.
similar updates as above
```suggestion
This endpoint uses the same path as our existing parameterized route, `"/<book_id>"`, so we can refactor and expand on the same function.

Let's modify our endpoint code to support the delete feature.
```

2021-04-20 05:41 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +    book = Book.query.get(book_id)
as mentioned above, we should consider not having a variable shadow the function it's defined in

2021-04-20 05:41 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +        return Response(f"Book #{book.id} successfully deleted", status=200)
```suggestion
        return make_response(f"Book #{book.id} successfully deleted")
```

2021-04-20 05:43 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +| `book = Book.query.get(book_id)`                    | This feature will need to find our matching `Book` instance, so we still need to use `book`
remind what book is and what this line does to fill it
```suggestion
| `book = Book.query.get(book_id)`                    | This feature will need to find our matching `Book` instance, so we still need the lookup code using `book_id` and store the found book in `book`                                                           |
```

2021-04-20 05:44 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +| `db.session.delete(book)`                           | We can use SQLAlchemy's functions to delete our `book` with `db.session.delete(book)`
explain how this is notifying sqlalchemy of the pending deletion
```suggestion
| `db.session.delete(book)`                           | We can use SQLAlchemy's functions to tell the database to prepare to delete our `book` with `db.session.delete(book)`                                                                 |
```

2021-04-20 05:44 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +| `return Response(...)`                              | This is one of many ways to return an HTTP response
```suggestion
| `return make_response(...)`                              | This is one of many ways to return an HTTP response. Since we didn't supply a status code, Flask will default to `200 OK`.                                                                                                   |
```

2021-04-20 05:45 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +| `f"Book #{book.id} successfully deleted"`           | We can still access `book.id` because the variable itself is still in scope in our app, even if the `book` _was_ successfully deleted in the da
explicitly state that retrieved book instance isn't a live copy attached to changes in the database
```suggestion
| `f"Book #{book.id} successfully deleted"`           | We can still access `book.id` because the variable itself is still in scope in our app, even if the `book` _was_ successfully deleted in the database. The object stored in memory and referenced by `book` does not automatically update in response to changes in the database. |
```

2021-04-20 05:45 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +We could also use `psql` to check this, too.
similar (but smaller) expansion as above
```suggestion
### Manually Testing with `psql`

We can also check if our book was deleted from the database using `psql`.

Let's try it out on our own!
```

2021-04-20 05:46 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +* Predicted the HTTP response, request, and logic for this endpoint
```suggestion
* Planned the HTTP response, request, and logic for this endpoint
```

2021-04-20 05:46 UTC, anselrognlie commented on update-and-delete/update-and-delete.md
> +* Predicted the HTTP response, request, and logic for this endpoint
```suggestion
* Planned the HTTP response, request, and logic for this endpoint
```

2021-04-20 05:51 UTC, anselrognlie commented on update-and-delete/activity-solar-system-api-update-delete.md
> +# Activity: Solar System API: Update, Delete
Ah. Now I see why the previous incarnation of solar system switched drivers daily!

2021-04-20 05:52 UTC, anselrognlie commented on update-and-delete/activity-solar-system-api-update-delete.md
> +1. Create the `planet` table with the columns `id`, `name`, and `description`, and the one additional column
this should be unnecessary. running the upgrade should apply the migration, creating the table
```suggestion
```

2021-04-20 07:18 UTC, anselrognlie reviewed
comments for 404 and more

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +- Exploring more query functionality available by Flask-SQLAlchemy
```suggestion
- Exploring more query functionality made available by Flask-SQLAlchemy
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +
details often need a br to push them down.
```suggestion

<br />

```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +### Predict HTTP Requests, Responses, and Logic
```suggestion
### Planning HTTP Requests, Responses, and Logic
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +Let's consider the endpoint to get a single book:
prompts for why we used this endpoint
```suggestion
This feature is a variation on our existing endpoint that reads a record, but it uses an invalid id. As a result, we can use the following verb and endpoint combination.
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +No request body.
more explicit reasoning for lack of request body
```suggestion
As with our existing `GET` requests, we do not send a request body.
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +The response we want to send back is:
reasoning about the response
```suggestion
We want to inform the client that the record was not found. The most appropriate response status code is `404 Not Found`. We could return an error message that echoes back the id the client submitted, but for simplicity, we'll just return the status code and leave the body empty.
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +During this method, we will need to:
slight variation on the transitional phrase we've been using
```suggestion
Now that we have planned out the endpoint behavior, we can turn our attention to how to implement it.

Our endpoint will need to:
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +When `Model.query.get(primary key)` doesn't find a matching record, it returns `None`!
primary_key to be more pythonic
```suggestion
When `Model.query.get(primary_key)` doesn't find a matching record, it returns `None`!
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +For this feature, we must return to our `GET` `/<book_id>` endpoint and re-work it.
reiterate why we're going back to the same route
```suggestion
This endpoint uses the same path as our existing parameterized route, `"/<book_id>"`, so we can re-work it to add our new behavior.
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +Let's look at this example code for one strategy:
invite the reader to perform this modification even though we're going to refactor
```suggestion
Let's modify our endpoint code to report a not found status when trying to `GET` a book.
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +            return Response("", status=404)
when checking against `None`, `is` is more idiomatic than `==`. What I'd really like to  use is `if not book:` but that seems like it would need a callout that would be more distracting than helpful.

also replace Response with call to helper
```suggestion
        if book is None:
            return make_response("", 404)
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +| `return Response("", status=404)`                   | We sent back an empty string as our empty response body                                     |
reflect the above changes in the explanation
```suggestion
| `if book is None:`                                  | This checks if `Book.query.get(book_id)` returned `None` because there was no matching book |
| `return make_response("", 404)`                   | We sent back an empty string as our empty response body and set the status code to `404 Not Found`                                     |
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +We can consider refactoring and then testing our API to this code:
briefly mention the alternative to provide justification for this change.
```suggestion
While we _could_ duplicate the `None` check we added to the `GET` branch in each of the other cases, a simpler approach is to handle the `None` check before even checking for the verb. This lets us handle all three cases with a single piece of logic!

Let's make the change and then test our API, making sure each verb case works as expected!
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +        return Response("", status=404)
equivalent changes as above
```suggestion
    if book is None:
        return make_response("", 404)
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +We could refactor our code to a number of different solutions that are more elegant. Feel free to refactor!
elegant code is pretty subjective, and depends on what aspects you value. Maybe just leave it open ended?
```suggestion
There is no single correct way to structure our code. We could refactor our code to any number of different solutions. Feel free to refactor!
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +We can use the method `filter_by()` in order to filter our search query. We can give keyword arguments to describe the attribute and value we're filtering on. Consider this example that filters `Book
dangling preposition
```suggestion
We can use the method `filter_by()` in order to filter our search query. We can give keyword arguments to describe the attribute and value on which we're filtering. Consider this example that filters `Book`s by title.
```

2021-04-20 07:18 UTC, anselrognlie commented on more-flask-queries/404s-and-more-queries.md
> +There's way more to explore in filtering that is uncovered in this curriculum, so drive your own learning!
my brain _really_ wants "way more than" not "way more that", so while what was there is technically fine, I'd suggest this change.

```suggestion
There's way more to explore in filtering than is covered in this curriculum, so drive your own learning!
```

2021-04-20 16:07 UTC, tildeee commented on more-flask-queries/404s-and-more-queries.md
> +            return Response("", status=404)
I think `if not book` is totally reasonable at this point in the curriculum?

```suggestion
        if not book:
            return make_response("", 404)
```

2021-04-20 16:07 UTC, tildeee commented on more-flask-queries/404s-and-more-queries.md
> +| `return Response("", status=404)`                   | We sent back an empty string as our empty response body                                     |
If we're excited about `if not book`:

```suggestion
| `if not book:`                                  | This checks if `Book.query.get(book_id)` returned `None` because there was no matching book |
| `return make_response("", 404)`                   | We sent back an empty string as our empty response body and set the status code to `404 Not Found`                                     |
```

2021-04-20 16:08 UTC, tildeee commented on more-flask-queries/404s-and-more-queries.md
> +We can consider refactoring and then testing our API to this code:
Note for me/us to consider if the phrase "None check" is appropriate if we go the `if not book` way

2021-04-20 16:45 UTC, tildeee commented on update-and-delete/update-and-delete.md
> +1. Send back a response
Just want to explicitly say that I like this a lot and I'm learning form it!

2021-04-20 16:59 UTC, tildeee commented on update-and-delete/update-and-delete.md
> +| `return Response(...)`                              | This is one of many ways to return an HTTP response
This specific suggestion is helping me remember to continue to be repetitive in this curriculum (which I put a lot of effort into in Unit 1, but probably slipped on during Unit 2. Good to refresh myself for Unit 3!)

2021-04-20 17:43 UTC, tildeee commented on update-and-delete/update-and-delete.md
> +Then, make a request to `PUT /books/1` with our proper JSON request body.
This is such a small suggestion, I recognize I might be fixating on it, but I don't feel like this is necessary, and I would love reassurance that this will help the student experience!

2021-04-21 06:24 UTC, anselrognlie requested changes
comments for query params, finishing off this review pass

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +Often, the work of encoding happens _through the client_, not through the server. However, this knowledge may be helpful when constructing URLs with query strings for testing!
expand the guidance around when url encoding might be necessary
I really wanted to spell out that the replacement sequence is a percent followed by the ascii code of the character to replace encoded as 2 hexadecimal digits, but the curriculum only mentions ascii in passing once, and NEVER mentions hexadecimal.

More lightning talk candidates? (ascii/unicode, hexadecimal/number bases)

```suggestion
If we are using a program like Postman or a web browser to send requests, they will do their best to encode our URLs for us. If we are writing code to contact an endpoint, we may need to encode parts of the URL ourselves, using functionality built into Python.

We will try to avoid characters that require encoding in our URLs and query parameters. However, this knowledge may be helpful when constructing URLs with query strings for testing!
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +HTTP response bodies and query params are both responsible for adding data to a request, and can both accomplish similar things. The exact difference in usage will always depend on your project, cont
also mention route parameters
```suggestion
HTTP request bodies, route parameters, and query params are all responsible for adding data to a request, and can accomplish similar things. The exact difference in usage will always depend on your project, context, and needs.
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +- Query params contain data that describe the nature of the request
we don't need both however and typically
include info about route parameters
describe the nature seems vague. suggest presenting as customizing the request
```suggestion
In the style of web API we are building, typically:

- HTTP request bodies contain data that should be uploaded to the server
- Route parameters contain data that identifies a particular record
- Query params contain data that select customized behaviors
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +We may often see query params used for:
a little less hedge-y
```suggestion
Common uses for query params include:
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +| `query_param_value =`                               | We can make a local variable to represent the value of the param                       |
it doesn't represent the value. we store the value there
```suggestion
| `query_param_value =`                               | A local variable in which we store the looked up value of a query param for later use  |
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +The popular package `requests`, used for making HTTP requests, is not the same as the `request` that represents the HTTP request.
good idea to call this out, but I feel like providing a little more context about when to pay attention might help
```suggestion
The popular package `requests`, used for making HTTP requests, is not the same as the `request` that represents the HTTP request. If we are working on a web API project that also calls external APIs by using the `requests` package, we should be especially careful of whether we have written `request` or `requests`!
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +How we use query params now depends on our project needs, and using whatever Python strategies we need!
I don't think the use of query params has much to do with python intrinsically.
```suggestion
The way we choose to use query params will depend on our project needs.
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +### Predict HTTP Requests, Responses, and Logic
same change as elsewhere
```suggestion
### Planning HTTP Requests, Responses, and Logic
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +Let's consider the endpoint to get a single book:
(seems like a copy paste error)
actively discuss why this modification goes with the existing get all route
```suggestion
We want to get a list of book results, so the base of our endpoint will look like our usual endpoint to get all records of a particular type. We will use the `GET` verb sent to the `/books` endpoint. But now we'd also like to provide an additional parameter `title` that we can use to filter the results. Since filtering is a customization of the default _get all_ behavior, we can decide to express that as a query param.
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +No request body.
acknowledge why we don't need it
```suggestion
As usual, we don't need a request body for `GET` requests.
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +This assumes that there is at least a `book` table with the following rows. (The contents of `id`, `description`, and `completed_at` are irrelevant for this feature).
similar 'at least' change as elsewhere
completed at seems copy paste from task list
```suggestion
This assumes that there is a `book` table with at least the following rows. (The contents of `id`, and `description` are irrelevant for this feature).
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +The response we want to send back is:
remind what we want the response to do
```suggestion
In response to the request we've discussed, we want the endpoint to return success for the status code, and a list of the books with a matching title. We can use `200 OK` for the response status code, and a JSON response body representing a list of books.
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +During this method, we will need to:
essentially the same transition as elsewhere
```suggestion
Now that we have planned out these changes to our endpoint behavior, we can turn our attention to how to implement them.

Our endpoint will need to:
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +1. If we have a `title` query param, retrieve all of the books from the db that match
set up for a "pre-refactored" solution. If all we need to do is decide our source of books, we don't need to present a repetitive version where we have to generate the JSON book results twice. instead, we can jump to a better version where we get books from one of two branches, but the rendering remains unified.
```suggestion
1. If we have a `title` query param, retrieve all of the books from the database that match, otherwise retrieve all books as usual
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +## Finding Books by Title: Pseudocode
providing real code
```suggestion
## Finding Books by Title: Code
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +For this feature, we must return to our `GET` `"/books"` endpoint and re-work it.
While bringing this into alignment with previous edits, I noticed that we're a little inconsistent around how we refer to the routes. We had been referring to the show-like route as /<book_id>, even though it should be /books/<book_id>. So I put in some wiggle room here for both /books and "", but I'm a little unhappy. I might just need to be okay with this...
```suggestion
This endpoint uses the same path as our existing `/books` route that lists books. Recall that the `"/books"` part comes from the blueprint, so our route path is set to `""`.
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +Let's look at this example pseudocode for one strategy:
we're presenting actual code
```suggestion
Let's modify our endpoint code to filter the results when a title query param is supplied.
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +    # ... no other changes
revised with real code
went with handle_books for now. Change may be required with further PR?
The `if` that picks which `books` to use _could_ use ternary notation, but in the same way the examples avoid list comprehensions, I thought avoiding ternary would be better.
```suggestion
@books_bp.route("", methods=["GET", "POST"])
def handle_books():
    if request.method == "GET":
        # this code replaces the previous query all code
        title_query = request.args.get("title")
        if title_query:
            books = Book.query.filter_by(title=title_query)
        else:
            books = Book.query.all()
        # end of the new code

        books_response = []
        for book in books:
            books_response.append({
                "id": book.id,
                "title": book.title,
                "description": book.description
            })

        return jsonify(books_response)
    # ... existing code for creating a new book
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +
code description
```suggestion

| <div style="min-width:270px;"> Piece of Code </div> | Notes                                                                                                                                                           |
| --------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `title_query = ...`                                 | Store the result of looking for the `title` query param in the variable `title_query`                                                                           |
| `... = request.args.get("title")`                   | Try to get a query param called `title` from the `request`. This returns the value of the query param if it was set, or `None` if the query param is not found. |
| `if title_query:`                                   | Decide which conditional branch to take by checking whether we got a query param with which to filter                                                           |
| `books = ...`                                       | Store the results of our query in the `books` variable.                                                                                                         |
| `... = Book.query.filter_by( ... )`                 | If we got a query param, we will make a `filter_by` call to filter the results.                                                                                 |
| `title=title_query`                                 | Filter the book query results to those whose titles match the query param                                                                                       |
| `... = Book.query.all()`                            | If we didn't get a query param, get all the books as before.                                                                                                    |

The remainder of the code is the same as it was previously.

To summarize, we looked up whether the `title` query param was provided. We used that to decide which query we should run, and we stored the result in `books`. Then we converted `books` into JSON as before and returned the result.

```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +Our actual results will vary, depending on the contents of our databases. For example, if we've never created a `Book` with the title "Apple," then we'll never be able to retrieve that record!
the "never able" makes it sound like we can never create a book with a title of Apple, so reworked that
```suggestion
Our actual results will vary, depending on the contents of our databases. For example, if we haven't created any `Book`s with the title "Apple," then the second test will always return an empty list!
```

2021-04-21 06:24 UTC, anselrognlie commented on more-flask-queries/query-params.md
> +Different records on different databases will change our tests and results.
this sounds a bit throw-away. added the "predict, then test" to sneak in an additional takeaway
```suggestion
We should practice trying to predict the results of a test before running it to check our understanding. But we must take into account what records exist in our database, since this will affect our tests and results.
```

2021-04-21 21:10 UTC, tildeee commented on update-and-delete/update-and-delete.md
> +| `f"Book #{book.id} successfully deleted"`           | We can still access `book.id` because the variable itself is still in scope in our app, even if the `book` _was_ successfully deleted in the da
Let's try it this cohort without the callout, and I'll look out for how that goes

2021-04-21 21:20 UTC, tildeee commented on more-flask-queries/query-params.md
> +Often, the work of encoding happens _through the client_, not through the server. However, this knowledge may be helpful when constructing URLs with query strings for testing!
Just added these topic suggestions for Unit 3 lightning talks, thank you!!!

2021-04-21 22:24 UTC, merged